
import { CategoryData } from './types';
import { CUSTOM_CATEGORIES } from './customCategories';

/**
 * BASE DE DATOS ORIGINAL
 * Se mantiene inalterada. Las nuevas palabras se fusionan al final del archivo.
 */
const BASE_CATEGORIES: Record<string, CategoryData[]> = {
    "Objetos Cotidianos": [
        { civ: "Móvil", imp: "Tablet", hints: ["Dispositivo", "Electrónica", "Pantalla"] },
        { civ: "Llaves", imp: "Mando", hints: ["Apertura", "Acceso", "Metal"] },
        { civ: "Reloj", imp: "Cronómetro", hints: ["Tiempo", "Medición", "Muñeca"] },
        { civ: "Gafas", imp: "Lentillas", hints: ["Visión", "Óptica", "Cristal"] },
        { civ: "Bolígrafo", imp: "Rotulador", hints: ["Escritura", "Tinta", "Trazo"] },
        { civ: "Fregona", imp: "Escoba", hints: ["Limpieza", "Suelo", "Mango"] },
        { civ: "Paraguas", imp: "Chubasquero", hints: ["Lluvia", "Protección", "Agua"] },
        { civ: "Cuchara", imp: "Tenedor", hints: ["Cubierto", "Vajilla", "Comer"] },
        { civ: "Silla", imp: "Taburete", hints: ["Asiento", "Mueble", "Respaldo"] },
        { civ: "Cama", imp: "Sofá", hints: ["Descanso", "Mueble", "Confort"] },
        { civ: "Espejo", imp: "Cristal", hints: ["Reflejo", "Imagen", "Baño"] },
        { civ: "Libro", imp: "Revista", hints: ["Lectura", "Papel", "Cultura"] },
        { civ: "Monedero", imp: "Cartera", hints: ["Dinero", "Cuero", "Bolsillo"] },
        { civ: "Zapatillas", imp: "Zapatos", hints: ["Calzado", "Pies", "Suela"] },
        { civ: "Peine", imp: "Cepillo", hints: ["Cabello", "Aseo", "Púas"] },
        { civ: "Vela", imp: "Bombilla", hints: ["Luz", "Energía", "Calor"] },
        { civ: "Mochila", imp: "Maleta", hints: ["Equipaje", "Viaje", "Carga"] },
        { civ: "Toalla", imp: "Albornoz", hints: ["Aseo", "Baño", "Tejido"] },
        { civ: "Televisor", imp: "Monitor", hints: ["Pantalla", "Imagen", "Ocio"] },
        { civ: "Botella", imp: "Cantimplora", hints: ["Recipiente", "Líquido", "Plástico"] },
        { civ: "Ventilador", imp: "Climatizador", hints: ["Aire", "Fresco", "Verano"] },
        { civ: "Tijeras", imp: "Cúter", hints: ["Corte", "Filo", "Manualidad"] },
        { civ: "Cargador", imp: "Batería", hints: ["Energía", "Corriente", "Cable"] },
        { civ: "Almohada", imp: "Cojín", hints: ["Descanso", "Blando", "Cama"] },
        { civ: "Plato", imp: "Cuenco", hints: ["Vajilla", "Recipiente", "Cerámica"] },
        { civ: "Caja", imp: "Paquete", hints: ["Envío", "Cartón", "Contenedor"] },
        { civ: "Papel", imp: "Cartón", hints: ["Material", "Celulosa", "Lámina"] },
        { civ: "Auriculares", imp: "Altavoz", hints: ["Audio", "Sonido", "Música"] },
        { civ: "Plancha", imp: "Secador", hints: ["Ropa", "Calor", "Hogar"] },
        { civ: "Martillo", imp: "Alicates", hints: ["Herramienta", "Metal", "Fuerza"] },
        { civ: "Cinturón", imp: "Tirantes", hints: ["Ropa", "Sujeción", "Cintura"] },
        { civ: "Agenda", imp: "Calendario", hints: ["Organización", "Fecha", "Planificación"] },
        { civ: "Cafetera", imp: "Tetera", hints: ["Cocina", "Desayuno", "Caliente"] },
        { civ: "Papelera", imp: "Contenedor", hints: ["Residuos", "Basura", "Desecho"] },
        { civ: "Sombrero", imp: "Gorra", hints: ["Accesorio", "Cabeza", "Prenda"] }
    ],
    "Personas Famosas": [
        { civ: "Rosalía", imp: "Aitana", hints: ["Cantante", "Artista", "Famosa"] },
        { civ: "Rafa Nadal", imp: "Carlos Alcaraz", hints: ["Tenista", "Deportista", "España"] },
        { civ: "Ibai Llanos", imp: "AuronPlay", hints: ["Streamer", "Internet", "Contenido"] },
        { civ: "Antonio Banderas", imp: "Javier Bardem", hints: ["Actor", "Hollywood", "Malagueño"] },
        { civ: "Penélope Cruz", imp: "Blanca Suárez", hints: ["Actriz", "Cine", "Estrella"] },
        { civ: "Fernando Alonso", imp: "Carlos Sainz", hints: ["Piloto", "Motor", "Velocidad"] },
        { civ: "Pau Gasol", imp: "Marc Gasol", hints: ["Baloncesto", "NBA", "Altura"] },
        { civ: "Dalí", imp: "Picasso", hints: ["Pintor", "Arte", "Genio"] },
        { civ: "Cervantes", imp: "Quevedo", hints: ["Escritor", "Letras", "Libro"] },
        { civ: "Iniesta", imp: "Casillas", hints: ["Futbolista", "Selección", "Leyenda"] },
        { civ: "Leo Messi", imp: "Cristiano", hints: ["Delantero", "Balón", "Goleador"] },
        { civ: "Elon Musk", imp: "Bill Gates", hints: ["Magnate", "Tecnología", "Riqueza"] },
        { civ: "Almodóvar", imp: "Amenábar", hints: ["Director", "Cine", "Premios"] },
        { civ: "Alaska", imp: "Chenoa", hints: ["Música", "Pop", "Televisión"] },
        { civ: "Joaquín Sabina", imp: "Serrat", hints: ["Cantautor", "Poeta", "Voz"] },
        { civ: "Rubius", imp: "Grefg", hints: ["Youtuber", "Juegos", "Influencer"] },
        { civ: "De Gea", imp: "Oblak", hints: ["Portero", "Fútbol", "Guantes"] },
        { civ: "Úrsula Corberó", imp: "Najwa Nimri", hints: ["Actriz", "Netflix", "Serie"] },
        { civ: "Felipe VI", imp: "Letizia", hints: ["Monarquía", "Casa", "Estado"] },
        { civ: "Belén Esteban", imp: "Jorge Javier", hints: ["Telecinco", "Prensa", "Famoso"] },
        { civ: "Lady Gaga", imp: "Madonna", hints: ["Icono", "Música", "Pop"] },
        { civ: "Don Quijote", imp: "Sancho Panza", hints: ["Personaje", "Mancha", "Literatura"] },
        { civ: "Yamal", imp: "Williams", hints: ["Joven", "Fútbol", "Eurocopa"] },
        { civ: "Santiago Segura", imp: "Dani Rovira", hints: ["Cine", "Cómico", "España"] },
        { civ: "LeBron James", imp: "Curry", hints: ["NBA", "Basket", "Estrella"] },
        { civ: "Shakira", imp: "Karol G", hints: ["Cantante", "Latina", "Música"] },
        { civ: "Bad Bunny", imp: "Quevedo", hints: ["Trap", "Urbano", "Éxito"] },
        { civ: "Taylor Swift", imp: "Beyoncé", hints: ["Pop", "Gira", "Cantante"] },
        { civ: "Mbappé", imp: "Haaland", hints: ["Fútbol", "Fichaje", "Goleador"] },
        { civ: "Broncano", imp: "Buenafuente", hints: ["Humor", "Late", "Presentador"] },
        { civ: "Paco de Lucía", imp: "Camarón", hints: ["Flamenco", "Música", "Andalucía"] },
        { civ: "Amancio Ortega", imp: "Juan Roig", hints: ["Empresario", "Zara", "Riqueza"] },
        { civ: "Lola Flores", imp: "Rocío Jurado", hints: ["Artista", "España", "Folclore"] },
        { civ: "Risto Mejide", imp: "Arturo Valls", hints: ["TV", "Jurado", "Famoso"] },
        { civ: "Bizarrap", imp: "Guetta", hints: ["DJ", "Música", "Productor"] }
    ],
    "Comidas y Bebidas": [
        { civ: "Tortilla", imp: "Revuelto", hints: ["Huevo", "Cena", "Sartén"] },
        { civ: "Gazpacho", imp: "Salmorejo", hints: ["Tomate", "Frío", "Verano"] },
        { civ: "Paella", imp: "Risotto", hints: ["Arroz", "Plato", "Amarillo"] },
        { civ: "Croqueta", imp: "Empanadilla", hints: ["Frito", "Tapa", "Bechamel"] },
        { civ: "Jamón", imp: "Lomo", hints: ["Cerdo", "Embutido", "Curado"] },
        { civ: "Cerveza", imp: "Sidra", hints: ["Bebida", "Alcohol", "Fermentada"] },
        { civ: "Café", imp: "Cortado", hints: ["Desayuno", "Taza", "Energía"] },
        { civ: "Vino", imp: "Cava", hints: ["Uva", "Copa", "Bebida"] },
        { civ: "Zumo", imp: "Batido", hints: ["Fruta", "Vaso", "Natural"] },
        { civ: "Churros", imp: "Porras", hints: ["Desayuno", "Masa", "Aceite"] },
        { civ: "Pizza", imp: "Lasaña", hints: ["Trigo", "Queso", "Italiano"] },
        { civ: "Sushi", imp: "Sashimi", hints: ["Pescado", "Arroz", "Asia"] },
        { civ: "Hamburguesa", imp: "Perrito", hints: ["Rápida", "Carne", "Pan"] },
        { civ: "Bravas", imp: "Alioli", hints: ["Salsa", "Patata", "Picante"] },
        { civ: "Agua", imp: "Casera", hints: ["Bebida", "Transparente", "Sed"] },
        { civ: "Cola", imp: "Fanta", hints: ["Burbuja", "Refresco", "Azúcar"] },
        { civ: "Taco", imp: "Burrito", hints: ["México", "Carne", "Tortilla"] },
        { civ: "Helado", imp: "Sorbeto", hints: ["Frío", "Postre", "Azúcar"] },
        { civ: "Lentejas", imp: "Garbanzos", hints: ["Cuchara", "Legumbre", "Guiso"] },
        { civ: "Bacalao", imp: "Merluza", hints: ["Pescado", "Blanco", "Mar"] },
        { civ: "Manchego", imp: "Cabrales", hints: ["Queso", "Lácteo", "Oveja"] },
        { civ: "Calamares", imp: "Chopitos", hints: ["Mar", "Frito", "Bocadillo"] },
        { civ: "Donut", imp: "Croissant", hints: ["Bollería", "Dulce", "Masa"] },
        { civ: "Albóndigas", imp: "Filete", hints: ["Carne", "Plato", "Cena"] },
        { civ: "Leche", imp: "Horchata", hints: ["Bebida", "Blanco", "Vaso"] },
        { civ: "Té", imp: "Poleo", hints: ["Infusión", "Hierba", "Taza"] },
        { civ: "Pipas", imp: "Almendras", hints: ["Fruto", "Cáscara", "Sal"] },
        { civ: "Macarrones", imp: "Tallarines", hints: ["Pasta", "Salsa", "Trigo"] },
        { civ: "Yogur", imp: "Cuajada", hints: ["Postre", "Cuchara", "Lácteo"] },
        { civ: "Mojito", imp: "Daiquiri", hints: ["Cóctel", "Hielo", "Copa"] },
        { civ: "Flan", imp: "Natillas", hints: ["Huevo", "Dulce", "Postre"] },
        { civ: "Chistorra", imp: "Chorizo", hints: ["Carne", "Rojo", "Cerdo"] },
        { civ: "Pan", imp: "Baguette", hints: ["Trigo", "Horno", "Barra"] },
        { civ: "Aceitunas", imp: "Pepinillos", hints: ["Vinagre", "Aperitivo", "Verde"] },
        { civ: "Whisky", imp: "Ron", hints: ["Fuerte", "Destilado", "Copa"] }
    ],
    "Animales": [
        { civ: "Perro", imp: "Lobo", hints: ["Cánido", "Colmillos", "Ladrar"] },
        { civ: "Gato", imp: "Lince", hints: ["Felino", "Garras", "Sigilo"] },
        { civ: "Caballo", imp: "Burro", hints: ["Equino", "Cascos", "Campo"] },
        { civ: "Vaca", imp: "Toro", hints: ["Cuernos", "Prado", "Ganado"] },
        { civ: "Águila", imp: "Halcón", hints: ["Rapaz", "Vuelo", "Garras"] },
        { civ: "León", imp: "Tigre", hints: ["Depredador", "Sabana", "Fiera"] },
        { civ: "Elefante", imp: "Mamut", hints: ["Trompa", "Marfil", "Orejas"] },
        { civ: "Delfín", imp: "Orca", hints: ["Marino", "Salto", "Agua"] },
        { civ: "Serpiente", imp: "Víbora", hints: ["Reptil", "Veneno", "Escamas"] },
        { civ: "Mono", imp: "Gorila", hints: ["Selva", "Primate", "Manos"] },
        { civ: "Oveja", imp: "Cabra", hints: ["Lana", "Granja", "Rebaño"] },
        { civ: "Gallina", imp: "Pato", hints: ["Ave", "Plumas", "Pico"] },
        { civ: "Tiburón", imp: "Raya", hints: ["Océano", "Aleta", "Dientes"] },
        { civ: "Hormiga", imp: "Abeja", hints: ["Insecto", "Pequeño", "Colonia"] },
        { civ: "Oso", imp: "Panda", hints: ["Montaña", "Pelo", "Garras"] },
        { civ: "Conejo", imp: "Liebre", hints: ["Orejas", "Salto", "Campo"] },
        { civ: "Rana", imp: "Sapo", hints: ["Agua", "Salto", "Lengua"] },
        { civ: "Pingüino", imp: "Foca", hints: ["Frío", "Hielo", "Piel"] },
        { civ: "Jirafa", imp: "Cebra", hints: ["África", "Cuello", "Piel"] },
        { civ: "Cerdo", imp: "Jabalí", hints: ["Hocico", "Barro", "Piel"] },
        { civ: "Mariposa", imp: "Polilla", hints: ["Alas", "Vuelo", "Color"] },
        { civ: "Araña", imp: "Alacrán", hints: ["Veneno", "Patas", "Red"] },
        { civ: "Murciélago", imp: "Vampiro", hints: ["Noche", "Cueva", "Vuelo"] },
        { civ: "Canguro", imp: "Koala", hints: ["Bolsa", "Salto", "Animal"] },
        { civ: "Camello", imp: "Dromedario", hints: ["Desierto", "Joroba", "Sed"] },
        { civ: "Pulpo", imp: "Sepia", hints: ["Tentáculos", "Mar", "Tinta"] },
        { civ: "Búho", imp: "Lechuza", hints: ["Noche", "Ojos", "Vuelo"] },
        { civ: "Ardilla", imp: "Hamster", hints: ["Cola", "Pequeño", "Frutos"] },
        { civ: "Loro", imp: "Periquito", hints: ["Pájaro", "Plumas", "Hablar"] },
        { civ: "Cocodrilo", imp: "Iguana", hints: ["Escamas", "Dientes", "Río"] },
        { civ: "Caracol", imp: "Babosa", hints: ["Lento", "Baba", "Concha"] },
        { civ: "Zorro", imp: "Hiena", hints: ["Astuto", "Cola", "Colmillos"] },
        { civ: "Flamenco", imp: "Cigüeña", hints: ["Rosa", "Patas", "Pájaro"] },
        { civ: "Hipopótamo", imp: "Rinoceronte", hints: ["Peso", "Piel", "África"] },
        { civ: "Medusa", imp: "Coral", hints: ["Mar", "Picadura", "Gelatina"] }
    ],
    "Marcas y Logotipos": [
        { civ: "Zara", imp: "Mango", hints: ["Moda", "Tienda", "Ropa"] },
        { civ: "Mercadona", imp: "Lidl", hints: ["Supermercado", "Comida", "Compra"] },
        { civ: "Nike", imp: "Puma", hints: ["Deporte", "Marca", "Ropa"] },
        { civ: "Apple", imp: "Samsung", hints: ["Logo", "Móvil", "Pc"] },
        { civ: "Coca-Cola", imp: "Pepsi", hints: ["Refresco", "Burbuja", "Marca"] },
        { civ: "Seat", imp: "Renault", hints: ["Coche", "Motor", "Logo"] },
        { civ: "Iberia", imp: "Vueling", hints: ["Vuelo", "Avión", "Viaje"] },
        { civ: "Santander", imp: "BBVA", hints: ["Banco", "Dinero", "Tarjeta"] },
        { civ: "Movistar", imp: "Vodafone", hints: ["Móvil", "Red", "Fibra"] },
        { civ: "Repsol", imp: "Cepsa", hints: ["Combustible", "Luz", "Energía"] },
        { civ: "Amazon", imp: "AliExpress", hints: ["Paquete", "Web", "Envío"] },
        { civ: "Netflix", imp: "HBO", hints: ["Pantalla", "Película", "Streaming"] },
        { civ: "Instagram", imp: "Facebook", hints: ["Perfil", "Foto", "Social"] },
        { civ: "Starbucks", imp: "Dunkin", hints: ["Vaso", "Café", "Logo"] },
        { civ: "McDonald's", imp: "Burger", hints: ["Patata", "Comida", "Rápida"] },
        { civ: "Nivea", imp: "Dove", hints: ["Piel", "Crema", "Cuidado"] },
        { civ: "Lego", imp: "Playmobil", hints: ["Figura", "Juguete", "Pieza"] },
        { civ: "Danone", imp: "Nestlé", hints: ["Lácteo", "Alimento", "Yogur"] },
        { civ: "El Corte Inglés", imp: "Fnac", hints: ["Centro", "Compra", "Tienda"] },
        { civ: "IKEA", imp: "Leroy", hints: ["Casa", "Mueble", "Hogar"] },
        { civ: "Disney", imp: "Pixar", hints: ["Dibujo", "Niño", "Cine"] },
        { civ: "Spotify", imp: "Tidal", hints: ["Audio", "Música", "Red"] },
        { civ: "PlayStation", imp: "Xbox", hints: ["Consola", "Mando", "Mando"] },
        { civ: "Ferrari", imp: "Porsche", hints: ["Logo", "Coche", "Lujo"] },
        { civ: "Lacoste", imp: "Ralph", hints: ["Logo", "Ropa", "Marca"] },
        { civ: "Hacendado", imp: "Carrefour", hints: ["Marca", "Barata", "Blanca"] },
        { civ: "Campofrío", imp: "ElPozo", hints: ["Carne", "Marca", "Lomo"] },
        { civ: "Bimbo", imp: "Panrico", hints: ["Masa", "Pan", "Marca"] },
        { civ: "Telepizza", imp: "Domino's", hints: ["Pizza", "Cena", "Motillo"] },
        { civ: "Visa", imp: "Mastercard", hints: ["Dinero", "Pago", "Tarjeta"] },
        { civ: "Google", imp: "Yahoo", hints: ["Web", "Buscador", "Letras"] },
        { civ: "Rolex", imp: "Casio", hints: ["Muñeca", "Reloj", "Lujo"] },
        { civ: "Red Bull", imp: "Monster", hints: ["Energía", "Bebida", "Lata"] },
        { civ: "Renfe", imp: "Iryo", hints: ["Vía", "Raíl", "Tren"] },
        { civ: "Bershka", imp: "Stradivarius", hints: ["Inditex", "Tienda", "Ropa"] }
    ],
    "Colores y Formas": [
        { civ: "Rojo", imp: "Granate", hints: ["Cálido", "Sangre", "Pasión"] },
        { civ: "Azul", imp: "Cian", hints: ["Cielo", "Mar", "Frío"] },
        { civ: "Círculo", imp: "Óvalo", hints: ["Redondo", "Línea", "Curva"] },
        { civ: "Cuadrado", imp: "Rectángulo", hints: ["Esquina", "Ángulo", "Lado"] },
        { civ: "Amarillo", imp: "Dorado", hints: ["Luz", "Sol", "Brillo"] },
        { civ: "Verde", imp: "Lima", hints: ["Prado", "Natural", "Hierba"] },
        { civ: "Triángulo", imp: "Rombo", hints: ["Figura", "Vértice", "Línea"] },
        { civ: "Rosa", imp: "Fucsia", hints: ["Suave", "Color", "Pétalo"] },
        { civ: "Negro", imp: "Gris", hints: ["Noche", "Sombra", "Oscuro"] },
        { civ: "Blanco", imp: "Beige", hints: ["Luz", "Claro", "Nieve"] },
        { civ: "Naranja", imp: "Butano", hints: ["Color", "Fuego", "Fruta"] },
        { civ: "Morado", imp: "Lila", hints: ["Violeta", "Color", "Uva"] },
        { civ: "Cubo", imp: "Esfera", hints: ["Forma", "Espacio", "Volumen"] },
        { civ: "Estrella", imp: "Pentágono", hints: ["Forma", "Punta", "Cielo"] },
        { civ: "Hexágono", imp: "Octógono", hints: ["Geometría", "Lado", "Línea"] },
        { civ: "Marrón", imp: "Castaño", hints: ["Tierra", "Madera", "Color"] },
        { civ: "Transparente", imp: "Opaco", hints: ["Efecto", "Cristal", "Visión"] },
        { civ: "Mate", imp: "Brillo", hints: ["Luz", "Textura", "Capa"] },
        { civ: "Línea", imp: "Punto", hints: ["Trazo", "Dibujo", "Marca"] },
        { civ: "Diamante", imp: "Pica", hints: ["Carta", "Figura", "Brillo"] },
        { civ: "Turquesa", imp: "Esmeralda", hints: ["Color", "Piedra", "Agua"] },
        { civ: "Plata", imp: "Bronce", hints: ["Metal", "Color", "Brillo"] },
        { civ: "Corazón", imp: "Cruz", hints: ["Símbolo", "Forma", "Icono"] },
        { civ: "Flecha", imp: "Rayo", hints: ["Señal", "Figura", "Dirección"] },
        { civ: "Cilindro", imp: "Cono", hints: ["Tubo", "Forma", "Volumen"] },
        { civ: "Espiral", imp: "Zigzag", hints: ["Línea", "Curva", "Trazo"] },
        { civ: "Neón", imp: "Flúor", hints: ["Luz", "Color", "Llamativo"] },
        { civ: "Cápsula", imp: "Pastilla", hints: ["Forma", "Farmacia", "Mano"] },
        { civ: "Mancha", imp: "Gota", hints: ["Agua", "Forma", "Marca"] },
        { civ: "Sombra", imp: "Luz", hints: ["Visión", "Ojos", "Efecto"] },
        { civ: "Militar", imp: "Oliva", hints: ["Verde", "Tono", "Oscuro"] },
        { civ: "Trapecio", imp: "Pirámide", hints: ["Base", "Figura", "Lado"] },
        { civ: "Anillo", imp: "Aro", hints: ["Dedo", "Redondo", "Metal"] },
        { civ: "Puente", imp: "Arco", hints: ["Río", "Forma", "Vía"] },
        { civ: "Cian", imp: "Magenta", hints: ["Color", "Tinta", "Papel"] }
    ],
    "Países y Ciudades": [
        { civ: "España", imp: "Portugal", hints: ["Europa", "Península", "Fútbol"] },
        { civ: "Madrid", imp: "Barcelona", hints: ["Ciudad", "España", "Capital"] },
        { civ: "Francia", imp: "Italia", hints: ["Mapa", "Europa", "Bandera"] },
        { civ: "Sevilla", imp: "Granada", hints: ["Sur", "Andalucía", "Calor"] },
        { civ: "Londres", imp: "París", hints: ["Turismo", "Torre", "Ciudad"] },
        { civ: "Alemania", imp: "Austria", hints: ["Idioma", "Mapa", "Europa"] },
        { civ: "Valencia", imp: "Alicante", hints: ["Playa", "Costa", "Paella"] },
        { civ: "Japón", imp: "China", hints: ["Asia", "Mapa", "Isla"] },
        { civ: "Nueva York", imp: "Chicago", hints: ["EEUU", "Mapa", "Cine"] },
        { civ: "Bilbao", imp: "Vitoria", hints: ["Norte", "Euskadi", "Frío"] },
        { civ: "Marruecos", imp: "Túnez", hints: ["África", "Calor", "Mapa"] },
        { civ: "México", imp: "Colombia", hints: ["Idioma", "Mapa", "Comida"] },
        { civ: "Zaragoza", imp: "Huesca", hints: ["Aragón", "Ebro", "Pilar"] },
        { civ: "Málaga", imp: "Marbella", hints: ["Costa", "Andalucía", "Sol"] },
        { civ: "Roma", imp: "Venecia", hints: ["Italia", "Historia", "Canal"] },
        { civ: "Berlín", imp: "Munich", hints: ["Cerveza", "Muro", "Coche"] },
        { civ: "Vigo", imp: "Coruña", hints: ["Galicia", "Mar", "Lluvia"] },
        { civ: "Rusia", imp: "Polonia", hints: ["Este", "Frío", "Mapa"] },
        { civ: "Australia", imp: "Islandia", hints: ["Isla", "Lejos", "Mar"] },
        { civ: "Toledo", imp: "Segovia", hints: ["Castilla", "Historia", "Piedra"] },
        { civ: "Tenerife", imp: "Lanzarote", hints: ["Canarias", "Isla", "Vulcano"] },
        { civ: "Palma", imp: "Ibiza", hints: ["Baleares", "Isla", "Playa"] },
        { civ: "Salamanca", imp: "Valladolid", hints: ["Universidad", "León", "Castilla"] },
        { civ: "Murcia", imp: "Cartagena", hints: ["Costa", "Sur", "Huerta"] },
        { civ: "Brasil", imp: "Argentina", hints: ["Fútbol", "Mapa", "Cumbia"] },
        { civ: "Oviedo", imp: "Gijón", hints: ["Sidra", "Asturias", "Norte"] },
        { civ: "Santander", imp: "Laredo", hints: ["Norte", "Cantabria", "Mar"] },
        { civ: "Pamplona", imp: "Logroño", hints: ["Vino", "Toros", "Norte"] },
        { civ: "Lisboa", imp: "Oporto", hints: ["Fado", "Puente", "Río"] },
        { civ: "Ámsterdam", imp: "Bruselas", hints: ["Canal", "Europa", "Ciudad"] },
        { civ: "Tokio", imp: "Kioto", hints: ["Templos", "Luz", "Japón"] },
        { civ: "Canadá", imp: "Suiza", hints: ["Nieve", "Montaña", "Frío"] },
        { civ: "Estambul", imp: "Atenas", hints: ["Historia", "Mar", "Mapa"] },
        { civ: "Cádiz", imp: "Huelva", hints: ["Luz", "Carnaval", "Andalucía"] },
        { civ: "Cáceres", imp: "Badajoz", hints: ["Extremadura", "Bellota", "Tierra"] }
    ],
    "Emociones y Sentimientos": [
        { civ: "Alegría", imp: "Euforia", hints: ["Positivo", "Risa", "Ánimo"] },
        { civ: "Tristeza", imp: "Pena", hints: ["Llantos", "Ánimo", "Ojos"] },
        { civ: "Miedo", imp: "Pánico", hints: ["Susto", "Grito", "Oscuro"] },
        { civ: "Ira", imp: "Rencor", hints: ["Enfado", "Rojo", "Fuerte"] },
        { civ: "Amor", imp: "Cariño", hints: ["Afecto", "Abrazo", "Corazón"] },
        { civ: "Sorpresa", imp: "Alarma", hints: ["Inesperado", "Cara", "Susto"] },
        { civ: "Asco", imp: "Rechazo", hints: ["Boca", "Reacción", "Gesto"] },
        { civ: "Aburrimiento", imp: "Cansancio", hints: ["Sueño", "Gesto", "Tedio"] },
        { civ: "Envidia", imp: "Celos", hints: ["Deseo", "Amigo", "Rabia"] },
        { civ: "Orgullo", imp: "Soberbia", hints: ["Ego", "Cara", "Valor"] },
        { civ: "Culpa", imp: "Pesar", hints: ["Error", "Fallo", "Mente"] },
        { civ: "Vergüenza", imp: "Timidez", hints: ["Rojo", "Cara", "Gesto"] },
        { civ: "Esperanza", imp: "Ilusión", hints: ["Futuro", "Sueño", "Mente"] },
        { civ: "Paz", imp: "Calma", hints: ["Relajación", "Mente", "Silencio"] },
        { civ: "Duda", imp: "Confusión", hints: ["Pregunta", "Mente", "Gesto"] },
        { civ: "Gratitud", imp: "Favor", hints: ["Gracias", "Ayuda", "Amigo"] },
        { civ: "Soledad", imp: "Vacío", hints: ["Solo", "Casa", "Lugar"] },
        { civ: "Ansiedad", imp: "Estrés", hints: ["Nervios", "Mente", "Aire"] },
        { civ: "Pasión", imp: "Fuego", hints: ["Intenso", "Corazón", "Gesto"] },
        { civ: "Alivio", imp: "Respiro", hints: ["Final", "Mente", "Aire"] },
        { civ: "Odio", imp: "Ira", hints: ["Fuerte", "Mente", "Enfado"] },
        { civ: "Fe", imp: "Confianza", hints: ["Creer", "Mente", "Mano"] },
        { civ: "Lástima", imp: "Piedad", hints: ["Ayuda", "Ojos", "Triste"] },
        { civ: "Interés", imp: "Ganas", hints: ["Atención", "Mente", "Ojos"] },
        { civ: "Recuerdo", imp: "Olvido", hints: ["Pasado", "Mente", "Foto"] },
        { civ: "Rabia", imp: "Enfado", hints: ["Grito", "Rojo", "Mano"] },
        { civ: "Optimismo", imp: "Dicha", hints: ["Bien", "Risa", "Ánimo"] },
        { civ: "Dolor", imp: "Sufrimiento", hints: ["Mal", "Cuerpo", "Grito"] },
        { civ: "Respeto", imp: "Honor", hints: ["Valor", "Amigo", "Mano"] },
        { civ: "Paciencia", imp: "Espera", hints: ["Tiempo", "Mente", "Reloj"] },
        { civ: "Motivación", imp: "Impulso", hints: ["Energía", "Meta", "Ánimo"] },
        { civ: "Humor", imp: "Risa", hints: ["Gracia", "Chiste", "Cara"] },
        { civ: "Pena", imp: "Duelo", hints: ["Triste", "Llorar", "Ojos"] },
        { civ: "Felicidad", imp: "Gozo", hints: ["Estado", "Ánimo", "Bien"] },
        { civ: "Coraje", imp: "Valor", hints: ["Héroe", "Acción", "Fuerte"] }
    ],
    "Aficiones y Actividades": [
        { civ: "Leer", imp: "Hoja", hints: ["Libro", "Cultura", "Letra"] },
        { civ: "Cocinar", imp: "Guisar", hints: ["Comida", "Fuego", "Sartén"] },
        { civ: "Correr", imp: "Andar", hints: ["Pies", "Deporte", "Calle"] },
        { civ: "Nadar", imp: "Bucear", hints: ["Agua", "Mar", "Cuerpo"] },
        { civ: "Viajar", imp: "Turismo", hints: ["Maleta", "Avión", "Mapa"] },
        { civ: "Dibujar", imp: "Pintar", hints: ["Arte", "Lápiz", "Papel"] },
        { civ: "Cantar", imp: "Gritar", hints: ["Voz", "Boca", "Música"] },
        { civ: "Bailar", imp: "Saltar", hints: ["Mover", "Cuerpo", "Ritmo"] },
        { civ: "Gamers", imp: "Consola", hints: ["Mando", "Pantalla", "Ocio"] },
        { civ: "Series", imp: "Pelis", hints: ["Netflix", "Televisión", "Pantalla"] },
        { civ: "Gimnasio", imp: "Pesas", hints: ["Fuerza", "Músculo", "Sudor"] },
        { civ: "Fotos", imp: "Cámara", hints: ["Lente", "Imagen", "Flash"] },
        { civ: "Plantas", imp: "Huerto", hints: ["Verde", "Tierra", "Jardín"] },
        { civ: "Pescar", imp: "Cazar", hints: ["Campo", "Animal", "Silencio"] },
        { civ: "Compras", imp: "Rebajas", hints: ["Tienda", "Dinero", "Bolsa"] },
        { civ: "Concierto", imp: "Ópera", hints: ["Escenario", "Música", "Público"] },
        { civ: "Yoga", imp: "Zen", hints: ["Relajación", "Mente", "Cuerpo"] },
        { civ: "Escalar", imp: "Senda", hints: ["Monte", "Arnés", "Roca"] },
        { civ: "Skate", imp: "Patín", hints: ["Rueda", "Tabla", "Calle"] },
        { civ: "Bici", imp: "Moto", hints: ["Vehículo", "Ruedas", "Manillar"] },
        { civ: "Cartas", imp: "Damas", hints: ["Juego", "Mesa", "Mano"] },
        { civ: "Piano", imp: "Guitarra", hints: ["Instrumento", "Cuerda", "Dedo"] },
        { civ: "Camping", imp: "Vivac", hints: ["Tienda", "Campo", "Dormir"] },
        { civ: "Surf", imp: "Vela", hints: ["Mar", "Olas", "Tabla"] },
        { civ: "Puzle", imp: "Maqueta", hints: ["Piezas", "Mano", "Encajar"] },
        { civ: "Monedas", imp: "Sellos", hints: ["Colección", "Papel", "Álbum"] },
        { civ: "Reparar", imp: "Montar", hints: ["Herramienta", "Mano", "Arreglar"] },
        { civ: "Inglés", imp: "Chino", hints: ["Idioma", "Hablar", "Libro"] },
        { civ: "Actuar", imp: "Teatro", hints: ["Cine", "Escenario", "Guion"] },
        { civ: "Coser", imp: "Tejer", hints: ["Hilo", "Aguja", "Tejido"] },
        { civ: "Cine", imp: "Palomitas", hints: ["Pantalla", "Butaca", "Varios"] },
        { civ: "Pádel", imp: "Tenis", hints: ["Raqueta", "Pelota", "Red"] },
        { civ: "Sol", imp: "Playa", hints: ["Verano", "Toalla", "Calor"] },
        { civ: "Siesta", imp: "Sueño", hints: ["Sofá", "Cama", "Dormir"] },
        { civ: "Tapeo", imp: "Cañas", hints: ["Bar", "Amigo", "Caña"] }
    ],
    "Cultura de Internet": [
        { civ: "Meme", imp: "Imagen", hints: ["Gracia", "Red", "Viral"] },
        { civ: "Influencer", imp: "Famoso", hints: ["Redes", "Perfil", "Foto"] },
        { civ: "Streamer", imp: "Ibai", hints: ["Twitch", "Directo", "Cámara"] },
        { civ: "TikTok", imp: "Reels", hints: ["Vídeo", "Móvil", "Famoso"] },
        { civ: "Viral", imp: "Fama", hints: ["Éxito", "Web", "Compartir"] },
        { civ: "Hashtag", imp: "Etiqueta", hints: ["Texto", "Azul", "Red"] },
        { civ: "Spam", imp: "Basura", hints: ["Correo", "Web", "Mucho"] },
        { civ: "Troll", imp: "Hater", hints: ["Usuario", "Chat", "Malo"] },
        { civ: "Emoji", imp: "Icono", hints: ["Cara", "Chat", "Amarillo"] },
        { civ: "Wifi", imp: "Red", hints: ["Señal", "Internet", "Invisible"] },
        { civ: "Google", imp: "Bing", hints: ["Buscador", "Letras", "Info"] },
        { civ: "Spoiler", imp: "Final", hints: ["Serie", "Chat", "Sorpresa"] },
        { civ: "Reto", imp: "Challenge", hints: ["Prueba", "TikTok", "Hacer"] },
        { civ: "Hacker", imp: "Pirata", hints: ["PC", "Código", "Entrar"] },
        { civ: "Blog", imp: "Foro", hints: ["Web", "Escritura", "Leer"] },
        { civ: "Clickbait", imp: "Titular", hints: ["Engaño", "Web", "Click"] },
        { civ: "Selfie", imp: "Foto", hints: ["Cara", "Cámara", "Yo"] },
        { civ: "Drive", imp: "Nube", hints: ["Google", "Archivo", "Nube"] },
        { civ: "Login", imp: "Password", hints: ["Entrar", "User", "Perfil"] },
        { civ: "Avatar", imp: "Perfil", hints: ["Imagen", "User", "Cara"] },
        { civ: "App", imp: "Software", hints: ["Icono", "Móvil", "Pantalla"] },
        { civ: "Bug", imp: "Fallo", hints: ["Error", "Software", "Fallo"] },
        { civ: "Lag", imp: "Corte", hints: ["Red", "Lento", "Internet"] },
        { civ: "Follow", imp: "Like", hints: ["Botón", "Red", "User"] },
        { civ: "Caché", imp: "Cookies", hints: ["Memoria", "Web", "Pc"] },
        { civ: "NFT", imp: "Cripto", hints: ["Token", "Arte", "Digital"] },
        { civ: "Cringe", imp: "Pena", hints: ["Sentimiento", "Gesto", "Incómodo"] },
        { civ: "Dark", imp: "Modo", hints: ["Negro", "Luz", "Pantalla"] },
        { civ: "Unboxing", imp: "Paquete", hints: ["Abrir", "YouTube", "Caja"] },
        { civ: "Webcam", imp: "Micro", hints: ["Pc", "Ojo", "Voz"] },
        { civ: "URL", imp: "Link", hints: ["Web", "Enlace", "Texto"] },
        { civ: "PIN", imp: "Huella", hints: ["Cerradura", "Número", "Acceso"] },
        { civ: "Captura", imp: "Imagen", hints: ["Pantalla", "Móvil", "Instante"] },
        { civ: "Email", imp: "Carta", hints: ["Mensaje", "Arroba", "Internet"] },
        { civ: "Sticker", imp: "Pegatina", hints: ["Cara", "Chat", "Imagen"] }
    ],
    "Cocina y Gastronomía": [
        { civ: "Sartén", imp: "Olla", hints: ["Cocina", "Mango", "Calor"] },
        { civ: "Horno", imp: "Micro", hints: ["Calor", "Hogar", "Puerta"] },
        { civ: "Chef", imp: "Pinche", hints: ["Gorro", "Delantal", "Cuchillo"] },
        { civ: "Sal", imp: "Azúcar", hints: ["Blanco", "Sabor", "Polvo"] },
        { civ: "Aceite", imp: "Manteca", hints: ["Líquido", "Grasa", "Oro"] },
        { civ: "Ajo", imp: "Cebolla", hints: ["Sabor", "Bulbo", "Olor"] },
        { civ: "Pelador", imp: "Cuchillo", hints: ["Filo", "Hoja", "Mano"] },
        { civ: "Menú", imp: "Carta", hints: ["Papel", "Precio", "Plato"] },
        { civ: "Postre", imp: "Dulce", hints: ["Azúcar", "Final", "Cuchara"] },
        { civ: "Freír", imp: "Hervir", hints: ["Agua", "Aceite", "Calor"] },
        { civ: "Batidora", imp: "Picadora", hints: ["Aspa", "Cuchilla", "Motor"] },
        { civ: "Vino", imp: "Tinto", hints: ["Uva", "Copa", "Rojo"] },
        { civ: "Especias", imp: "Hierbas", hints: ["Bote", "Aroma", "Seco"] },
        { civ: "Salsa", imp: "Crema", hints: ["Sabor", "Líquido", "Pan"] },
        { civ: "Pasta", imp: "Pizza", hints: ["Italia", "Harina", "Queso"] },
        { civ: "Carne", imp: "Pollo", hints: ["Cuchillo", "Tenedor", "Animal"] },
        { civ: "Verdura", imp: "Fruta", hints: ["Verde", "Natural", "Vitaminas"] },
        { civ: "Tarta", imp: "Pastel", hints: ["Dulce", "Vela", "Bizcocho"] },
        { civ: "Gamba", imp: "Langosta", hints: ["Antena", "Pata", "Rojo"] },
        { civ: "Sopa", imp: "Caldo", hints: ["Agua", "Bol", "Fideo"] },
        { civ: "Asado", imp: "Plancha", hints: ["Fuego", "Humos", "Metal"] },
        { civ: "Desayuno", imp: "Cena", hints: ["Leche", "Hora", "Comer"] },
        { civ: "Tapa", imp: "Bocado", hints: ["Pan", "España", "Bar"] },
        { civ: "Copa", imp: "Vaso", hints: ["Pie", "Transparente", "Beber"] },
        { civ: "Mantel", imp: "Trapo", hints: ["Tela", "Hogar", "Mesa"] },
        { civ: "Maitre", imp: "Camarero", hints: ["Vino", "Carta", "Bandeja"] },
        { civ: "Michelin", imp: "Repsol", hints: ["Guía", "Plato", "Estrella"] },
        { civ: "Buffet", imp: "Picoteo", hints: ["Bandeja", "Mesa", "Libre"] },
        { civ: "Crudo", imp: "Hecho", hints: ["Rojo", "Marrón", "Filo"] },
        { civ: "Picante", imp: "Soso", hints: ["Guindilla", "Sabor", "Boca"] },
        { civ: "Miel", imp: "Sirop", hints: ["Dulce", "Bote", "Denso"] },
        { civ: "Nata", imp: "Mousse", hints: ["Blanco", "Montar", "Suave"] },
        { civ: "Salado", imp: "Agrio", hints: ["Mar", "Boca", "Sabor"] },
        { civ: "Gourmet", imp: "Casero", hints: ["Plato", "Dinero", "Lujo"] },
        { civ: "Artesano", imp: "Fabril", hints: ["Mano", "Obra", "Pueblo"] }
    ],
    "Películas y Series": [
        { civ: "Vader", imp: "Yoda", hints: ["Fuerza", "Saga", "Espacio"] },
        { civ: "Harry", imp: "Hermione", hints: ["Varita", "Libro", "Gafas"] },
        { civ: "Berlín", imp: "Tokio", hints: ["Ciudad", "Plan", "Atraco"] },
        { civ: "Titanic", imp: "Avatar", hints: ["Agua", "Director", "Barco"] },
        { civ: "Joker", imp: "Batman", hints: ["Cara", "Capa", "Gotham"] },
        { civ: "Marvel", imp: "DC", hints: ["Héroe", "Cine", "Viñeta"] },
        { civ: "Eleven", imp: "Mike", hints: ["Niños", "Serie", "Poder"] },
        { civ: "Mafia", imp: "Padrino", hints: ["Puro", "Traje", "Familia"] },
        { civ: "Shrek", imp: "Fiona", hints: ["Pantano", "Ogros", "Burro"] },
        { civ: "Trono", imp: "Dragón", hints: ["Rey", "Fuego", "Castillo"] },
        { civ: "Simpson", imp: "Homer", hints: ["Familia", "TV", "Amarillo"] },
        { civ: "Walter", imp: "Jesse", hints: ["Plan", "Cristal", "Laboratorio"] },
        { civ: "Bond", imp: "Hunt", hints: ["Traje", "Misión", "Pistola"] },
        { civ: "Dino", imp: "Parque", hints: ["Isla", "Cola", "Colmillos"] },
        { civ: "Miedo", imp: "Susto", hints: ["Grito", "Sangre", "Sombra"] },
        { civ: "Risa", imp: "Broma", hints: ["Humor", "Final", "Gesto"] },
        { civ: "Oscar", imp: "Goya", hints: ["Figura", "Cine", "Premios"] },
        { civ: "Actor", imp: "Doble", hints: ["Cara", "Traje", "Papel"] },
        { civ: "Director", imp: "Guion", hints: ["Cámara", "Libro", "Silla"] },
        { civ: "Popcorn", imp: "Nachos", hints: ["Bolsa", "Maíz", "Comer"] },
        { civ: "Netflix", imp: "HBO", hints: ["Web", "Serie", "Suscripción"] },
        { civ: "Zombi", imp: "Vampiro", hints: ["Cuerpo", "Noche", "Miedo"] },
        { civ: "Pirata", imp: "Corsario", hints: ["Barco", "Mar", "Oro"] },
        { civ: "Gladiador", imp: "César", hints: ["Arena", "Espada", "Casco"] },
        { civ: "Rocky", imp: "Apolo", hints: ["Guantes", "Ring", "Fuerte"] },
        { civ: "Stark", imp: "Rogers", hints: ["Escudo", "Traje", "Héroe"] },
        { civ: "Sitcom", imp: "Drama", hints: ["Risa", "Guion", "Serie"] },
        { civ: "Tráiler", imp: "Teaser", hints: ["Vídeo", "Cine", "Inicio"] },
        { civ: "Doblaje", imp: "Subs", hints: ["Voz", "Letras", "Idioma"] },
        { civ: "CGI", imp: "Efecto", hints: ["Pc", "Visual", "Imagen"] },
        { civ: "Banda", imp: "BSO", hints: ["Audio", "Música", "Peli"] },
        { civ: "Sequía", imp: "Duna", hints: ["Desierto", "Arena", "Agua"] },
        { civ: "Mago", imp: "Bruja", hints: ["Varita", "Sombrero", "Capa"] },
        { civ: "Ring", imp: "Lucha", hints: ["Cuerda", "Malla", "Puño"] },
        { civ: "Butaca", imp: "Pantalla", hints: ["Sitio", "Cine", "Sala"] }
    ],
    "Música y Bandas": [
        { civ: "Beatles", imp: "Queen", hints: ["Banda", "Inglaterra", "Música"] },
        { civ: "Rock", imp: "Pop", hints: ["Sonido", "Instrumento", "Éxito"] },
        { civ: "Guitarra", imp: "Bajo", hints: ["Instrumento", "Cuerda", "Dedo"] },
        { civ: "Batería", imp: "Caja", hints: ["Baqueta", "Ritmo", "Piezas"] },
        { civ: "Piano", imp: "Órgano", hints: ["Teclas", "Instrumento", "Asiento"] },
        { civ: "Cantar", imp: "Voz", hints: ["Micro", "Vocal", "Grito"] },
        { civ: "Festival", imp: "Gira", hints: ["Evento", "Público", "Grupo"] },
        { civ: "Vinilo", imp: "CD", hints: ["Disco", "Música", "Físico"] },
        { civ: "Spotify", imp: "YouTube", hints: ["Web", "Reproductor", "Red"] },
        { civ: "DJ", imp: "Productor", hints: ["Mesa", "Cascos", "Música"] },
        { civ: "Flamenco", imp: "Copla", hints: ["Guitarra", "Voz", "Cultura"] },
        { civ: "Metal", imp: "Punk", hints: ["Sonido", "Fuerte", "Ropa"] },
        { civ: "Jazz", imp: "Blues", hints: ["Voz", "Instrumento", "Clásico"] },
        { civ: "Rap", imp: "HipHop", hints: ["Letra", "Voz", "Gesto"] },
        { civ: "Coro", imp: "Ópera", hints: ["Voz", "Público", "Teatro"] },
        { civ: "Micro", imp: "Amplificador", hints: ["Audio", "Pc", "Equipo"] },
        { civ: "Letra", imp: "Rima", hints: ["Verso", "Texto", "Poesía"] },
        { civ: "Álbum", imp: "Disco", hints: ["Foto", "Música", "Digital"] },
        { civ: "Grammy", imp: "Premio", hints: ["Gala", "Trofeo", "Cantante"] },
        { civ: "Aitana", imp: "Lola", hints: ["Música", "Joven", "Éxito"] },
        { civ: "Rosalía", imp: "Quevedo", hints: ["Voz", "Éxito", "España"] },
        { civ: "Violín", imp: "Arco", hints: ["Hilos", "Cuerda", "Caja"] },
        { civ: "Flauta", imp: "Pito", hints: ["Viento", "Agujero", "Instrumento"] },
        { civ: "Fan", imp: "Ídolo", hints: ["Seguidor", "Público", "Amor"] },
        { civ: "Baile", imp: "Danza", hints: ["Cuerpo", "Pasos", "Música"] },
        { civ: "Estudio", imp: "Ensayo", hints: ["Habitación", "Música", "Grabación"] },
        { civ: "Solo", imp: "Dúo", hints: ["Persona", "Grupo", "Micro"] },
        { civ: "Agudo", imp: "Grave", hints: ["Tono", "Voz", "Sonido"] },
        { civ: "Melodía", imp: "Acorde", hints: ["Sonido", "Dedo", "Oído"] },
        { civ: "Rapero", imp: "Trapero", hints: ["Gorra", "Voz", "Joyas"] },
        { civ: "Sinfonía", imp: "Sonata", hints: ["Papel", "Instrumento", "Obra"] },
        { civ: "Techno", imp: "House", hints: ["Pum", "Electrónica", "Baile"] },
        { civ: "Grito", imp: "Susurro", hints: ["Boca", "Voz", "Nivel"] },
        { civ: "Altavoz", imp: "Cascos", hints: ["Oído", "Caja", "Música"] },
        { civ: "Estribillo", imp: "Verso", hints: ["Letra", "Música", "Estructura"] }
    ],
    "Profesiones": [
        { civ: "Médico", imp: "Enfermera", hints: ["Blanco", "Hospital", "Dolor"] },
        { civ: "Docente", imp: "Mentor", hints: ["Pizarra", "Libro", "Alumno"] },
        { civ: "Guardia", imp: "Policía", hints: ["Uniforme", "Pistola", "Seguridad"] },
        { civ: "Bombero", imp: "Rescate", hints: ["Fuego", "Casco", "Sirena"] },
        { civ: "Chef", imp: "Camarero", hints: ["Comida", "Restaurante", "Uniforme"] },
        { civ: "Obrero", imp: "Arquitecto", hints: ["Casco", "Piedra", "Obra"] },
        { civ: "Juez", imp: "Fiscal", hints: ["Juicio", "Martillo", "Ley"] },
        { civ: "Fontanero", imp: "Tubo", hints: ["Agua", "Hogar", "Manual"] },
        { civ: "Mecánico", imp: "Motor", hints: ["Coche", "Taller", "Aceite"] },
        { civ: "Peluquero", imp: "Estilista", hints: ["Tijera", "Pelo", "Espejo"] },
        { civ: "Prensa", imp: "Radio", hints: ["Cámara", "Noticia", "Micro"] },
        { civ: "Piloto", imp: "Marinero", hints: ["Avión", "Mando", "Viaje"] },
        { civ: "Taxista", imp: "Bus", hints: ["Asiento", "Vía", "Coche"] },
        { civ: "Cajero", imp: "Venta", hints: ["Dinero", "Ticket", "Tienda"] },
        { civ: "Actor", imp: "Doble", hints: ["Cine", "Cara", "Papel"] },
        { civ: "Soldado", imp: "Fusil", hints: ["Guerra", "Casco", "Militar"] },
        { civ: "Físico", imp: "Químico", hints: ["Ciencia", "Gafas", "Materia"] },
        { civ: "Pc", imp: "Web", hints: ["Código", "Silla", "Red"] },
        { civ: "Campesino", imp: "Vaca", hints: ["Animal", "Tierra", "Sol"] },
        { civ: "Escritor", imp: "Libro", hints: ["Papel", "Mano", "Idea"] },
        { civ: "Dibujante", imp: "Diseño", hints: ["Lápiz", "Imagen", "Color"] },
        { civ: "Atleta", imp: "Deporte", hints: ["Cuerpo", "Meta", "Zapatilla"] },
        { civ: "Veterinario", imp: "Clínica", hints: ["Pelo", "Cura", "Animal"] },
        { civ: "Psicólogo", imp: "Mente", hints: ["Silla", "Sofá", "Charla"] },
        { civ: "Espacio", imp: "Luna", hints: ["Casco", "Vuelo", "Nave"] },
        { civ: "Pan", imp: "Horno", hints: ["Harina", "Blanco", "Comer"] },
        { civ: "Pintor", imp: "Pared", hints: ["Color", "Brocha", "Obra"] },
        { civ: "Jardín", imp: "Planta", hints: ["Verde", "Tierra", "Tijera"] },
        { civ: "Diputado", imp: "Alcalde", hints: ["Político", "Voto", "Voto"] },
        { civ: "Banca", imp: "Bolsa", hints: ["Euros", "Pc", "Banco"] },
        { civ: "Circo", imp: "Mago", hints: ["Niño", "Mago", "Carpa"] },
        { civ: "Moda", imp: "Modelo", hints: ["Ropa", "Foto", "Cara"] },
        { civ: "Turista", imp: "Hotel", hints: ["Maleta", "Foto", "Guía"] },
        { civ: "Fósil", imp: "Tierra", hints: ["Piedra", "Pasado", "Mano"] },
        { civ: "Trompeta", imp: "Voz", hints: ["Audio", "Instrumento", "Soplar"] }
    ],
    "Escuela y Educación": [
        { civ: "Examen", imp: "Nota", hints: ["Papel", "Estudio", "Número"] },
        { civ: "Tarea", imp: "Libro", hints: ["Casa", "Hoja", "Mochila"] },
        { civ: "Patio", imp: "Juego", hints: ["Niño", "Recreo", "Pelota"] },
        { civ: "Mochila", imp: "Libreta", hints: ["Mesa", "Escuela", "Papel"] },
        { civ: "Bolígrafo", imp: "Lápiz", hints: ["Escribir", "Tinta", "Mano"] },
        { civ: "Goma", imp: "Papel", hints: ["Borrar", "Fallo", "Gesto"] },
        { civ: "Pizarra", imp: "Tiza", hints: ["Clase", "Verde", "Blanco"] },
        { civ: "Director", imp: "Profe", hints: ["Escuela", "Silla", "Cargo"] },
        { civ: "Alumno", imp: "Clase", hints: ["Niño", "Mesa", "Estudiar"] },
        { civ: "Lección", imp: "Tema", hints: ["Hoja", "Hablar", "Saber"] },
        { civ: "Sumas", imp: "Letras", hints: ["Papel", "Materia", "Pc"] },
        { civ: "Guerra", imp: "Mapa", hints: ["Historia", "Papel", "Lugar"] },
        { civ: "Átomo", imp: "Cuerpo", hints: ["Ciencia", "Pc", "Micro"] },
        { civ: "Inglés", imp: "Verbo", hints: ["Hablar", "Libro", "Cultura"] },
        { civ: "Gimnasio", imp: "Pelota", hints: ["Deporte", "Cuerpo", "Sudor"] },
        { civ: "Suspenso", imp: "Aprobar", hints: ["Nota", "Número", "Rojo"] },
        { civ: "Uni", imp: "Insti", hints: ["Lugar", "Centro", "Libro"] },
        { civ: "Pupitre", imp: "Silla", hints: ["Madera", "Mueble", "Mesa"] },
        { civ: "Regla", imp: "Escuadra", hints: ["Línea", "Medir", "Plástico"] },
        { civ: "Danza", imp: "Coro", hints: ["Arte", "Voz", "Cuerpo"] },
        { civ: "Beca", imp: "Dinero", hints: ["Papel", "Ayuda", "Saber"] },
        { civ: "Tesis", imp: "Grado", hints: ["Final", "Libro", "Cargo"] },
        { civ: "Fuera", imp: "Viaje", hints: ["Lugar", "Salida", "Excursión"] },
        { civ: "Típex", imp: "Boli", hints: ["Error", "Blanco", "Escribir"] },
        { civ: "Carpeta", imp: "Folio", hints: ["Hojas", "Guardar", "Plástico"] },
        { civ: "Cuentas", imp: "Números", hints: ["Calculadora", "Mente", "Papel"] },
        { civ: "Aula", imp: "Laboratorio", hints: ["Habitación", "Mesa", "Sitio"] },
        { civ: "Protesta", imp: "Paro", hints: ["Calle", "Grito", "Grupo"] },
        { civ: "Faltas", imp: "Aviso", hints: ["Anotar", "Error", "Nota"] },
        { civ: "Globo", imp: "Mapa", hints: ["Mundo", "Redondo", "Países"] },
        { civ: "Pincel", imp: "Témpera", hints: ["Color", "Agua", "Mano"] },
        { civ: "Agenda", imp: "Móvil", hints: ["Notas", "Fechas", "Mano"] },
        { civ: "Flauta", imp: "Pentagrama", hints: ["Viento", "Agujeros", "Audio"] },
        { civ: "Comedor", imp: "Bandeja", hints: ["Plato", "Comida", "Mesa"] },
        { civ: "Becario", imp: "Prácticas", hints: ["Trabajo", "Joven", "Ayuda"] }
    ],
    "Ciencia y Tecnología": [
        { civ: "Red", imp: "Wifi", hints: ["Internet", "Invisible", "Wifi"] },
        { civ: "Pc", imp: "Ratón", hints: ["Pantalla", "Mesa", "Mano"] },
        { civ: "Móvil", imp: "Micro", hints: ["Audio", "Voz", "Mano"] },
        { civ: "Robot", imp: "Cable", hints: ["Hierro", "Luz", "Máquina"] },
        { civ: "Marte", imp: "Sol", hints: ["Espacio", "Luz", "Planeta"] },
        { civ: "Gen", imp: "Virus", hints: ["Vida", "Micro", "Medicina"] },
        { civ: "Átomo", imp: "Luz", hints: ["Materia", "Energía", "Invisible"] },
        { civ: "Bata", imp: "Tubo", hints: ["Cristal", "Laboratorio", "Ciencia"] },
        { civ: "NASA", imp: "ESA", hints: ["Espacio", "Cohete", "Cielo"] },
        { civ: "Software", imp: "Web", hints: ["Pc", "Web", "Pantalla"] },
        { civ: "Telescopio", imp: "Lupa", hints: ["Ver", "Lente", "Cristal"] },
        { civ: "Sonda", imp: "Cohete", hints: ["Vuelo", "Metal", "Lejos"] },
        { civ: "Luz", imp: "Pila", hints: ["Brillo", "Energía", "Bote"] },
        { civ: "Rayo", imp: "Láser", hints: ["Línea", "Luz", "Punto"] },
        { civ: "Placa", imp: "Panel", hints: ["Sol", "Azul", "Energía"] },
        { civ: "Cero", imp: "Uno", hints: ["Dato", "Binario", "Pc"] },
        { civ: "Vibración", imp: "Onda", hints: ["Movimiento", "Aire", "Oído"] },
        { civ: "Química", imp: "Mezcla", hints: ["Líquido", "Tubo", "Sabor"] },
        { civ: "Cura", imp: "Dosis", hints: ["Líquido", "Vaso", "Brazo"] },
        { civ: "Mono", imp: "Fósil", hints: ["Pasado", "Tierra", "Hueso"] },
        { civ: "Dron", imp: "Hélice", hints: ["Vuelo", "Cámara", "Motor"] },
        { civ: "IA", imp: "Bot", hints: ["Mente", "Chat", "Código"] },
        { civ: "Dato", imp: "Bit", hints: ["Número", "Pc", "Memoria"] },
        { civ: "Led", imp: "Monitor", hints: ["Luz", "Color", "Pantalla"] },
        { civ: "Teclas", imp: "Clic", hints: ["Mano", "Ruido", "Escribir"] },
        { civ: "Tinta", imp: "Papel", hints: ["Color", "Línea", "Impresión"] },
        { civ: "Muela", imp: "Implante", hints: ["Boca", "Duro", "Metal"] },
        { civ: "Gafas", imp: "Casco", hints: ["Ojos", "Cabeza", "Juego"] },
        { civ: "Bio", imp: "Nano", hints: ["Ciencia", "Futuro", "Pequeño"] },
        { civ: "Cable", imp: "Luz", hints: ["Hebra", "Internet", "Velocidad"] },
        { civ: "Apps", imp: "Play", hints: ["Tienda", "Móvil", "Iconos"] },
        { civ: "Apple", imp: "Java", hints: ["Sistemas", "Logo", "Web"] },
        { civ: "Nube", imp: "Disco", hints: ["Almacén", "Dato", "Aire"] },
        { civ: "Hack", imp: "Virus", hints: ["Ataque", "Pc", "Código"] },
        { civ: "Satélite", imp: "Antena", hints: ["Onda", "Espacio", "TV"] }
    ],
    "Deportes": [
        { civ: "Fútbol", imp: "Gol", hints: ["Césped", "Pelota", "Campo"] },
        { civ: "Basket", imp: "Aro", hints: ["Cancha", "Balón", "Alto"] },
        { civ: "Tenis", imp: "Red", hints: ["Raqueta", "Pista", "Amarillo"] },
        { civ: "Bici", imp: "Rueda", hints: ["Casco", "Ruta", "Pedal"] },
        { civ: "Coche", imp: "F1", hints: ["Motor", "Circuito", "Casco"] },
        { civ: "Mar", imp: "Cloro", hints: ["Gafas", "Piscina", "Agua"] },
        { civ: "Salto", imp: "Valla", hints: ["Atletismo", "Correr", "Pies"] },
        { civ: "Ring", imp: "Guante", hints: ["Golpe", "Puño", "Cuerda"] },
        { civ: "Hoyo", imp: "Palo", hints: ["Hierba", "Bola", "Andar"] },
        { civ: "Nieve", imp: "Esquí", hints: ["Frío", "Gafas", "Montaña"] },
        { civ: "Tabla", imp: "Olas", hints: ["Mar", "Equilibrio", "Agua"] },
        { civ: "Malla", imp: "Estera", hints: ["Cuerpo", "Suelo", "Zen"] },
        { civ: "Red", imp: "Arena", hints: ["Playa", "Salto", "Malla"] },
        { civ: "Melé", imp: "Placaje", hints: ["Fuerza", "Césped", "Grupo"] },
        { civ: "Jaque", imp: "Ficha", hints: ["Mesa", "Mente", "Madera"] },
        { civ: "Mesa", imp: "Pala", hints: ["Pelota", "Pequeño", "Red"] },
        { civ: "Arnés", imp: "Roca", hints: ["Altura", "Monte", "Cuerda"] },
        { civ: "Puck", imp: "Stick", hints: ["Hielo", "Golpe", "Casco"] },
        { civ: "Piragua", imp: "Remo", hints: ["Agua", "Río", "Barca"] },
        { civ: "Diana", imp: "Arco", hints: ["Puntería", "Centro", "Madera"] },
        { civ: "Taco", imp: "Bola", hints: ["Mesa", "Bar", "Verde"] },
        { civ: "Silla", imp: "Casco", hints: ["Animal", "Rienda", "Campo"] },
        { civ: "Cinto", imp: "Tatami", hints: ["Lucha", "Traje", "Color"] },
        { civ: "Músculo", imp: "Pesas", hints: ["Fuerza", "Hierro", "Esfuerzo"] },
        { civ: "Coreo", imp: "Ritmo", hints: ["Cuerpo", "Música", "Pista"] },
        { civ: "Meta", imp: "Podio", hints: ["Final", "Carrera", "Trofeo"] },
        { civ: "Pelota", imp: "Balón", hints: ["Esfera", "Aire", "Redonda"] },
        { civ: "Grada", imp: "Cancha", hints: ["Lugar", "Público", "Asiento"] },
        { civ: "Silbato", imp: "Falta", hints: ["Árbitro", "Boca", "Regla"] },
        { civ: "Oro", imp: "Copa", hints: ["Victoria", "Brillo", "Final"] },
        { civ: "Antorcha", imp: "Aros", hints: ["Evento", "Fuego", "Mundo"] },
        { civ: "Pala", imp: "Raqueta", hints: ["Mango", "Malla", "Mano"] },
        { civ: "Malla", imp: "Casco", hints: ["Ropa", "Metal", "Protección"] },
        { civ: "Viento", imp: "Vela", hints: ["Barco", "Mar", "Soplar"] },
        { civ: "Sudor", imp: "Ducha", hints: ["Agua", "Calor", "Ejercicio"] }
    ],
    "Superhéroes": [
        { civ: "Batman", imp: "Robin", hints: ["Capa", "Gotham", "Murciélago"] },
        { civ: "Superman", imp: "Volar", hints: ["Rojo", "Capa", "Símbolo"] },
        { civ: "Araña", imp: "Rojo", hints: ["Red", "Muro", "Ojos"] },
        { civ: "Hierro", imp: "Robot", hints: ["Metal", "Vuelo", "Luz"] },
        { civ: "Verde", imp: "Furia", hints: ["Fuerza", "Roto", "Músculo"] },
        { civ: "Trueno", imp: "Dios", hints: ["Martillo", "Capa", "Pelo"] },
        { civ: "Mujer", imp: "Lazo", hints: ["Escudo", "Fuerte", "Estrella"] },
        { civ: "Correr", imp: "Veloz", hints: ["Rayo", "Rojo", "Flash"] },
        { civ: "Garras", imp: "Lobo", hints: ["Metal", "Peludo", "X"] },
        { civ: "Escudo", imp: "Bandera", hints: ["Azul", "Estrella", "Capitán"] },
        { civ: "Arco", imp: "Viuda", hints: ["Flecha", "Equipo", "Vengador"] },
        { civ: "Magia", imp: "Capa", hints: ["Mano", "Ojo", "Misterio"] },
        { civ: "Pez", imp: "Agua", hints: ["Mar", "Tridente", "Reino"] },
        { civ: "Pantera", imp: "Gato", hints: ["Selva", "Ropa", "África"] },
        { civ: "Grupo", imp: "Mutante", hints: ["Poder", "Escuela", "Letra"] },
        { civ: "Ciego", imp: "Rojo", hints: ["Abogado", "Mano", "Justicia"] },
        { civ: "Anillo", imp: "Verde", hints: ["Luz", "Vuelo", "Poder"] },
        { civ: "Máscara", imp: "Capa", hints: ["Disfraz", "Oculto", "Héroe"] },
        { civ: "Villano", imp: "Malo", hints: ["Miedo", "Plan", "Pelea"] },
        { civ: "Ciudad", imp: "Pueblo", hints: ["Calle", "Ayuda", "Techo"] },
        { civ: "Chiste", imp: "Risa", hints: ["Cara", "Pelo", "Risa"] },
        { civ: "Gema", imp: "Guante", hints: ["Poder", "Mano", "Color"] },
        { civ: "Piedra", imp: "Roca", hints: ["Duro", "Tierra", "Mano"] },
        { civ: "Disfraz", imp: "Malla", hints: ["Ropa", "Héroe", "Apretado"] },
        { civ: "Viñeta", imp: "Papel", hints: ["Dibujo", "Letra", "Papel"] },
        { civ: "Mundo", imp: "Tierra", hints: ["Mapa", "Gente", "Vida"] },
        { civ: "Oculto", imp: "Secreto", hints: ["Gafas", "Cara", "Trabajo"] },
        { civ: "Coche", imp: "Nave", hints: ["Vía", "Coche", "Viaje"] },
        { civ: "Rayo", imp: "Vuelo", hints: ["Niño", "Grito", "Fuerza"] },
        { civ: "Infierno", imp: "Cielo", hints: ["Rojo", "Cuernos", "Miedo"] },
        { civ: "Gata", imp: "Látigo", hints: ["Ladrón", "Noche", "Cara"] },
        { civ: "Mapache", imp: "Árbol", hints: ["Nave", "Grupo", "Hablar"] },
        { civ: "Imán", imp: "Metal", hints: ["Fuerza", "Casco", "Mover"] },
        { civ: "Casco", imp: "Vuelo", hints: ["Ojos", "Voz", "Robot"] },
        { civ: "Héroe", imp: "Capitán", hints: ["Líder", "Ayuda", "Símbolo"] }
    ],
    "Transporte": [
        { civ: "Coche", imp: "Bus", hints: ["Rueda", "Vía", "Puerta"] },
        { civ: "Moto", imp: "Bici", hints: ["Casco", "Rueda", "Manillar"] },
        { civ: "Tren", imp: "Vía", hints: ["Hierro", "Pasajero", "Estación"] },
        { civ: "Avión", imp: "Vuelo", hints: ["Ala", "Cielo", "Nube"] },
        { civ: "Barco", imp: "Vela", hints: ["Mar", "Agua", "Viento"] },
        { civ: "AVE", imp: "Metro", hints: ["Tren", "Vía", "Rápido"] },
        { civ: "Uber", imp: "Taxi", hints: ["Coche", "Móvil", "Pago"] },
        { civ: "Patín", imp: "Skate", hints: ["Rueda", "Calle", "Pies"] },
        { civ: "Grúa", imp: "Trailer", hints: ["Coche", "Camión", "Gancho"] },
        { civ: "Helicóptero", imp: "Ala", hints: ["Hélice", "Vuelo", "Aire"] },
        { civ: "Yate", imp: "Canoa", hints: ["Barca", "Agua", "Lujo"] },
        { civ: "Globo", imp: "Cesta", hints: ["Vuelo", "Aire", "Cielo"] },
        { civ: "Ambulancia", imp: "Sirena", hints: ["Hospital", "Coche", "Ruido"] },
        { civ: "Fúnebre", imp: "Negro", hints: ["Coche", "Triste", "Lento"] },
        { civ: "Tractor", imp: "Arado", hints: ["Campo", "Tierra", "Motor"] },
        { civ: "Parada", imp: "Andén", hints: ["Esperar", "Gente", "Vía"] },
        { civ: "Puerto", imp: "Aduana", hints: ["Mar", "Viaje", "Control"] },
        { civ: "Billete", imp: "Abono", hints: ["Papel", "Pago", "Viaje"] },
        { civ: "Súper", imp: "Gasoil", hints: ["Líquido", "Motor", "Gasolinera"] },
        { civ: "Freno", imp: "Embrague", hints: ["Pie", "Parar", "Pedal"] },
        { civ: "Volante", imp: "Pomo", hints: ["Mano", "Girar", "Conducir"] },
        { civ: "Atasco", imp: "Cola", hints: ["Calle", "Mucho", "Coche"] },
        { civ: "Chofer", imp: "Piloto", hints: ["Conducir", "Traje", "Persona"] },
        { civ: "Polizón", imp: "Maleta", hints: ["Oculto", "Barco", "Viajero"] },
        { civ: "Multa", imp: "Radar", hints: ["Dinero", "Papel", "Policía"] },
        { civ: "Luz", imp: "Señal", hints: ["Color", "Vía", "Control"] },
        { civ: "Vía", imp: "Acera", hints: ["Vía", "Hierro", "Suelo"] },
        { civ: "Muro", imp: "Valla", hints: ["Paso", "Cerca", "Separar"] },
        { civ: "Paso", imp: "Cruce", hints: ["Calle", "Vía", "Pintura"] },
        { civ: "Túnel", imp: "Puente", hints: ["Oscuro", "Paso", "Estructura"] },
        { civ: "Escala", imp: "Maleta", hints: ["Aeropuerto", "Vuelo", "Esperar"] },
        { civ: "Ancla", imp: "Muelle", hints: ["Barco", "Hierro", "Agua"] },
        { civ: "Gas", imp: "Freno", hints: ["Pedal", "Mover", "Coche"] },
        { civ: "Airbag", imp: "Cinto", hints: ["Seguro", "Choque", "Coche"] },
        { civ: "Mapa", imp: "GPS", hints: ["Ruta", "Lugar", "Pantalla"] }
    ],
    "Videojuegos": [
        { civ: "Mario", imp: "Luigi", hints: ["Gorra", "Salto", "Mando"] },
        { civ: "Zelda", imp: "Link", hints: ["Espada", "Escudo", "Aventura"] },
        { civ: "Pika", imp: "Ash", hints: ["Bola", "Animal", "Móvil"] },
        { civ: "Minecraft", imp: "Cubo", hints: ["Bloque", "Pico", "Tierra"] },
        { civ: "Fortnite", imp: "Baile", hints: ["Mapa", "Disparo", "Isla"] },
        { civ: "FIFA", imp: "Pelota", hints: ["Fútbol", "Consola", "Mando"] },
        { civ: "Mando", imp: "Tecla", hints: ["Jugar", "Mano", "Botón"] },
        { civ: "Skin", imp: "Disfraz", hints: ["Ropa", "Pagar", "Cara"] },
        { civ: "Xbox", imp: "Play", hints: ["Consola", "Tv", "Logo"] },
        { civ: "Game", imp: "Over", hints: ["Final", "Texto", "Perder"] },
        { civ: "Nivel", imp: "Misión", hints: ["Mapa", "Punto", "Mando"] },
        { civ: "Jefe", imp: "Malo", hints: ["Final", "Duro", "Gande"] },
        { civ: "Botón", imp: "Stick", hints: ["Mano", "Dedo", "Mando"] },
        { civ: "Pc", imp: "Monitor", hints: ["Mesa", "Mando", "Tecla"] },
        { civ: "Tetris", imp: "Línea", hints: ["Pieza", "Música", "Puntitos"] },
        { civ: "Sonic", imp: "Azul", hints: ["Animal", "Rápido", "Anillo"] },
        { civ: "Halo", imp: "Soldado", hints: ["Casco", "Muro", "Disparo"] },
        { civ: "Arcade", imp: "Salón", hints: ["Lugar", "Ficha", "Botón"] },
        { civ: "Gamer", imp: "Pro", hints: ["Persona", "Silla", "Mando"] },
        { civ: "Lag", imp: "Ping", hints: ["Red", "Internet", "Lento"] },
        { civ: "Steam", imp: "Epic", hints: ["Web", "Pc", "Tienda"] },
        { civ: "Retro", imp: "Viejo", hints: ["Pixel", "Tv", "Música"] },
        { civ: "Sims", imp: "Casa", hints: ["Vida", "Familia", "Diamante"] },
        { civ: "Roblox", imp: "Bloque", hints: ["Pc", "Niños", "Mundo"] },
        { civ: "Craft", imp: "Mina", hints: ["Tierra", "Pico", "Hierro"] },
        { civ: "Wii", imp: "Switch", hints: ["Mando", "Mover", "Nintendo"] },
        { civ: "Vida", imp: "Corazón", hints: ["Rojo", "Salud", "Barra"] },
        { civ: "Susto", imp: "Miedo", hints: ["Noche", "Zombi", "Pantalla"] },
        { civ: "Mundo", imp: "Mapa", hints: ["Abierto", "Lugar", "Libre"] },
        { civ: "Speed", imp: "Rápido", hints: ["Meta", "Tiempo", "Reloj"] },
        { civ: "Combo", imp: "Golpe", hints: ["Botón", "Mucho", "Lucha"] },
        { civ: "Mana", imp: "Hechizo", hints: ["Azul", "Magia", "Barra"] },
        { civ: "Skin", imp: "Mod", hints: ["Cambio", "Pc", "Archivo"] },
        { civ: "Noob", imp: "Manco", hints: ["Jugador", "Malo", "Novato"] },
        { civ: "Quest", imp: "Exp", hints: ["Rol", "Mapa", "Tarea"] }
    ],
    "Clima y Naturaleza": [
        { civ: "Lluvia", imp: "Agua", hints: ["Nube", "Cielo", "Mojado"] },
        { civ: "Nieve", imp: "Frío", hints: ["Blanco", "Invierno", "Nube"] },
        { civ: "Sol", imp: "Luz", hints: ["Calor", "Verano", "Amarillo"] },
        { civ: "Nube", imp: "Gris", hints: ["Cielo", "Viento", "Gris"] },
        { civ: "Trueno", imp: "Rayo", hints: ["Ruido", "Luz", "Cielo"] },
        { civ: "Monte", imp: "Pico", hints: ["Roca", "Tierra", "Alto"] },
        { civ: "Río", imp: "Mar", hints: ["Agua", "Mojado", "Mapa"] },
        { civ: "Bosque", imp: "Pino", hints: ["Árbol", "Verde", "Tierra"] },
        { civ: "Selva", imp: "Liana", hints: ["Húmedo", "Animal", "Verde"] },
        { civ: "Arena", imp: "Duna", hints: ["Seco", "Calor", "Tierra"] },
        { civ: "Flor", imp: "Hoja", hints: ["Planta", "Color", "Jardín"] },
        { civ: "Fuego", imp: "Lava", hints: ["Quemar", "Rojo", "Calor"] },
        { civ: "Hielo", imp: "Polo", hints: ["Frío", "Cristal", "Blanco"] },
        { civ: "Isla", imp: "Playa", hints: ["Arena", "Rodeado", "Mar"] },
        { civ: "Cueva", imp: "Oso", hints: ["Oscuro", "Bajo", "Piedra"] },
        { civ: "Viento", imp: "Aire", hints: ["Soplo", "Árbol", "Frío"] },
        { civ: "Niebla", imp: "Nube", hints: ["Gris", "Vaso", "Ojos"] },
        { civ: "Otoño", imp: "Hoja", hints: ["Tiempo", "Suelo", "Árbol"] },
        { civ: "Verano", imp: "Calor", hints: ["Playa", "Sol", "Sudor"] },
        { civ: "Hierba", imp: "Prado", hints: ["Verde", "Tierra", "Animal"] },
        { civ: "Plástico", imp: "Humo", hints: ["Malo", "Mundo", "Aire"] },
        { civ: "Tierra", imp: "Barro", hints: ["Marrón", "Suelo", "Pala"] },
        { civ: "Animal", imp: "Bicho", hints: ["Vida", "Ojos", "Patas"] },
        { civ: "Piedra", imp: "Guijarro", hints: ["Duro", "Tierra", "Mano"] },
        { civ: "Arco", imp: "Iris", hints: ["Cielo", "Color", "Lluvia"] },
        { civ: "Luna", imp: "Noche", hints: ["Cielo", "Luz", "Blanco"] },
        { civ: "Día", imp: "Noche", hints: ["Tiempo", "Luz", "Hora"] },
        { civ: "Ola", imp: "Surf", hints: ["Mar", "Agua", "Mover"] },
        { civ: "Rayo", imp: "Chispa", hints: ["Luz", "Brillo", "Electricidad"] },
        { civ: "Clima", imp: "Mapa", hints: ["Tiempo", "Tele", "Sol"] },
        { civ: "Ecología", imp: "Bio", hints: ["Mundo", "Verde", "Cuidado"] },
        { civ: "Volcán", imp: "Fuego", hints: ["Monte", "Humo", "Piedra"] },
        { civ: "Humedad", imp: "Agua", hints: ["Aire", "Mojado", "Gesto"] },
        { civ: "Huracán", imp: "Giro", hints: ["Viento", "Miedo", "Giro"] },
        { civ: "Tornado", imp: "Embudo", hints: ["Aire", "Giro", "Cielo"] }
    ],
    "Series de Éxito": [
        { civ: "La Casa de Papel", imp: "Vis a Vis", hints: ["Netflix", "Prisión", "España"] },
        { civ: "Stranger Things", imp: "Dark", hints: ["Niños", "Misterio", "Años 80"] },
        { civ: "Juego de Tronos", imp: "The Witcher", hints: ["Fantasía", "Dragones", "Espadas"] },
        { civ: "Breaking Bad", imp: "Narcos", hints: ["Drogas", "Química", "Crimen"] },
        { civ: "Élite", imp: "Rebelde", hints: ["Instituto", "Ricos", "Drama"] }
    ],
    "Dibujos Animados Retro": [
        { civ: "Oliver y Benji", imp: "Campeones", hints: ["Fútbol", "Infancia", "Campo Infinito"] },
        { civ: "Dragon Ball", imp: "Caballeros del Zodiaco", hints: ["Lucha", "Anime", "Bolas"] },
        { civ: "Doraemon", imp: "Shin Chan", hints: ["Japón", "Niño", "Inventos"] },
        { civ: "Pokémon", imp: "Digimon", hints: ["Monstruos", "Evolución", "Colección"] },
        { civ: "Los Simpsons", imp: "Padre de Familia", hints: ["Amarillo", "Comedia", "Padre"] }
    ],
    "Iconos del Pop": [
        { civ: "Rosalía", imp: "C. Tangana", hints: ["Música", "Grammy", "Motomami"] },
        { civ: "Aitana", imp: "Lola Índigo", hints: ["Operación Triunfo", "Pop", "Cantante"] },
        { civ: "Bad Gyal", imp: "Karol G", hints: ["Urbano", "Baile", "Autotune"] },
        { civ: "Shakira", imp: "Jennifer Lopez", hints: ["Latina", "Baile", "Mundial"] },
        { civ: "Harry Styles", imp: "Justin Bieber", hints: ["Ídolo", "Pop", "Moda"] }
    ],
    "Cine de Terror": [
        { civ: "Drácula", imp: "Nosferatu", hints: ["Vampiro", "Noche", "Colmillos"] },
        { civ: "It", imp: "Annabelle", hints: ["Payaso", "Miedo", "Muñeca"] },
        { civ: "El Exorcista", imp: "Poltergeist", hints: ["Posesión", "Cama", "Grito"] },
        { civ: "Scream", imp: "Halloween", hints: ["Máscara", "Cuchillo", "Slasher"] },
        { civ: "Alien", imp: "Predator", hints: ["Espacio", "Monstruo", "Miedo"] }
    ],
    "Mundo Gamer": [
        { civ: "Minecraft", imp: "Roblox", hints: ["Cubos", "Online", "Construcción"] },
        { civ: "Fortnite", imp: "Apex Legends", hints: ["Battle Royale", "Disparos", "Mapa"] },
        { civ: "League of Legends", imp: "Dota 2", hints: ["PC", "Estrategia", "Torreta"] },
        { civ: "Super Mario", imp: "Sonic", hints: ["Plataformas", "Salto", "Clásico"] },
        { civ: "Zelda", imp: "Elden Ring", hints: ["Aventura", "Espada", "Mundo Abierto"] }
    ],
    "Universo Marvel/DC": [
        { civ: "Iron Man", imp: "Batman", hints: ["Millonario", "Héroe", "Tecnología"] },
        { civ: "Spider-Man", imp: "Deadpool", hints: ["Máscara", "Rojo", "Salto"] },
        { civ: "Thor", imp: "Superman", hints: ["Capa", "Volar", "Fuerza"] },
        { civ: "Vengadores", imp: "Liga de la Justicia", hints: ["Equipo", "Cine", "Héroes"] },
        { civ: "Joker", imp: "Thanos", hints: ["Villano", "Malo", "Caos"] }
    ],
    "Gastronomía Regional": [
        { civ: "Cocido Madrileño", imp: "Fabada Asturiana", hints: ["Legumbres", "Plato", "Cuchara"] },
        { civ: "Salmorejo", imp: "Gazpacho", hints: ["Tomate", "Frío", "Andalucía"] },
        { civ: "Pulpo a la Gallega", imp: "Calamares", hints: ["Marisco", "Plato", "Aceite"] },
        { civ: "Ensaimada", imp: "Sobrasada", hints: ["Baleares", "Comida", "Isla"] },
        { civ: "Pintxo", imp: "Tapa", hints: ["Bar", "Pequeño", "Palillo"] }
    ],
    "Monumentos Nacionales": [
        { civ: "La Alhambra", imp: "La Mezquita", hints: ["Andalucía", "Historia", "Arquitectura"] },
        { civ: "Sagrada Familia", imp: "Catedral de Burgos", hints: ["Iglesia", "Piedra", "Turismo"] },
        { civ: "Acueducto de Segovia", imp: "Muralla de Ávila", hints: ["Piedra", "Castilla", "Antiguo"] },
        { civ: "Teatro de Mérida", imp: "Itálica", hints: ["Roma", "Ruinas", "Cultura"] },
        { civ: "Guggenheim", imp: "Ciudad de las Ciencias", hints: ["Moderno", "Museo", "Metal"] }
    ],
    "Fiestas Populares": [
        { civ: "San Fermín", imp: "Fallas", hints: ["Multitud", "Tradición", "Evento"] },
        { civ: "Semana Santa", imp: "Romería", hints: ["Religión", "Paso", "Calle"] },
        { civ: "Carnaval", imp: "Orgullo", hints: ["Disfraz", "Música", "Fiesta"] },
        { civ: "Tomatina", imp: "Batalla del Vino", hints: ["Comida", "Mancha", "Pueblo"] },
        { civ: "Feria de Abril", imp: "El Rocío", hints: ["Sevilla", "Caballo", "Baile"] }
    ],
    "Islas del Archipiélago": [
        { civ: "Ibiza", imp: "Mallorca", hints: ["Baleares", "Mar", "Fiesta"] },
        { civ: "Tenerife", imp: "Gran Canaria", hints: ["Canarias", "Volcán", "Sol"] },
        { civ: "Formentera", imp: "Menorca", hints: ["Cala", "Tranquilo", "Agua Turquesa"] },
        { civ: "Lanzarote", imp: "Fuerteventura", hints: ["Viento", "Arena", "Canarias"] },
        { civ: "La Gomera", imp: "El Hierro", hints: ["Pequeña", "Isla", "Naturaleza"] }
    ],
    "Supermercados Locales": [
        { civ: "Mercadona", imp: "Carrefour", hints: ["Compra", "Comida", "Hacendado"] },
        { civ: "Lidl", imp: "Aldi", hints: ["Alemán", "Barato", "Oferta"] },
        { civ: "Dia", imp: "Alcampo", hints: ["Barrio", "Supermercado", "Tienda"] },
        { civ: "El Corte Inglés", imp: "Fnac", hints: ["Centro", "Ropa", "Caro"] },
        { civ: "Bershka", imp: "Zara", hints: ["Ropa", "Tienda", "Inditex"] }
    ],
    "Cuerpo Humano (Órganos)": [
        { civ: "Hígado", imp: "Páncreas", hints: ["Interior", "Vital", "Filtro"] },
        { civ: "Pulmones", imp: "Corazón", hints: ["Pecho", "Aire", "Vida"] },
        { civ: "Cerebro", imp: "Médula", hints: ["Cabeza", "Pensar", "Nervios"] },
        { civ: "Riñones", imp: "Vejiga", hints: ["Agua", "Filtro", "Cuerpo"] },
        { civ: "Estómago", imp: "Intestino", hints: ["Comida", "Digestión", "Vientre"] }
    ],
    "Astronomía": [
        { civ: "Agujero Negro", imp: "Supernova", hints: ["Espacio", "Gravedad", "Muerte Estelar"] },
        { civ: "Marte", imp: "Júpiter", hints: ["Planeta", "Rojo", "Sistema Solar"] },
        { civ: "Vía Láctea", imp: "Andrómeda", hints: ["Galaxia", "Estrellas", "Espacio"] },
        { civ: "Cometa", imp: "Asteroide", hints: ["Cielo", "Roca", "Velocidad"] },
        { civ: "Telescopio", imp: "Satélite", hints: ["Ver", "Lente", "Espacio"] }
    ],
    "Elementos Químicos": [
        { civ: "Oro", imp: "Plata", hints: ["Metal", "Joyas", "Valor"] },
        { civ: "Hierro", imp: "Cobre", hints: ["Metal", "Duro", "Herramienta"] },
        { civ: "Oxígeno", imp: "Hidrógeno", hints: ["Gas", "Aire", "Invisible"] },
        { civ: "Mercurio", imp: "Plomo", hints: ["Tóxico", "Metal", "Pesado"] },
        { civ: "Carbono", imp: "Diamante", hints: ["Materia", "Vida", "Negro"] }
    ],
    "Clima Extremo": [
        { civ: "Tsunami", imp: "Marejada", hints: ["Agua", "Peligro", "Ola"] },
        { civ: "Huracán", imp: "Tornado", hints: ["Viento", "Giro", "Tormenta"] },
        { civ: "Sequía", imp: "Ola de Calor", hints: ["Sol", "Sed", "Tierra Seca"] },
        { civ: "Nevada", imp: "Ventisca", hints: ["Frío", "Blanco", "Invierno"] },
        { civ: "Inundación", imp: "Riada", hints: ["Lluvia", "Agua", "Calle"] }
    ],
    "Tecnología del Mañana": [
        { civ: "Coche Volador", imp: "Dron de Pasajeros", hints: ["Futuro", "Volar", "Cielo"] },
        { civ: "Teletransporte", imp: "Viaje en el Tiempo", hints: ["Ciencia Ficción", "Movimiento", "Imposible"] },
        { civ: "IA Sentiente", imp: "Cyborg", hints: ["Mente", "Robot", "Futuro"] },
        { civ: "Base en Marte", imp: "Estación Lunar", hints: ["Espacio", "Vivir", "Planeta"] },
        { civ: "Realidad Inmersiva", imp: "Metaverso", hints: ["Gafas", "Mundo", "Virtual"] }
    ],
    "Herramientas de Bricolaje": [
        { civ: "Taladro", imp: "Atornillador", hints: ["Taller", "Mano", "Agujero"] },
        { civ: "Sierra", imp: "Radial", hints: ["Corte", "Dientes", "Metal"] },
        { civ: "Martillo", imp: "Maza", hints: ["Golpe", "Clavo", "Fuerza"] },
        { civ: "Lijadora", imp: "Cepillo", hints: ["Madera", "Suave", "Polvo"] },
        { civ: "Llave Inglesa", imp: "Alicates", hints: ["Tuerca", "Metal", "Apretar"] }
    ],
    "Oficios en Extinción": [
        { civ: "Afilador", imp: "Paragüero", hints: ["Tradición", "Calle", "Flauta"] },
        { civ: "Carbonero", imp: "Leñador", hints: ["Fuego", "Antiguo", "Negro"] },
        { civ: "Relojero", imp: "Zapatero", hints: ["Arreglo", "Mano", "Taller"] },
        { civ: "Sereno", imp: "Pregonero", hints: ["Noche", "Voz", "Pueblo"] },
        { civ: "Molinero", imp: "Herrero", hints: ["Harina", "Piedra", "Viento"] }
    ],
    "Instrumentos de Cuerda": [
        { civ: "Ukelele", imp: "Guitarra", hints: ["Música", "Cuerdas", "Pequeño"] },
        { civ: "Violín", imp: "Violonchelo", hints: ["Arco", "Cuerda", "Clásico"] },
        { civ: "Arpa", imp: "Lira", hints: ["Dedos", "Cuerdas", "Ángel"] },
        { civ: "Bajo", imp: "Contrabajo", hints: ["Grave", "Cuerda", "Ritmo"] },
        { civ: "Banjo", imp: "Mandolina", hints: ["Folclore", "Cuerda", "Metal"] }
    ],
    "Deportes de Raqueta": [
        { civ: "Pádel", imp: "Tenis", hints: ["Red", "Pelota", "Pala"] },
        { civ: "Ping-Pong", imp: "Bádminton", hints: ["Mesa", "Red", "Raqueta"] },
        { civ: "Squash", imp: "Frontón", hints: ["Pared", "Raqueta", "Rápido"] },
        { civ: "Pickleball", imp: "Tenis Playa", hints: ["Red", "Arena", "Deporte"] },
        { civ: "Pelota Vasca", imp: "Jai Alai", hints: ["Cesta", "Mano", "Frontón"] }
    ],
    "Moda (Inditex)": [
        { civ: "Zara", imp: "Pull&Bear", hints: ["Ropa", "Tienda", "España"] },
        { civ: "Stradivarius", imp: "Bershka", hints: ["Chica", "Tienda", "Moda"] },
        { civ: "Massimo Dutti", imp: "Oysho", hints: ["Elegante", "Ropa", "Inditex"] },
        { civ: "Lefties", imp: "Primark", hints: ["Barato", "Ropa", "Tienda"] },
        { civ: "H&M", imp: "Mango", hints: ["Moda", "Tienda", "Ropa"] }
    ],
    "Zodiaco": [
        { civ: "Escorpio", imp: "Piscis", hints: ["Signo", "Estrellas", "Destino"] },
        { civ: "Leo", imp: "Aries", hints: ["Fuego", "Animal", "Horóscopo"] },
        { civ: "Géminis", imp: "Libra", hints: ["Aire", "Signo", "Dualidad"] },
        { civ: "Tauro", imp: "Capricornio", hints: ["Tierra", "Cuernos", "Signo"] },
        { civ: "Sagitario", imp: "Acuario", hints: ["Arco", "Estrellas", "Futuro"] }
    ],
    "Mitología Griega": [
        { civ: "Zeus", imp: "Odín", hints: ["Dios", "Rayo", "Poder"] },
        { civ: "Hércules", imp: "Aquiles", hints: ["Héroe", "Fuerza", "Leyenda"] },
        { civ: "Poseidón", imp: "Hades", hints: ["Dios", "Tridente", "Mar"] },
        { civ: "Atenea", imp: "Afrodita", hints: ["Diosa", "Sabiduría", "Mujer"] },
        { civ: "Minotauro", imp: "Medusa", hints: ["Monstruo", "Laberinto", "Mitología"] }
    ],
    "Emociones Complejas": [
        { civ: "Nostalgia", imp: "Melancolía", hints: ["Sentimiento", "Pasado", "Tristeza"] },
        { civ: "Euforia", imp: "Éxtasis", hints: ["Alegría", "Intenso", "Cuerpo"] },
        { civ: "Rencor", imp: "Envidia", hints: ["Malo", "Corazón", "Persona"] },
        { civ: "Alivio", imp: "Paz", hints: ["Calma", "Final", "Mente"] },
        { civ: "Ansiedad", imp: "Estrés", hints: ["Nervios", "Mente", "Prisa"] }
    ],
    "Filosofía": [
        { civ: "Platón", imp: "Aristóteles", hints: ["Pensador", "Grecia", "Libro"] },
        { civ: "Sócrates", imp: "Descartes", hints: ["Mente", "Filosofía", "Pregunta"] },
        { civ: "Nietzsche", imp: "Marx", hints: ["Alemán", "Idea", "Política"] },
        { civ: "Epicuro", imp: "Séneca", hints: ["Vida", "Felicidad", "Grecia"] },
        { civ: "Existencialismo", imp: "Nihilismo", hints: ["Nada", "Vida", "Sentido"] }
    ],
    "Electrodomésticos Pequeños": [
        { civ: "Tostadora", imp: "Sandwichera", hints: ["Cocina", "Calor", "Pan"] },
        { civ: "Batidora", imp: "Exprimidor", hints: ["Zumo", "Motor", "Vaso"] },
        { civ: "Cafetera", imp: "Tetera", hints: ["Desayuno", "Agua", "Taza"] },
        { civ: "Freidora", imp: "Airfryer", hints: ["Aceite", "Comida", "Frito"] },
        { civ: "Microondas", imp: "Horno", hints: ["Caliente", "Hogar", "Rápido"] }
    ],
    "Papelería y Oficina": [
        { civ: "Grapadora", imp: "Clips", hints: ["Mesa", "Papel", "Unión"] },
        { civ: "Agenda", imp: "Calendario", hints: ["Fecha", "Papel", "Día"] },
        { civ: "Rotulador", imp: "Subrayador", hints: ["Color", "Escribir", "Tinta"] },
        { civ: "Folio", imp: "Libreta", hints: ["Papel", "Blanco", "Escribir"] },
        { civ: "Tijeras", imp: "Pegamento", hints: ["Cortar", "Manualidad", "Mesa"] }
    ],
    "Transporte de Lujo": [
        { civ: "Yate", imp: "Crucero", hints: ["Mar", "Dinero", "Barco"] },
        { civ: "Jet Privado", imp: "Primera Clase", hints: ["Avión", "Viaje", "Rico"] },
        { civ: "Limusina", imp: "Ferrari", hints: ["Coche", "Largo", "Lujo"] },
        { civ: "Suite", imp: "Penthouse", hints: ["Hotel", "Cama", "Caro"] },
        { civ: "Helicóptero", imp: "Globo", hints: ["Volar", "Cielo", "Caro"] }
    ],
    "Juegos de Mesa Clásicos": [
        { civ: "Parchís", imp: "La Oca", hints: ["Dados", "Tablero", "Fichas"] },
        { civ: "Monopoly", imp: "Catan", hints: ["Dinero", "Casas", "Jugar"] },
        { civ: "Scrabble", imp: "Trivial", hints: ["Letras", "Palabras", "Mesa"] },
        { civ: "Ajedrez", imp: "Damas", hints: ["Fichas", "Estrategia", "Blanco y Negro"] },
        { civ: "Dominó", imp: "Cartas", hints: ["Mano", "Mesa", "Tradición"] }
    ],
    "Vida Nocturna": [
        { civ: "Discoteca", imp: "Pub", hints: ["Fiesta", "Noche", "Bebida"] },
        { civ: "Festival", imp: "Concierto", hints: ["Música", "Gente", "Entrada"] },
        { civ: "Bar de Copas", imp: "Chiringuito", hints: ["Beber", "Música", "Amigos"] },
        { civ: "Karaoke", imp: "Bingo", hints: ["Cantar", "Micro", "Noche"] },
        { civ: "After", imp: "Chill out", hints: ["Noche", "Música", "Final"] }
    ]
};

/**
 * SISTEMA DE FUSIÓN AUTOMÁTICA
 * Combina las categorías base con las personalizadas del usuario.
 */
export const CATEGORIES_DATA: Record<string, CategoryData[]> = (() => {
    // 1. Clonar base original
    const merged = { ...BASE_CATEGORIES };
    
    // 2. Iterar sobre categorías personalizadas
    Object.keys(CUSTOM_CATEGORIES).forEach(key => {
        if (merged[key]) {
            // Si la categoría existe, añadir palabras (merge arrays)
            merged[key] = [...merged[key], ...CUSTOM_CATEGORIES[key]];
        } else {
            // Si es nueva, añadir categoría completa
            merged[key] = CUSTOM_CATEGORIES[key];
        }
    });
    
    return merged;
})();
