import { CategoryData } from './customCategoriesPart1';

export const CUSTOM_CATEGORIES_PART_7: Record<string, CategoryData[]> = {
    "Superhéroes": [
        { civ: "Superman", imp: "Supergirl", hints: ["Capa", "Volar", "S" ] },
        { civ: "Batman", imp: "Robin", hints: ["Murciélago", "Cueva", "Noche"] },
        { civ: "Spiderman", imp: "Venom", hints: ["Araña", "Red", "Trepar"] },
        { civ: "Ironman", imp: "War Machine", hints: ["Armadura", "Rico", "Volar"] },
        { civ: "Thor", imp: "Loki", hints: ["Martillo", "Dios", "Trueno"] },
        { civ: "Hulk", imp: "La Cosa", hints: ["Fuerte", "Grande", "Monstruo"] },
        { civ: "Capitán América", imp: "Soldado Invierno", hints: ["Escudo", "Soldado", "USA"] },
        { civ: "Wonder Woman", imp: "Capitana Marvel", hints: ["Mujer", "Fuerte", "Volar"] },
        { civ: "Flash", imp: "Quicksilver", hints: ["Rápido", "Correr", "Rojo/Gris"] },
        { civ: "Aquaman", imp: "Namor", hints: ["Agua", "Tridente", "Rey"] },
        { civ: "Lobezno", imp: "Sabretooth", hints: ["Garras", "X-Men", "Curar"] },
        { civ: "Deadpool", imp: "Deathstroke", hints: ["Espadas", "Rojo", "Máscara"] },
        { civ: "Joker", imp: "Harley Quinn", hints: ["Payaso", "Loco", "Risa"] },
        { civ: "Thanos", imp: "Darkseid", hints: ["Guantelete", "Malo", "Espacio"] },
        { civ: "Magneto", imp: "Profesor X", hints: ["Casco", "Mente", "Mutante"] },
        { civ: "Cíclope", imp: "Tormenta", hints: ["Ojos", "Rayo", "X-Men"] },
        { civ: "Viuda Negra", imp: "Ojo de Halcón", hints: ["Espía", "Vengadores", "Humano"] },
        { civ: "Ant-Man", imp: "Átomo", hints: ["Pequeño", "Grande", "Traje"] },
        { civ: "Linterna Verde", imp: "Sinestro", hints: ["Anillo", "Luz", "Espacio"] },
        { civ: "Daredevil", imp: "Punisher", hints: ["Ciego", "Justicia", "Calle"] },
        { civ: "Doctor Strange", imp: "Doctor Fate", hints: ["Mago", "Capa", "Hechizo"] },
        { civ: "Pantera Negra", imp: "Catwoman", hints: ["Gato", "Garras", "Traje"] },
        { civ: "Groot", imp: "Rocket", hints: ["Árbol", "Mapache", "Guardianes"] },
        { civ: "Star-Lord", imp: "Han Solo", hints: ["Espacio", "Pistola", "Nave"] },
        { civ: "Shazam", imp: "Black Adam", hints: ["Rayo", "Magia", "Niño"] },
        { civ: "Robin", imp: "Nightwing", hints: ["Ayudante", "Batman", "Joven"] },
        { civ: "Batgirl", imp: "Batwoman", hints: ["Murciélago", "Mujer", "Capa"] },
        { civ: "Lex Luthor", imp: "Doctor Doom", hints: ["Calvo/Máscara", "Malo", "Genio"] },
        { civ: "Duende Verde", imp: "Octopus", hints: ["Spiderman", "Malo", "Volar/Brazos"] },
        { civ: "Mística", imp: "Camaleón", hints: ["Azul", "Cambio", "Forma"] },
        { civ: "Jean Grey", imp: "Bruja Escarlata", hints: ["Poder", "Mente", "Magia"] },
        { civ: "Gambito", imp: "Pícara", hints: ["Cartas", "Tocar", "X-Men"] },
        { civ: "Bestia", imp: "Hulk", hints: ["Azul/Verde", "Fuerte", "Listo"] },
        { civ: "Falcon", imp: "Buitre", hints: ["Alas", "Volar", "Pájaro"] },
        { civ: "Cyborg", imp: "Terminator", hints: ["Robot", "Ojo", "Metal"] },
        { civ: "Superhéroe", imp: "Villano", hints: ["Bueno/Malo", "Capa", "Poderes"] },
        { civ: "Capa", imp: "Máscara", hints: ["Ropa", "Volar", "Ocultar"] },
        { civ: "Escudo", imp: "Armadura", hints: ["Protección", "Metal", "Defensa"] },
        { civ: "Guarida", imp: "Base", hints: ["Secreto", "Lugar", "Esconder"] },
        { civ: "Identidad", imp: "Disfraz", hints: ["Nombre", "Secreto", "Traje"] },
        { civ: "Mutante", imp: "Inhumano", hints: ["Gen", "Poder", "Nacer"] },
        { civ: "Alien", imp: "Dios", hints: ["Espacio", "Poder", "Cielo"] },
        { civ: "Volar", imp: "Teletransporte", hints: ["Aire", "Moverse", "Rápido"] },
        { civ: "Fuerza", imp: "Velocidad", hints: ["Músculo", "Correr", "Poder"] },
        { civ: "Invisibilidad", imp: "Intangibilidad", hints: ["NoVer", "Atravesar", "Poder"] },
        { civ: "Rayo", imp: "Fuego", hints: ["Energía", "Quemar", "Luz"] },
        { civ: "Hielo", imp: "Agua", hints: ["Frío", "Congelar", "Líquido"] },
        { civ: "Mente", imp: "Telequinesis", hints: ["Pensar", "Mover", "Cerebro"] },
        { civ: "Regeneración", imp: "Inmortalidad", hints: ["Curar", "Vivir", "Herida"] },
        { civ: "Sidekick", imp: "Compañero", hints: ["Ayuda", "Héroe", "Joven"] },
        { civ: "Liga Justicia", imp: "Vengadores", hints: ["Grupo", "Equipo", "Héroes"] },
        { civ: "X-Men", imp: "4 Fantásticos", hints: ["Mutantes", "Familia", "Grupo"] },
        { civ: "Kryptonita", imp: "Veneno", hints: ["Verde", "Debilidad", "Matar"] },
        { civ: "Batmovil", imp: "Nave", hints: ["Coche", "Batman", "Transporte"] },
        { civ: "Capa", imp: "Alas", hints: ["Espalda", "Volar", "Tela"] },
        { civ: "Antifaz", imp: "Casco", hints: ["Ojos", "Cara", "Tapar"] },
        { civ: "Mallas", imp: "Uniforme", hints: ["Ropa", "Ajustado", "Color"] },
        { civ: "Rescate", imp: "Misión", hints: ["Salvar", "Ayuda", "Trabajo"] },
        { civ: "Crimen", imp: "Justicia", hints: ["Malo", "Ley", "Policía"] },
        { civ: "Ciudad", imp: "Metrópolis", hints: ["Edificios", "Gente", "Proteger"] },
        { civ: "Gotham", imp: "Nueva York", hints: ["Ciudad", "Batman/Spiderman", "Noche"] },
        { civ: "Asgard", imp: "Olimpo", hints: ["Dioses", "Casa", "Cielo"] },
        { civ: "Wakanda", imp: "Atlantis", hints: ["País", "Oculto", "Tecnología"] },
        { civ: "Stan Lee", imp: "Jack Kirby", hints: ["Creador", "Cómics", "Marvel"] },
        { civ: "Cómic", imp: "Película", hints: ["Papel", "Dibujos", "Leer"] },
        { civ: "Viñeta", imp: "Bocadillo", hints: ["Dibujo", "Texto", "Página"] },
        { civ: "Multiverso", imp: "Universo", hints: ["Muchos", "Mundos", "Variantes"] },
        { civ: "Clon", imp: "Robot", hints: ["Copia", "Igual", "Falso"] },
        { civ: "Magia", imp: "Ciencia", hints: ["Truco", "Hechizo", "Estudio"] },
        { civ: "Radiactivo", imp: "Químico", hints: ["Araña", "Peligro", "Poder"] },
        { civ: "Mordisco", imp: "Inyección", hints: ["Dientes", "Sangre", "Origen"] },
        { civ: "Traje", imp: "Arma", hints: ["Poner", "Luchar", "Objeto"] },
        { civ: "Láser", imp: "Bala", hints: ["Rojo", "Disparo", "Luz"] },
        { civ: "Explosión", imp: "Golpe", hints: ["Boom", "Ruido", "Fuego"] },
        { civ: "Salvar", imp: "Vengar", hints: ["Ayuda", "Vida", "Castigo"] },
        { civ: "Civil", imp: "Héroe", hints: ["Persona", "Normal", "Disfraz"] },
        { civ: "Reportero", imp: "Fotógrafo", hints: ["Noticia", "Superman/Spiderman", "Trabajo"] },
        { civ: "Millonario", imp: "Científico", hints: ["Dinero", "Batman/Ironman", "Listo"] },
        { civ: "Huérfano", imp: "Elegido", hints: ["Padres", "Triste", "Destino"] },
        { civ: "Vigilante", imp: "Policía", hints: ["Noche", "Ley", "Máscara"] },
        { civ: "Patrulla", imp: "Guardia", hints: ["Vigilar", "Calle", "Grupo"] },
        { civ: "Símbolo", imp: "Logo", hints: ["Pecho", "Dibujo", "Marca"] },
        { civ: "Secreto", imp: "Misterio", hints: ["Nadie", "Saber", "Oculto"] },
        { civ: "Origen", imp: "Final", hints: ["Principio", "Historia", "Empezar"] },
        { civ: "Batalla", imp: "Guerra", hints: ["Pelea", "Lucha", "Final"] },
        { civ: "Cameo", imp: "Escena", hints: ["Salir", "Breve", "Película"] },
        { civ: "Créditos", imp: "Intro", hints: ["Letras", "Final", "Nombre"] },
        { civ: "Reboot", imp: "Remake", hints: ["Nuevo", "Empezar", "Película"] },
        { civ: "Saga", imp: "Trilogía", hints: ["Películas", "Historia", "Varias"] },
        { civ: "Fan", imp: "Friki", hints: ["Gustar", "Saber", "Mucho"] },
        { civ: "Cosplay", imp: "Disfraz", hints: ["Ropa", "Personaje", "Evento"] },
        { civ: "Evento", imp: "Convención", hints: ["Reunión", "Fans", "Cómics"] },
        { civ: "Merchandising", imp: "Juguete", hints: ["Vender", "Muñeco", "Tienda"] },
        { civ: "Póster", imp: "Camiseta", hints: ["Pared", "Imagen", "Ropa"] },
        { civ: "Funko", imp: "Figura", hints: ["Muñeco", "Cabeza", "Colección"] },
        { civ: "Teoría", imp: "Spoiler", hints: ["Idea", "Pensar", "Internet"] },
        { civ: "Canon", imp: "Relleno", hints: ["Historia", "Real", "Oficial"] },
        { civ: "Spin-off", imp: "Secuela", hints: ["Aparte", "Historia", "Otro"] },
        { civ: "Precuela", imp: "Secuela", hints: ["Antes", "Después", "Película"] },
        { civ: "Estreno", imp: "Adelanto", hints: ["Día", "Cine", "Ver"] }
    ],
    "Transporte": [
        { civ: "Coche", imp: "Moto", hints: ["Ruedas", "Carretera", "Motor"] },
        { civ: "Autobús", imp: "Camión", hints: ["Grande", "Ruedas", "Carretera"] },
        { civ: "Tren", imp: "Metro", hints: ["Vías", "Estación", "Pasajeros"] },
        { civ: "Avión", imp: "Helicóptero", hints: ["Volar", "Aire", "Alas/Hélice"] },
        { civ: "Barco", imp: "Lancha", hints: ["Agua", "Mar", "Navegar"] },
        { civ: "Bicicleta", imp: "Patinete", hints: ["Ruedas", "Equilibrio", "Calle"] },
        { civ: "Taxi", imp: "Uber", hints: ["Coche", "Pagar", "Llevar"] },
        { civ: "Furgoneta", imp: "Caravana", hints: ["Grande", "Carga/Dormir", "Coche"] },
        { civ: "Tranvía", imp: "Tren", hints: ["Ciudad", "Vías", "Calle"] },
        { civ: "Ave", imp: "Cercanías", hints: ["Tren", "Rápido/Lento", "Renfe"] },
        { civ: "Globo", imp: "Dirigible", hints: ["Volar", "Aire", "Cesta"] },
        { civ: "Submarino", imp: "Barco", hints: ["Agua", "Debajo", "Mar"] },
        { civ: "Cohete", imp: "Transbordador", hints: ["Espacio", "Fuego", "Volar"] },
        { civ: "Tractor", imp: "Grúa", hints: ["Campo/Obra", "Lento", "Fuerza"] },
        { civ: "Ambulancia", imp: "Bomberos", hints: ["Sirena", "Emergencia", "Ayuda"] },
        { civ: "Policía", imp: "Guardia Civil", hints: ["Coche", "Sirena", "Luces"] },
        { civ: "Monopatín", imp: "Patines", hints: ["Ruedas", "Pies", "Suelo"] },
        { civ: "Teleférico", imp: "Funicular", hints: ["Cable", "Montaña", "Subir"] },
        { civ: "Ascensor", imp: "Escalera", hints: ["Subir", "Edificio", "Pisos"] },
        { civ: "Puente", imp: "Túnel", hints: ["Cruzar", "Carretera", "Agua/Tierra"] },
        { civ: "Carretera", imp: "Autopista", hints: ["Asfalto", "Coches", "Viaje"] },
        { civ: "Calle", imp: "Avenida", hints: ["Ciudad", "Coches", "Dirección"] },
        { civ: "Acera", imp: "Calzada", hints: ["Peatón", "Andar", "Suelo"] },
        { civ: "Semáforo", imp: "Señal", hints: ["Luces", "Tráfico", "Parar"] },
        { civ: "Paso Cebra", imp: "Semáforo", hints: ["Cruzar", "Rayas", "Peatón"] },
        { civ: "Gasolinera", imp: "Taller", hints: ["Coche", "Parar", "Combustible"] },
        { civ: "Aeropuerto", imp: "Estación", hints: ["Viaje", "Avión/Tren", "Maletas"] },
        { civ: "Puerto", imp: "Embarcadero", hints: ["Barcos", "Mar", "Llegar"] },
        { civ: "Parada", imp: "Estación", hints: ["Bus/Metro", "Esperar", "Gente"] },
        { civ: "Billete", imp: "Abono", hints: ["Pagar", "Viaje", "Tarjeta"] },
        { civ: "Conductor", imp: "Piloto", hints: ["Manejar", "Vehículo", "Persona"] },
        { civ: "Pasajero", imp: "Copiloto", hints: ["Viajar", "Sentado", "Acompañar"] },
        { civ: "Revisor", imp: "Controlador", hints: ["Billete", "Mirar", "Multa"] },
        { civ: "Mecánico", imp: "Chófer", hints: ["Arreglar", "Coche", "Profesión"] },
        { civ: "Rueda", imp: "Neumático", hints: ["Girar", "Caucho", "Coche"] },
        { civ: "Volante", imp: "Manillar", hints: ["Dirección", "Manejar", "Manos"] },
        { civ: "Motor", imp: "Batería", hints: ["Fuerza", "Ruido", "Energía"] },
        { civ: "Freno", imp: "Acelerador", hints: ["Pedal", "Parar", "Velocidad"] },
        { civ: "Marcha", imp: "Embrague", hints: ["Cambio", "Coche", "Velocidad"] },
        { civ: "Retrovisor", imp: "Parabrisas", hints: ["Espejo", "Cristal", "Ver"] },
        { civ: "Cinturón", imp: "Airbag", hints: ["Seguridad", "Abrochar", "Coche"] },
        { civ: "Maletero", imp: "Guantera", hints: ["Guardar", "Coche", "Espacio"] },
        { civ: "Capó", imp: "Techo", hints: ["Coche", "Motor", "Parte"] },
        { civ: "Matrícula", imp: "Marca", hints: ["Placa", "Números", "Identificar"] },
        { civ: "Llave", imp: "Mando", hints: ["Arrancar", "Abrir", "Coche"] },
        { civ: "Gasolina", imp: "Diésel", hints: ["Combustible", "Llenar", "Manguera"] },
        { civ: "Eléctrico", imp: "Híbrido", hints: ["Coche", "Enchufe", "Motor"] },
        { civ: "Aceite", imp: "Agua", hints: ["Motor", "Líquido", "Revisar"] },
        { civ: "Pinchazo", imp: "Avería", hints: ["Rueda", "Taller", "Problema"] },
        { civ: "Multa", imp: "Peaje", hints: ["Pagar", "Policía/Carretera", "Dinero"] },
        { civ: "Atasco", imp: "Tráfico", hints: ["Coches", "Parado", "Lento"] },
        { civ: "Accidente", imp: "Choque", hints: ["Golpe", "Coche", "Mal"] },
        { civ: "Curva", imp: "Recta", hints: ["Carretera", "Giro", "Volante"] },
        { civ: "Cruce", imp: "Rotonda", hints: ["Dirección", "Coches", "Intersección"] },
        { civ: "Salida", imp: "Entrada", hints: ["Autopista", "Cartel", "Dirección"] },
        { civ: "Norte", imp: "Sur", hints: ["Dirección", "Brújula", "Mapa"] },
        { civ: "Este", imp: "Oeste", hints: ["Dirección", "Sol", "Mapa"] },
        { civ: "Mapa", imp: "GPS", hints: ["Ruta", "Papel/Pantalla", "Guiar"] },
        { civ: "Ruta", imp: "Camino", hints: ["Viaje", "Seguir", "Dirección"] },
        { civ: "Destino", imp: "Origen", hints: ["Llegar", "Viaje", "Final"] },
        { civ: "Turista", imp: "Viajero", hints: ["Persona", "Visita", "Maleta"] },
        { civ: "Equipaje", imp: "Maleta", hints: ["Bulto", "Ropa", "Viaje"] },
        { civ: "Mochila", imp: "Bolso", hints: ["Espalda", "Llevar", "Cosas"] },
        { civ: "Pasaporte", imp: "DNI", hints: ["Documento", "Viaje", "Frontera"] },
        { civ: "Visado", imp: "Billete", hints: ["Permiso", "País", "Papel"] },
        { civ: "Aduana", imp: "Frontera", hints: ["Control", "País", "Policía"] },
        { civ: "Embarque", imp: "Facturar", hints: ["Avión", "Puerta", "Maleta"] },
        { civ: "Despegue", imp: "Aterrizaje", hints: ["Avión", "Volar", "Suelo"] },
        { civ: "Vuelo", imp: "Viaje", hints: ["Avión", "Aire", "Ir"] },
        { civ: "Asiento", imp: "Plaza", hints: ["Sentarse", "Número", "Billete"] },
        { civ: "Primera", imp: "Turista", hints: ["Clase", "Avión/Tren", "Caro"] },
        { civ: "Ventana", imp: "Pasillo", hints: ["Asiento", "Ver", "Avión"] },
        { civ: "Azafata", imp: "Piloto", hints: ["Avión", "Ayuda", "Uniforme"] },
        { civ: "Turbulencia", imp: "Tormenta", hints: ["Movimiento", "Avión", "Miedo"] },
        { civ: "Andén", imp: "Vía", hints: ["Tren", "Esperar", "Suelo"] },
        { civ: "Vagón", imp: "Locomotora", hints: ["Tren", "Parte", "Gente"] },
        { civ: "Camarote", imp: "Cubierta", hints: ["Barco", "Dormir/Fuera", "Habitación"] },
        { civ: "Ancla", imp: "Vela", hints: ["Barco", "Parar", "Viento"] },
        { civ: "Remo", imp: "Timón", hints: ["Barca", "Mover", "Dirección"] },
        { civ: "Casco", imp: "Chaleco", hints: ["Seguridad", "Cabeza/Cuerpo", "Moto/Barco"] },
        { civ: "Cadena", imp: "Pedal", hints: ["Bici", "Metal", "Pie"] },
        { civ: "Sillín", imp: "Cuadro", hints: ["Bici", "Asiento", "Parte"] },
        { civ: "Pinchazo", imp: "Caída", hints: ["Rueda", "Suelo", "Dolor"] },
        { civ: "Carril Bici", imp: "Acera", hints: ["Bici", "Suelo", "Pintado"] },
        { civ: "Patinete", imp: "Skate", hints: ["Ruedas", "Eléctrico/Tabla", "Calle"] },
        { civ: "Segway", imp: "Hoverboard", hints: ["Ruedas", "Equilibrio", "Turista"] },
        { civ: "Carro", imp: "Cesta", hints: ["Compra", "Ruedas", "Supermercado"] },
        { civ: "Silla Ruedas", imp: "Muleta", hints: ["Ayuda", "Moverse", "Hospital"] },
        { civ: "Camilla", imp: "Cama", hints: ["Hospital", "Ruedas", "Enfermo"] },
        { civ: "Grúa", imp: "Excavadora", hints: ["Obra", "Levantar", "Máquina"] },
        { civ: "Remolque", imp: "Caravana", hints: ["Coche", "Atrás", "Carga"] },
        { civ: "Barca", imp: "Canoa", hints: ["Agua", "Pequeña", "Remar"] },
        { civ: "Yate", imp: "Velero", hints: ["Barco", "Lujo/Viento", "Mar"] },
        { civ: "Crucero", imp: "Transatlántico", hints: ["Barco", "Grande", "Vacaciones"] }
    ],
    "Videojuegos": [
        { civ: "Mario", imp: "Luigi", hints: ["Nintendo", "Bigote", "Rojo/Verde"] },
        { civ: "Zelda", imp: "Peach", hints: ["Princesa", "Juego", "Rescatar"] },
        { civ: "Link", imp: "Zelda", hints: ["Héroe", "Espada", "Verde"] },
        { civ: "Sonic", imp: "Tails", hints: ["Erizo", "Rápido", "Azul"] },
        { civ: "Pikachu", imp: "Eevee", hints: ["Pokémon", "Amarillo", "Ratón"] },
        { civ: "Charizard", imp: "Dragonite", hints: ["Dragón", "Fuego", "Volar"] },
        { civ: "Kratos", imp: "Thor", hints: ["Dios", "Guerra", "Hacha/Martillo"] },
        { civ: "Master Chief", imp: "Doom Guy", hints: ["Casco", "Verde", "Disparos"] },
        { civ: "Ryu", imp: "Ken", hints: ["Lucha", "StreetFighter", "Hadoken"] },
        { civ: "Pacman", imp: "Fantasma", hints: ["Comer", "Bolitas", "Laberinto"] },
        { civ: "Tetris", imp: "Candy Crush", hints: ["Piezas", "Encajar", "Colores"] },
        { civ: "Minecraft", imp: "Roblox", hints: ["Cubos", "Construir", "Niños"] },
        { civ: "Fortnite", imp: "PUBG", hints: ["Disparos", "Mapa", "BattleRoyale"] },
        { civ: "FIFA", imp: "PES", hints: ["Fútbol", "Balón", "EA"] },
        { civ: "GTA", imp: "Saints Row", hints: ["Coches", "Crimen", "Ciudad"] },
        { civ: "Call of Duty", imp: "Battlefield", hints: ["Guerra", "Disparos", "Soldado"] },
        { civ: "LoL", imp: "Dota", hints: ["Torres", "PC", "Equipo"] },
        { civ: "WoW", imp: "Final Fantasy", hints: ["Rol", "Magia", "Online"] },
        { civ: "Sims", imp: "Animal Crossing", hints: ["Vida", "Casa", "Simulador"] },
        { civ: "Among Us", imp: "Fall Guys", hints: ["Colores", "Juego", "Muñecos"] },
        { civ: "Resident Evil", imp: "Silent Hill", hints: ["Terror", "Zombies", "Miedo"] },
        { civ: "Tomb Raider", imp: "Uncharted", hints: ["Aventura", "Tesoros", "Explorar"] },
        { civ: "Assassin's Creed", imp: "Prince Persia", hints: ["Saltar", "Matar", "Historia"] },
        { civ: "Dark Souls", imp: "Elden Ring", hints: ["Difícil", "Morir", "Espada"] },
        { civ: "Metal Gear", imp: "Splinter Cell", hints: ["Espía", "Sigilo", "Soldado"] },
        { civ: "Portal", imp: "Half-Life", hints: ["Ciencia", "Valve", "Puzzle"] },
        { civ: "Overwatch", imp: "Valorant", hints: ["Disparos", "Equipo", "Poderes"] },
        { civ: "Clash Royale", imp: "Clash Clans", hints: ["Móvil", "Cartas", "Torres"] },
        { civ: "Angry Birds", imp: "Plants vs Zombies", hints: ["Móvil", "Lanzar", "Defensa"] },
        { civ: "PlayStation", imp: "Xbox", hints: ["Consola", "Mando", "TV"] },
        { civ: "Nintendo", imp: "Sega", hints: ["Japón", "Juegos", "Marca"] },
        { civ: "Switch", imp: "Steam Deck", hints: ["Portátil", "Consola", "Pantalla"] },
        { civ: "PC", imp: "Consola", hints: ["Jugar", "Teclado/Mando", "Pantalla"] },
        { civ: "Mando", imp: "Teclado", hints: ["Control", "Botones", "Jugar"] },
        { civ: "Ratón", imp: "Joystick", hints: ["Mover", "Cámara", "Juego"] },
        { civ: "Pantalla", imp: "Monitor", hints: ["Ver", "Imagen", "Juego"] },
        { civ: "Cascos", imp: "Altavoces", hints: ["Oír", "Sonido", "Cabeza"] },
        { civ: "Micro", imp: "Chat", hints: ["Hablar", "Voz", "Equipo"] },
        { civ: "Silla", imp: "Sillón", hints: ["Sentarse", "Gamer", "Cómodo"] },
        { civ: "Disco", imp: "Digital", hints: ["Juego", "Formato", "Caja"] },
        { civ: "Cartucho", imp: "Tarjeta", hints: ["Juego", "Nintendo", "Insertar"] },
        { civ: "Online", imp: "Offline", hints: ["Internet", "Conexión", "Jugar"] },
        { civ: "Lag", imp: "Bug", hints: ["Lento", "Fallo", "Error"] },
        { civ: "Noob", imp: "Pro", hints: ["Novato", "Experto", "Jugar"] },
        { civ: "Campero", imp: "Rusher", hints: ["Esconder", "Quieto", "Atacar"] },
        { civ: "Hacker", imp: "Cheater", hints: ["Trampa", "Código", "Ganar"] },
        { civ: "Boss", imp: "NPC", hints: ["Jefe", "Enemigo", "Personaje"] },
        { civ: "Nivel", imp: "Mundo", hints: ["Fase", "Pantalla", "Pasar"] },
        { civ: "Vida", imp: "Maná", hints: ["Barra", "Salud", "Verde/Azul"] },
        { civ: "Game Over", imp: "You Win", hints: ["Fin", "Perder", "Texto"] },
        { civ: "Save", imp: "Load", hints: ["Guardar", "Cargar", "Partida"] },
        { civ: "Pausa", imp: "Menú", hints: ["Parar", "Opciones", "Botón"] },
        { civ: "Start", imp: "Select", hints: ["Botón", "Empezar", "Mando"] },
        { civ: "X", imp: "Y", hints: ["Botón", "Letra", "Mando"] },
        { civ: "FPS", imp: "RPG", hints: ["Género", "Disparos", "Rol"] },
        { civ: "MMO", imp: "MOBA", hints: ["Online", "Masivo", "Gente"] },
        { civ: "Indie", imp: "Triple A", hints: ["Pequeño", "Juego", "Presupuesto"] },
        { civ: "Demo", imp: "Beta", hints: ["Prueba", "Gratis", "Versión"] },
        { civ: "DLC", imp: "Expansión", hints: ["Contenido", "Extra", "Pagar"] },
        { civ: "Skin", imp: "Loot", hints: ["Traje", "Recompensa", "Caja"] },
        { civ: "Ban", imp: "Kick", hints: ["Expulsar", "Castigo", "Fuera"] },
        { civ: "Streamer", imp: "Youtuber", hints: ["Jugar", "Ver", "Directo"] },
        { civ: "Twitch", imp: "YouTube", hints: ["Plataforma", "Vídeo", "Directo"] },
        { civ: "Speedrun", imp: "Walkthrough", hints: ["Rápido", "Guía", "Pasar"] },
        { civ: "Glitch", imp: "Truco", hints: ["Fallo", "Error", "Ventaja"] },
        { civ: "Pixel", imp: "Polígono", hints: ["Gráfico", "Cuadrado", "Retro/3D"] },
        { civ: "Retro", imp: "Moderno", hints: ["Antiguo", "Juego", "Estilo"] },
        { civ: "Arcade", imp: "Simulador", hints: ["Máquina", "Realista", "Juego"] },
        { civ: "Estrategia", imp: "Acción", hints: ["Pensar", "Rápido", "Género"] },
        { civ: "Terror", imp: "Suspense", hints: ["Miedo", "Susto", "Género"] },
        { civ: "Carreras", imp: "Deportes", hints: ["Coches", "Competición", "Género"] },
        { civ: "Puzle", imp: "Plataformas", hints: ["Pensar", "Saltar", "Género"] },
        { civ: "Mundo Abierto", imp: "Pasillo", hints: ["Mapa", "Libre", "Explorar"] },
        { civ: "Misión", imp: "Quest", hints: ["Tarea", "Objetivo", "Hacer"] },
        { civ: "Inventario", imp: "Mochila", hints: ["Objetos", "Guardar", "Menú"] },
        { civ: "Arma", imp: "Escudo", hints: ["Atacar", "Defender", "Objeto"] },
        { civ: "Poción", imp: "Botiquín", hints: ["Beber", "Curar", "Salud"] },
        { civ: "Moneda", imp: "Gema", hints: ["Dinero", "Comprar", "Valor"] },
        { civ: "Llave", imp: "Tarjeta", hints: ["Abrir", "Puerta", "Objeto"] },
        { civ: "Craftear", imp: "Farmear", hints: ["Crear", "Recoger", "Materiales"] },
        { civ: "Spawn", imp: "Checkpoint", hints: ["Aparecer", "Punto", "Guardar"] },
        { civ: "Campear", imp: "Rushear", hints: ["Esperar", "Correr", "Estrategia"] },
        { civ: "Tank", imp: "Healer", hints: ["Resistir", "Curar", "Rol"] },
        { civ: "DPS", imp: "Support", hints: ["Daño", "Ayuda", "Rol"] },
        { civ: "Combo", imp: "Golpe", hints: ["Seguido", "Ataque", "Muchos"] },
        { civ: "Critico", imp: "Fallo", hints: ["Daño", "Mucho", "Ataque"] },
        { civ: "Headshot", imp: "Kill", hints: ["Cabeza", "Muerte", "Disparo"] },
        { civ: "Bot", imp: "Player", hints: ["Máquina", "Persona", "Jugar"] },
        { civ: "Server", imp: "Host", hints: ["Conexión", "Partida", "Alojador"] },
        { civ: "Ping", imp: "FPS", hints: ["Conexión", "Fluidez", "Número"] },
        { civ: "Teabag", imp: "Bailar", hints: ["Burla", "Agacharse", "Muerto"] },
        { civ: "Rage Quit", imp: "Disconnect", hints: ["Enfado", "Salir", "Partida"] }
    ],
    "Clima y naturaleza": [
        { civ: "Sol", imp: "Luna", hints: ["Cielo", "Luz", "Día/Noche"] },
        { civ: "Nube", imp: "Niebla", hints: ["Blanco", "Cielo", "Agua"] },
        { civ: "Lluvia", imp: "Granizo", hints: ["Agua", "Caer", "Mojar"] },
        { civ: "Nieve", imp: "Hielo", hints: ["Blanco", "Frío", "Invierno"] },
        { civ: "Viento", imp: "Brisa", hints: ["Aire", "Mover", "Soplar"] },
        { civ: "Tormenta", imp: "Huracán", hints: ["Rayo", "Lluvia", "Fuerte"] },
        { civ: "Trueno", imp: "Rayo", hints: ["Sonido", "Luz", "Tormenta"] },
        { civ: "Arcoíris", imp: "Aurora", hints: ["Colores", "Cielo", "Luz"] },
        { civ: "Calor", imp: "Frío", hints: ["Temperatura", "Sol", "Sensación"] },
        { civ: "Verano", imp: "Invierno", hints: ["Estación", "Sol/Nieve", "Tiempo"] },
        { civ: "Primavera", imp: "Otoño", hints: ["Flores", "Hojas", "Estación"] },
        { civ: "Día", imp: "Noche", hints: ["Luz", "Oscuro", "Tiempo"] },
        { civ: "Amanecer", imp: "Atardecer", hints: ["Sol", "Horizonte", "Color"] },
        { civ: "Cielo", imp: "Mar", hints: ["Azul", "Arriba", "Inmenso"] },
        { civ: "Tierra", imp: "Arena", hints: ["Suelo", "Marrón", "Playa"] },
        { civ: "Montaña", imp: "Colina", hints: ["Alto", "Piedra", "Subir"] },
        { civ: "Volcán", imp: "Geiser", hints: ["Fuego", "Agua", "Explosión"] },
        { civ: "Río", imp: "Arroyo", hints: ["Agua", "Corriente", "Dulce"] },
        { civ: "Lago", imp: "Laguna", hints: ["Agua", "Quieta", "Azul"] },
        { civ: "Mar", imp: "Océano", hints: ["Agua", "Salada", "Grande"] },
        { civ: "Playa", imp: "Costa", hints: ["Arena", "Mar", "Verano"] },
        { civ: "Isla", imp: "Península", hints: ["Tierra", "Agua", "Rodeado"] },
        { civ: "Desierto", imp: "Duna", hints: ["Arena", "Seco", "Calor"] },
        { civ: "Selva", imp: "Bosque", hints: ["Árboles", "Verde", "Animales"] },
        { civ: "Árbol", imp: "Arbusto", hints: ["Tronco", "Hojas", "Planta"] },
        { civ: "Flor", imp: "Hoja", hints: ["Color", "Olor", "Planta"] },
        { civ: "Raíz", imp: "Rama", hints: ["Planta", "Suelo", "Madera"] },
        { civ: "Piedra", imp: "Roca", hints: ["Duro", "Suelo", "Gris"] },
        { civ: "Cueva", imp: "Gruta", hints: ["Oscuro", "Agujero", "Piedra"] },
        { civ: "Cascada", imp: "Catarata", hints: ["Agua", "Caer", "Altura"] },
        { civ: "Ola", imp: "Marea", hints: ["Mar", "Movimiento", "Agua"] },
        { civ: "Terremoto", imp: "Tsunami", hints: ["Temblor", "Agua", "Destrucción"] },
        { civ: "Inundación", imp: "Sequía", hints: ["Agua", "Falta", "Desastre"] },
        { civ: "Fuego", imp: "Incendio", hints: ["Calor", "Quemar", "Llama"] },
        { civ: "Humo", imp: "Ceniza", hints: ["Gris", "Fuego", "Aire"] },
        { civ: "Aire", imp: "Oxígeno", hints: ["Respirar", "Invisible", "Gas"] },
        { civ: "Estrella", imp: "Planeta", hints: ["Cielo", "Luz", "Noche"] },
        { civ: "Constelación", imp: "Galaxia", hints: ["Estrellas", "Grupo", "Cielo"] },
        { civ: "Meteorito", imp: "Cometa", hints: ["Piedra", "Espacio", "Caer"] },
        { civ: "Eclipse", imp: "Luna Nueva", hints: ["Oscuro", "Sol/Luna", "Tapar"] },
        { civ: "Rocío", imp: "Escarcha", hints: ["Agua", "Mañana", "Hierba"] },
        { civ: "Barro", imp: "Lodo", hints: ["Tierra", "Agua", "Sucio"] },
        { civ: "Polvo", imp: "Arena", hints: ["Pequeño", "Sucio", "Aire"] },
        { civ: "Charco", imp: "Balsa", hints: ["Agua", "Suelo", "Lluvia"] },
        { civ: "Acantilado", imp: "Barranco", hints: ["Altura", "Caer", "Piedra"] },
        { civ: "Valle", imp: "Llanura", hints: ["Bajo", "Montañas", "Verde"] },
        { civ: "Cumbre", imp: "Cima", hints: ["Arriba", "Pico", "Montaña"] },
        { civ: "Glaciar", imp: "Iceberg", hints: ["Hielo", "Grande", "Frío"] },
        { civ: "Jungla", imp: "Sabana", hints: ["Árboles/Hierba", "Animales", "Calor"] },
        { civ: "Oasis", imp: "Espejismo", hints: ["Agua", "Desierto", "Verde"] },
        { civ: "Pantano", imp: "Ciénaga", hints: ["Agua", "Barro", "Sucio"] },
        { civ: "Coral", imp: "Alga", hints: ["Mar", "Colores", "Fondo"] },
        { civ: "Setas", imp: "Hongos", hints: ["Bosque", "Suelo", "Otoño"] },
        { civ: "Musgo", imp: "Hierba", hints: ["Verde", "Piedra", "Húmedo"] },
        { civ: "Cactus", imp: "Palmera", hints: ["Pincho", "Desierto", "Planta"] },
        { civ: "Pino", imp: "Abeto", hints: ["Árbol", "Navidad", "Verde"] },
        { civ: "Roble", imp: "Encina", hints: ["Árbol", "Duro", "Bellota"] },
        { civ: "Rosa", imp: "Clavel", hints: ["Flor", "Roja", "Olor"] },
        { civ: "Margarita", imp: "Girasol", hints: ["Flor", "Pétalos", "Amarillo"] },
        { civ: "Tulipán", imp: "Amapola", hints: ["Flor", "Campo", "Color"] },
        { civ: "Semilla", imp: "Fruto", hints: ["Plantar", "Comer", "Crecer"] },
        { civ: "Huerto", imp: "Jardín", hints: ["Plantar", "Comida/Flor", "Casa"] },
        { civ: "Granja", imp: "Campo", hints: ["Animales", "Tierra", "Rural"] },
        { civ: "Norte", imp: "Sur", hints: ["Frío/Calor", "Brújula", "Mapa"] },
        { civ: "Este", imp: "Oeste", hints: ["Sol", "Salida/Puesta", "Mapa"] },
        { civ: "Atmósfera", imp: "Capa", hints: ["Aire", "Tierra", "Cielo"] },
        { civ: "Ozono", imp: "Contaminación", hints: ["Capa", "Agujero", "Gas"] },
        { civ: "Clima", imp: "Tiempo", hints: ["Temperatura", "Lugar", "Cambio"] },
        { civ: "Humedad", imp: "Sequedad", hints: ["Agua", "Aire", "Sensación"] },
        { civ: "Presión", imp: "Altura", hints: ["Aire", "Oídos", "Medir"] },
        { civ: "Termómetro", imp: "Grados", hints: ["Temperatura", "Medir", "Calor"] },
        { civ: "Paraguas", imp: "Chubasquero", hints: ["Lluvia", "Mojar", "Proteger"] },
        { civ: "Gafas Sol", imp: "Crema", hints: ["Verano", "Ojos/Piel", "Proteger"] },
        { civ: "Sombra", imp: "Cobijo", hints: ["Sol", "Fresco", "Árbol"] },
        { civ: "Relámpago", imp: "Centella", hints: ["Luz", "Rápido", "Cielo"] },
        { civ: "Ciclón", imp: "Tifón", hints: ["Viento", "Agua", "Girar"] },
        { civ: "Avalancha", imp: "Desprendimiento", hints: ["Nieve/Roca", "Caer", "Montaña"] },
        { civ: "Maremoto", imp: "Oleaje", hints: ["Mar", "Fuerza", "Costa"] },
        { civ: "Erupción", imp: "Lava", hints: ["Volcán", "Fuego", "Explotar"] },
        { civ: "Cráter", imp: "Agujero", hints: ["Volcán", "Meteorito", "Suelo"] },
        { civ: "Magma", imp: "Lava", hints: ["Fuego", "Piedra", "Interior"] },
        { civ: "Fósil", imp: "Hueso", hints: ["Piedra", "Antiguo", "Animal"] },
        { civ: "Mineral", imp: "Gema", hints: ["Piedra", "Mina", "Brillo"] },
        { civ: "Diamante", imp: "Carbón", hints: ["Duro", "Joya/Fuego", "Mina"] },
        { civ: "Cuarzo", imp: "Cristal", hints: ["Piedra", "Transparente", "Mineral"] },
        { civ: "Petróleo", imp: "Gas", hints: ["Negro", "Suelo", "Energía"] },
        { civ: "Cosecha", imp: "Siembra", hints: ["Recoger", "Plantar", "Campo"] },
        { civ: "Trigo", imp: "Cebada", hints: ["Campo", "Amarillo", "Pan/Cerveza"] },
        { civ: "Maíz", imp: "Pipa", hints: ["Planta", "Amarillo", "Comer"] },
        { civ: "Uva", imp: "Aceituna", hints: ["Vino/Aceite", "Fruto", "Campo"] },
        { civ: "Pasto", imp: "Cesped", hints: ["Hierba", "Vaca", "Verde"] },
        { civ: "Paja", imp: "Heno", hints: ["Seco", "Amarillo", "Animales"] },
        { civ: "Establo", imp: "Corral", hints: ["Animales", "Casa", "Granja"] },
        { civ: "Nido", imp: "Madriguera", hints: ["Pájaro/Conejo", "Casa", "Crías"] },
        { civ: "Colmena", imp: "Hormiguero", hints: ["Abejas/Hormigas", "Grupo", "Casa"] },
        { civ: "Telaraña", imp: "Red", hints: ["Araña", "Hilo", "Atrapar"] }
    ]
};
