import { CategoryData } from './customCategoriesPart1';

export const CUSTOM_CATEGORIES_PART_6: Record<string, CategoryData[]> = {
    "Escuela y educación": [
        { civ: "Lápiz", imp: "Portaminas", hints: ["Escribir", "Grafito", "Estuche"] },
        { civ: "Bolígrafo", imp: "Pluma", hints: ["Tinta", "Escribir", "Azul"] },
        { civ: "Goma", imp: "Tippex", hints: ["Borrar", "Error", "Corregir"] },
        { civ: "Cuaderno", imp: "Libreta", hints: ["Hojas", "Escribir", "Muelle"] },
        { civ: "Folio", imp: "Cartulina", hints: ["Papel", "Blanco", "Escribir"] },
        { civ: "Libro", imp: "Enciclopedia", hints: ["Leer", "Texto", "Estudiar"] },
        { civ: "Diccionario", imp: "Traductor", hints: ["Palabras", "Significado", "Idioma"] },
        { civ: "Pizarra", imp: "Pantalla", hints: ["Clase", "Escribir", "Profesor"] },
        { civ: "Tiza", imp: "Rotulador", hints: ["Blanco", "Polvo", "Escribir"] },
        { civ: "Mochila", imp: "Cartera", hints: ["Libros", "Espalda", "Llevar"] },
        { civ: "Estuche", imp: "Neceser", hints: ["Guardar", "Lápices", "Cremallera"] },
        { civ: "Regla", imp: "Escuadra", hints: ["Medir", "Recta", "Plástico"] },
        { civ: "Compás", imp: "Transportador", hints: ["Círculo", "Grados", "Dibujo"] },
        { civ: "Sacapuntas", imp: "Cúter", hints: ["Afilar", "Punta", "Lápiz"] },
        { civ: "Pegamento", imp: "Celo", hints: ["Unir", "Barra", "Pegar"] },
        { civ: "Tijeras", imp: "Punzón", hints: ["Cortar", "Manualidades", "Papel"] },
        { civ: "Mapa", imp: "Globo", hints: ["Mundo", "Países", "Geografía"] },
        { civ: "Examen", imp: "Test", hints: ["Preguntas", "Nota", "Nervios"] },
        { civ: "Aprobar", imp: "Sacar Nota", hints: ["Éxito", "Pasar", "Bien"] },
        { civ: "Suspender", imp: "Repetir", hints: ["Mal", "Septiembre", "Fallo"] },
        { civ: "Nota", imp: "Calificación", hints: ["Número", "Boletín", "Evaluar"] },
        { civ: "Sobresaliente", imp: "Matrícula", hints: ["Diez", "Mejor", "Nota"] },
        { civ: "Notable", imp: "Bien", hints: ["Siete", "Ocho", "Nota"] },
        { civ: "Suficiente", imp: "Raspado", hints: ["Cinco", "Justo", "Aprobar"] },
        { civ: "Insuficiente", imp: "Cero", hints: ["Suspenso", "Mal", "Estudiar"] },
        { civ: "Deberes", imp: "Trabajo", hints: ["Casa", "Tarde", "Obligación"] },
        { civ: "Recreo", imp: "Patio", hints: ["Jugar", "Descanso", "Bocadillo"] },
        { civ: "Comedor", imp: "Cantina", hints: ["Comer", "Bandeja", "Mediodía"] },
        { civ: "Clase", imp: "Aula", hints: ["Sitio", "Alumnos", "Aprender"] },
        { civ: "Pasillo", imp: "Escalera", hints: ["Andar", "Cambio", "Ruido"] },
        { civ: "Pupitre", imp: "Mesa", hints: ["Sentarse", "Madera", "Alumno"] },
        { civ: "Silla", imp: "Taburete", hints: ["Sentarse", "Clase", "Mueble"] },
        { civ: "Taquilla", imp: "Perchero", hints: ["Guardar", "Cosas", "Pasillo"] },
        { civ: "Profesor", imp: "Maestro", hints: ["Enseñar", "Adulto", "Mandar"] },
        { civ: "Tutor", imp: "Orientador", hints: ["Guía", "Ayuda", "Responsable"] },
        { civ: "Director", imp: "Jefe Estudios", hints: ["Mandar", "Despacho", "Líder"] },
        { civ: "Alumno", imp: "Estudiante", hints: ["Aprender", "Joven", "Clase"] },
        { civ: "Delegado", imp: "Representante", hints: ["Votar", "Clase", "Líder"] },
        { civ: "Compañero", imp: "Amigo", hints: ["Clase", "Juntos", "Pupitre"] },
        { civ: "Matemáticas", imp: "Física", hints: ["Números", "Cuentas", "Difícil"] },
        { civ: "Lengua", imp: "Literatura", hints: ["Palabras", "Escribir", "Leer"] },
        { civ: "Historia", imp: "Geografía", hints: ["Pasado", "Fechas", "Mundo"] },
        { civ: "Inglés", imp: "Francés", hints: ["Idioma", "Hablar", "Extranjero"] },
        { civ: "Biología", imp: "Geología", hints: ["Vida", "Naturaleza", "Ciencia"] },
        { civ: "Química", imp: "Física", hints: ["Laboratorio", "Fórmulas", "Ciencia"] },
        { civ: "Música", imp: "Plástica", hints: ["Arte", "Creativo", "Asignatura"] },
        { civ: "Gimnasia", imp: "Educación Física", hints: ["Deporte", "Chándal", "Correr"] },
        { civ: "Religión", imp: "Ética", hints: ["Valores", "Creer", "Pensar"] },
        { civ: "Latín", imp: "Griego", hints: ["Antiguo", "Clásico", "Letras"] },
        { civ: "Filosofía", imp: "Psicología", hints: ["Pensar", "Mente", "Ideas"] },
        { civ: "Economía", imp: "Empresa", hints: ["Dinero", "Negocio", "Números"] },
        { civ: "Tecnología", imp: "Informática", hints: ["Ordenador", "Taller", "Futuro"] },
        { civ: "Guardería", imp: "Infantil", hints: ["Bebés", "Pequeños", "Jugar"] },
        { civ: "Primaria", imp: "Secundaria", hints: ["Niños", "Colegio", "Etapa"] },
        { civ: "Instituto", imp: "Colegio", hints: ["Adolescente", "ESO", "Centro"] },
        { civ: "Bachillerato", imp: "FP", hints: ["Mayores", "Estudios", "Título"] },
        { civ: "Universidad", imp: "Facultad", hints: ["Carrera", "Campus", "Grado"] },
        { civ: "Máster", imp: "Doctorado", hints: ["Posgrado", "Experto", "Título"] },
        { civ: "Beca", imp: "Ayuda", hints: ["Dinero", "Gratis", "Estudio"] },
        { civ: "Matrícula", imp: "Tasas", hints: ["Pagar", "Apuntarse", "Curso"] },
        { civ: "Selectividad", imp: "EBAU", hints: ["Examen", "Junio", "Entrar"] },
        { civ: "Erasmus", imp: "Intercambio", hints: ["Viaje", "Europa", "Fiesta"] },
        { civ: "Chuleta", imp: "Apuntes", hints: ["Copiar", "Esconder", "Papel"] },
        { civ: "Copiar", imp: "Chivar", hints: ["Trampa", "Examen", "Mirar"] },
        { civ: "Estudiar", imp: "Memorizar", hints: ["Aprender", "Libro", "Tiempo"] },
        { civ: "Subrayar", imp: "Resumir", hints: ["Fluorescente", "Texto", "Corto"] },
        { civ: "Esquema", imp: "Mapa", hints: ["Resumen", "Flechas", "Ideas"] },
        { civ: "Redacción", imp: "Dictado", hints: ["Escribir", "Texto", "Tema"] },
        { civ: "Pregunta", imp: "Duda", hints: ["Mano", "Saber", "Responder"] },
        { civ: "Respuesta", imp: "Solución", hints: ["Correcto", "Saber", "Resultado"] },
        { civ: "Problema", imp: "Ejercicio", hints: ["Resolver", "Matemáticas", "Dificultad"] },
        { civ: "Campana", imp: "Timbre", hints: ["Sonido", "Hora", "Fin"] },
        { civ: "Hora", imp: "Clase", hints: ["Tiempo", "Asignatura", "Reloj"] },
        { civ: "Falta", imp: "Retraso", hints: ["NoVenir", "Tarde", "Justificar"] },
        { civ: "Castigo", imp: "Parte", hints: ["Mal", "Dirección", "Expulsión"] },
        { civ: "Agenda", imp: "Horario", hints: ["Fechas", "Días", "Organizar"] },
        { civ: "Trimestre", imp: "Evaluación", hints: ["Tiempo", "Notas", "Curso"] },
        { civ: "Vacaciones", imp: "Puente", hints: ["Descanso", "NoCole", "Fiesta"] },
        { civ: "Excursión", imp: "Viaje", hints: ["Bus", "Salida", "Visita"] },
        { civ: "Graduación", imp: "Fin Curso", hints: ["Fiesta", "Diploma", "Adiós"] },
        { civ: "Uniforme", imp: "Chándal", hints: ["Ropa", "Igual", "Colegio"] },
        { civ: "Bata", imp: "Mandil", hints: ["Profesor", "Manchas", "Ropa"] },
        { civ: "Pildora", imp: "Empollón", hints: ["Estudiar", "Notas", "Gafas"] },
        { civ: "Novato", imp: "Veterano", hints: ["Nuevo", "Experiencia", "Año"] },
        { civ: "Título", imp: "Diploma", hints: ["Papel", "Fin", "Pared"] },
        { civ: "Campus", imp: "Edificio", hints: ["Universidad", "Zona", "Grande"] },
        { civ: "Tesis", imp: "TFG", hints: ["Trabajo", "Final", "Escribir"] },
        { civ: "Oposiciones", imp: "Concurso", hints: ["Examen", "Plaza", "Estudiar"] },
        { civ: "Academia", imp: "Particular", hints: ["Repaso", "Pagar", "Tarde"] },
        { civ: "Curso", imp: "Grado", hints: ["Año", "Nivel", "Clase"] },
        { civ: "Lectura", imp: "Escritura", hints: ["Libro", "Letras", "Básico"] },
        { civ: "Sumar", imp: "Restar", hints: ["Cuentas", "Básico", "Números"] },
        { civ: "Multiplicar", imp: "Dividir", hints: ["Tablas", "Cuentas", "Números"] },
        { civ: "Abecedario", imp: "Vocales", hints: ["Letras", "Orden", "A-Z"] },
        { civ: "Orla", imp: "Foto", hints: ["Recuerdo", "Clase", "Todos"] }
    ],
    "Ciencia y tecnología": [
        { civ: "Átomo", imp: "Molécula", hints: ["Pequeño", "Materia", "Partícula"] },
        { civ: "Protón", imp: "Neutrón", hints: ["Núcleo", "Positivo/Neutro", "Átomo"] },
        { civ: "Electrón", imp: "Fotón", hints: ["Carga", "Girar/Luz", "Pequeño"] },
        { civ: "Sólido", imp: "Líquido", hints: ["Estado", "Duro/Agua", "Materia"] },
        { civ: "Gas", imp: "Plasma", hints: ["Aire", "Estado", "Volátil"] },
        { civ: "Oro", imp: "Plata", hints: ["Metal", "Valioso", "Elemento"] },
        { civ: "Oxígeno", imp: "Hidrógeno", hints: ["Gas", "Aire", "Agua"] },
        { civ: "Agua", imp: "Hielo", hints: ["Líquido", "Vida", "H2O"] },
        { civ: "Luz", imp: "Sonido", hints: ["Ver/Oír", "Onda", "Rápido"] },
        { civ: "Gravedad", imp: "Magnetismo", hints: ["Fuerza", "Atraer", "Tierra/Imán"] },
        { civ: "Electricidad", imp: "Corriente", hints: ["Energía", "Cable", "Luz"] },
        { civ: "Pila", imp: "Batería", hints: ["Energía", "Carga", "Portátil"] },
        { civ: "Imán", imp: "Metal", hints: ["Pegar", "Hierro", "Atraer"] },
        { civ: "Hardware", imp: "Software", hints: ["Ordenador", "Físico/Lógico", "Tocar"] },
        { civ: "Código", imp: "Algoritmo", hints: ["Programar", "Lenguaje", "Instrucciones"] },
        { civ: "Bit", imp: "Byte", hints: ["Dato", "Cero/Uno", "Información"] },
        { civ: "Virus", imp: "Bug", hints: ["Infección", "Error", "Ordenador"] },
        { civ: "Robot", imp: "Androide", hints: ["Máquina", "Humano", "Futuro"] },
        { civ: "Inteligencia Artificial", imp: "Humano", hints: ["Máquina", "Pensar", "Futuro"] },
        { civ: "ADN", imp: "Gen", hints: ["Vida", "Código", "Herencia"] },
        { civ: "Célula", imp: "Bacteria", hints: ["Vida", "Pequeño", "Microscopio"] },
        { civ: "Virus", imp: "Bacteria", hints: ["Enfermedad", "Microbio", "Contagio"] },
        { civ: "Vacuna", imp: "Antibiótico", hints: ["Curar", "Inyección", "Medicina"] },
        { civ: "Sangre", imp: "Plasma", hints: ["Rojo", "Cuerpo", "Líquido"] },
        { civ: "Corazón", imp: "Cerebro", hints: ["Órgano", "Vida", "Latir/Pensar"] },
        { civ: "Hueso", imp: "Músculo", hints: ["Esqueleto", "Fuerza", "Cuerpo"] },
        { civ: "Telescopio", imp: "Microscopio", hints: ["Lente", "Ver", "Lejos/Cerca"] },
        { civ: "Estrella", imp: "Planeta", hints: ["Espacio", "Luz", "Cielo"] },
        { civ: "Sol", imp: "Luna", hints: ["Cielo", "Día/Noche", "Brillo"] },
        { civ: "Tierra", imp: "Marte", hints: ["Planeta", "Vida", "Mundo"] },
        { civ: "Galaxia", imp: "Universo", hints: ["Espacio", "Estrellas", "Inmenso"] },
        { civ: "Agujero Negro", imp: "Supernova", hints: ["Espacio", "Gravedad/Explosión", "Oscuro"] },
        { civ: "Cohete", imp: "Satélite", hints: ["Espacio", "Volar", "Tecnología"] },
        { civ: "Astronauta", imp: "Alien", hints: ["Espacio", "Persona/Bicho", "Viaje"] },
        { civ: "Eclipse", imp: "Fase", hints: ["Sol/Luna", "Tapar", "Sombra"] },
        { civ: "Tiempo", imp: "Espacio", hints: ["Reloj", "Dimensiones", "Relativo"] },
        { civ: "Reloj", imp: "Cronómetro", hints: ["Hora", "Medir", "Tiempo"] },
        { civ: "Termómetro", imp: "Barómetro", hints: ["Temperatura", "Presión", "Medir"] },
        { civ: "Brújula", imp: "GPS", hints: ["Norte", "Mapa", "Orientar"] },
        { civ: "Láser", imp: "Rayo", hints: ["Luz", "Recto", "Potencia"] },
        { civ: "Nuclear", imp: "Solar", hints: ["Energía", "Planta", "Potencia"] },
        { civ: "Petróleo", imp: "Gasolina", hints: ["Combustible", "Negro", "Coche"] },
        { civ: "Plástico", imp: "Metal", hints: ["Material", "Envase", "Duro"] },
        { civ: "Reciclar", imp: "Reutilizar", hints: ["Basura", "Planeta", "Verde"] },
        { civ: "Volcán", imp: "Terremoto", hints: ["Desastre", "Lava/Suelo", "Fuerza"] },
        { civ: "Huracán", imp: "Tornado", hints: ["Viento", "Girar", "Tormenta"] },
        { civ: "Rayo", imp: "Trueno", hints: ["Tormenta", "Luz/Sonido", "Cielo"] },
        { civ: "Nube", imp: "Niebla", hints: ["Agua", "Blanco", "Cielo"] },
        { civ: "Arcoíris", imp: "Prisma", hints: ["Colores", "Luz", "Cielo"] },
        { civ: "Cámara", imp: "Ojo", hints: ["Ver", "Lente", "Imagen"] },
        { civ: "Foto", imp: "Píxel", hints: ["Imagen", "Recuerdo", "Pantalla"] },
        { civ: "Pantalla", imp: "Monitor", hints: ["Ver", "Imagen", "Ordenador"] },
        { civ: "Teclado", imp: "Ratón", hints: ["Escribir", "Mover", "Entrada"] },
        { civ: "Impresora", imp: "Escáner", hints: ["Papel", "Copiar", "Máquina"] },
        { civ: "Wifi", imp: "Bluetooth", hints: ["Inalámbrico", "Conexión", "Invisible"] },
        { civ: "USB", imp: "Disco Duro", hints: ["Guardar", "Datos", "Memoria"] },
        { civ: "Nube", imp: "Servidor", hints: ["Internet", "Guardar", "Datos"] },
        { civ: "Email", imp: "Chat", hints: ["Mensaje", "Escribir", "Enviar"] },
        { civ: "Google", imp: "Siri", hints: ["Buscar", "Asistente", "Preguntar"] },
        { civ: "Windows", imp: "Linux", hints: ["Sistema", "PC", "Software"] },
        { civ: "iPhone", imp: "Android", hints: ["Móvil", "Marca", "Teléfono"] },
        { civ: "PC", imp: "Mac", hints: ["Ordenador", "Escritorio", "Trabajo"] },
        { civ: "Tablet", imp: "iPad", hints: ["Pantalla", "Táctil", "Dispositivo"] },
        { civ: "Consola", imp: "PC Gamer", hints: ["Jugar", "Videojuegos", "Mando"] },
        { civ: "Realidad Virtual", imp: "3D", hints: ["Gafas", "Inmersión", "Ver"] },
        { civ: "Dron", imp: "Avión", hints: ["Volar", "Cámara", "Control"] },
        { civ: "Coche Eléctrico", imp: "Híbrido", hints: ["Motor", "Batería", "Enchufe"] },
        { civ: "Motor", imp: "Batería", hints: ["Energía", "Coche", "Movimiento"] },
        { civ: "Velocidad", imp: "Aceleración", hints: ["Rápido", "Física", "Coche"] },
        { civ: "Fuerza", imp: "Potencia", hints: ["Física", "Empujar", "Energía"] },
        { civ: "Masa", imp: "Peso", hints: ["Kilos", "Cuerpo", "Gravedad"] },
        { civ: "Laboratorio", imp: "Taller", hints: ["Ciencia", "Experimento", "Trabajo"] },
        { civ: "Bata", imp: "Uniforme", hints: ["Blanca", "Científico", "Ropa"] },
        { civ: "Pipeta", imp: "Probeta", hints: ["Líquido", "Medir", "Cristal"] },
        { civ: "Fórmula", imp: "Ecuación", hints: ["Matemática", "Pizarra", "Resolver"] },
        { civ: "Hipótesis", imp: "Teoría", hints: ["Idea", "Ciencia", "Comprobar"] },
        { civ: "Experimento", imp: "Prueba", hints: ["Hacer", "Resultado", "Ciencia"] },
        { civ: "Dinosaurio", imp: "Fósil", hints: ["Antiguo", "Huesos", "Extinto"] },
        { civ: "Evolución", imp: "Creación", hints: ["Cambio", "Darwin", "Especie"] },
        { civ: "Clon", imp: "Gemelo", hints: ["Igual", "Copia", "ADN"] },
        { civ: "Mutación", imp: "Cambio", hints: ["ADN", "X-Men", "Raro"] },
        { civ: "Invento", imp: "Descubrimiento", hints: ["Nuevo", "Crear", "Idea"] },
        { civ: "Patente", imp: "Marca", hints: ["Registro", "Idea", "Proteger"] },
        { civ: "Fibra", imp: "ADSL", hints: ["Internet", "Cable", "Rápido"] },
        { civ: "Antena", imp: "Satélite", hints: ["Señal", "Tejado", "Recibir"] },
        { civ: "Mando", imp: "Botón", hints: ["Control", "Pulsar", "Tele"] },
        { civ: "Enchufe", imp: "Cable", hints: ["Pared", "Luz", "Conectar"] }
    ],
    "Deportes": [
        { civ: "Fútbol", imp: "Fútbol Sala", hints: ["Balón", "Gol", "Equipo"] },
        { civ: "Baloncesto", imp: "Balonmano", hints: ["Mano", "Canasta/Portería", "Pelota"] },
        { civ: "Tenis", imp: "Pádel", hints: ["Raqueta", "Red", "Pelota"] },
        { civ: "Ping Pong", imp: "Bádminton", hints: ["Mesa/Aire", "Raqueta", "Red"] },
        { civ: "Golf", imp: "Minigolf", hints: ["Palo", "Hoyo", "Hierba"] },
        { civ: "Voleibol", imp: "Voley Playa", hints: ["Red", "Mano", "Salto"] },
        { civ: "Rugby", imp: "Fútbol Americano", hints: ["Placaje", "Balón", "Contacto"] },
        { civ: "Béisbol", imp: "Cricket", hints: ["Bate", "Golpear", "Carrera"] },
        { civ: "Hockey", imp: "Patinaje", hints: ["Hielo", "Stick", "Deslizar"] },
        { civ: "Esquí", imp: "Snowboard", hints: ["Nieve", "Montaña", "Bajar"] },
        { civ: "Surf", imp: "Windsurf", hints: ["Mar", "Olas", "Tabla"] },
        { civ: "Natación", imp: "Waterpolo", hints: ["Agua", "Piscina", "Nadar"] },
        { civ: "Atletismo", imp: "Maratón", hints: ["Correr", "Pista", "Cansancio"] },
        { civ: "Salto", imp: "Lanzamiento", hints: ["Aire", "Lejos", "Atletismo"] },
        { civ: "Jabalina", imp: "Martillo", hints: ["Lanzar", "Lejos", "Objeto"] },
        { civ: "Gimnasia", imp: "Baile", hints: ["Flexible", "Música", "Movimiento"] },
        { civ: "Yoga", imp: "Pilates", hints: ["Suelo", "Estirar", "Relax"] },
        { civ: "Boxeo", imp: "Karate", hints: ["Golpes", "Lucha", "Ring/Tatami"] },
        { civ: "Judo", imp: "Taekwondo", hints: ["Cinturón", "Kimono", "Arte Marcial"] },
        { civ: "Lucha", imp: "Sumo", hints: ["Agarrar", "Fuerza", "Suelo"] },
        { civ: "Esgrima", imp: "Espada", hints: ["Arma", "Tocar", "Blanco"] },
        { civ: "Ciclismo", imp: "Spinning", hints: ["Bici", "Pedales", "Ruedas"] },
        { civ: "Moto", imp: "Fórmula 1", hints: ["Motor", "Carrera", "Circuito"] },
        { civ: "Rally", imp: "Karting", hints: ["Coche", "Derrape", "Carrera"] },
        { civ: "Hípica", imp: "Polo", hints: ["Caballo", "Saltar", "Montar"] },
        { civ: "Escalada", imp: "Alpinismo", hints: ["Subir", "Montaña", "Cuerda"] },
        { civ: "Pesca", imp: "Caza", hints: ["Animal", "Paciencia", "Caña/Escopeta"] },
        { civ: "Tiro con Arco", imp: "Dardos", hints: ["Puntería", "Diana", "Flecha"] },
        { civ: "Bolos", imp: "Petanca", hints: ["Bola", "Tirar", "Suelo"] },
        { civ: "Billar", imp: "Snooker", hints: ["Mesa", "Taco", "Bolas"] },
        { civ: "Ajedrez", imp: "Damas", hints: ["Tablero", "Piezas", "Pensar"] },
        { civ: "Póker", imp: "Mus", hints: ["Cartas", "Apuesta", "Juego"] },
        { civ: "eSports", imp: "Videojuegos", hints: ["Pantalla", "Competir", "Mando"] },
        { civ: "Árbitro", imp: "Juez", hints: ["Silbato", "Normas", "Tarjeta"] },
        { civ: "Entrenador", imp: "Míster", hints: ["Banquillo", "Estrategia", "Mandar"] },
        { civ: "Jugador", imp: "Suplente", hints: ["Equipo", "Campo", "Jugar"] },
        { civ: "Capitán", imp: "Líder", hints: ["Brazalete", "Mandar", "Equipo"] },
        { civ: "Portero", imp: "Delantero", hints: ["Gol", "Parar/Meter", "Posición"] },
        { civ: "Defensa", imp: "Centrocampista", hints: ["Proteger", "Pase", "Campo"] },
        { civ: "Gol", imp: "Canasta", hints: ["Punto", "Red", "Marcar"] },
        { civ: "Partido", imp: "Prórroga", hints: ["Jugar", "Tiempo", "Resultado"] },
        { civ: "Penalti", imp: "Falta", hints: ["Castigo", "Tiro", "Árbitro"] },
        { civ: "Tarjeta Roja", imp: "Amarilla", hints: ["Expulsión", "Aviso", "Color"] },
        { civ: "Banquillo", imp: "Grada", hints: ["Sentado", "Campo", "Ver"] },
        { civ: "Estadio", imp: "Pabellón", hints: ["Público", "Grande", "Deporte"] },
        { civ: "Campo", imp: "Pista", hints: ["Suelo", "Jugar", "Líneas"] },
        { civ: "Ring", imp: "Tatami", hints: ["Lucha", "Cuadrado", "Suelo"] },
        { civ: "Balón", imp: "Pelota", hints: ["Redondo", "Juego", "Deporte"] },
        { civ: "Raqueta", imp: "Pala", hints: ["Mano", "Golpear", "Red"] },
        { civ: "Bate", imp: "Palo", hints: ["Golpear", "Madera/Metal", "Juego"] },
        { civ: "Casco", imp: "Guante", hints: ["Protección", "Cabeza/Mano", "Seguridad"] },
        { civ: "Camiseta", imp: "Dorsal", hints: ["Equipo", "Número", "Ropa"] },
        { civ: "Botas", imp: "Zapatillas", hints: ["Pies", "Tacos/Suela", "Correr"] },
        { civ: "Trofeo", imp: "Copa", hints: ["Premio", "Ganar", "Metal"] },
        { civ: "Medalla", imp: "Diploma", hints: ["Cuello", "Ganar", "Olimpiada"] },
        { civ: "Oro", imp: "Plata", hints: ["Primero", "Segundo", "Metal"] },
        { civ: "Ganar", imp: "Perder", hints: ["Resultado", "Campeón", "Final"] },
        { civ: "Empate", imp: "Tablas", hints: ["Igual", "Puntos", "Resultado"] },
        { civ: "Récord", imp: "Marca", hints: ["Mejor", "Historia", "Superar"] },
        { civ: "Dopaje", imp: "Trampa", hints: ["Prohibido", "Droga", "Descalificado"] },
        { civ: "Fair Play", imp: "Deportividad", hints: ["Respeto", "Juego", "Bueno"] },
        { civ: "Afición", imp: "Hooligan", hints: ["Animar", "Equipo", "Grada"] },
        { civ: "Ola", imp: "Cántico", hints: ["Público", "Movimiento", "Estadio"] },
        { civ: "Himno", imp: "Bandera", hints: ["País", "Equipo", "Honor"] },
        { civ: "Olimpiadas", imp: "Mundial", hints: ["Evento", "Países", "4Años"] },
        { civ: "Eurocopa", imp: "Liga", hints: ["Fútbol", "Torneo", "Europa"] },
        { civ: "Champions", imp: "Copa del Rey", hints: ["Trofeo", "Fútbol", "Clubes"] },
        { civ: "NBA", imp: "ACB", hints: ["Basket", "Liga", "EEUU/España"] },
        { civ: "Tour", imp: "Vuelta", hints: ["Bici", "Francia/España", "Etapas"] },
        { civ: "Meta", imp: "Salida", hints: ["Fin", "Principio", "Carrera"] },
        { civ: "Podio", imp: "Cajón", hints: ["Ganadores", "Tres", "Altura"] },
        { civ: "Crono", imp: "Tiempo", hints: ["Reloj", "Rápido", "Medir"] },
        { civ: "VAR", imp: "Ojo de Halcón", hints: ["Cámara", "Revisar", "Árbitro"] },
        { civ: "Directo", imp: "Repetición", hints: ["TV", "Ahora", "Ver"] },
        { civ: "Marca", imp: "As", hints: ["Periódico", "Deporte", "Leer"] },
        { civ: "Fichaje", imp: "Traspaso", hints: ["Dinero", "Cambio", "Equipo"] },
        { civ: "Cantera", imp: "Filial", hints: ["Jóvenes", "Equipo", "Futuro"] },
        { civ: "Profesional", imp: "Amateur", hints: ["Cobrar", "Hobby", "Nivel"] },
        { civ: "Lesión", imp: "Agujetas", hints: ["Dolor", "Baja", "Músculo"] },
        { civ: "Fisio", imp: "Masajista", hints: ["Curar", "Músculo", "Camilla"] },
        { civ: "Calentar", imp: "Estirar", hints: ["Antes", "Ejercicio", "Preparar"] },
        { civ: "Sudar", imp: "Cansar", hints: ["Esfuerzo", "Agua", "Cuerpo"] },
        { civ: "Agua", imp: "Isotónica", hints: ["Beber", "Sed", "Botella"] },
        { civ: "Toalla", imp: "Ducha", hints: ["Secar", "Limpiar", "Vestuario"] },
        { civ: "Vestuario", imp: "Taquilla", hints: ["Ropa", "Equipo", "Cambio"] },
        { civ: "CrossFit", imp: "Pesas", hints: ["Gimnasio", "Fuerza", "Duro"] },
        { civ: "Correr", imp: "Andar", hints: ["Pies", "Prisa", "Deporte"] },
        { civ: "Saltar", imp: "Volar", hints: ["Arriba", "Aire", "Suelo"] }
    ]
};
