export interface CategoryData {
    civ: string;   // Palabra Civil
    imp: string;   // Palabra Impostor
    hints: string[]; // Array de 3 pistas (CADA UNA DE 1 SOLA PALABRA)
}

export const CUSTOM_CATEGORIES_PART_1: Record<string, CategoryData[]> = {
    "Objetos cotidianos": [
        { civ: "Bolígrafo", imp: "Rotulador", hints: ["Tinta", "Escribir", "Papel"] },
        { civ: "Silla", imp: "Taburete", hints: ["Sentarse", "Mueble", "Patas"] },
        { civ: "Vaso", imp: "Copa", hints: ["Beber", "Cristal", "Líquido"] },
        { civ: "Cuchara", imp: "Tenedor", hints: ["Cubierto", "Comer", "Metal"] },
        { civ: "Bufanda", imp: "Pañuelo", hints: ["Cuello", "Abrigo", "Tela"] },
        { civ: "Mochila", imp: "Maleta", hints: ["Equipaje", "Transporte", "Guardar"] },
        { civ: "Reloj", imp: "Pulsera", hints: ["Muñeca", "Accesorio", "Mano"] },
        { civ: "Lámpara", imp: "Linterna", hints: ["Luz", "Bombilla", "Oscuridad"] },
        { civ: "Libro", imp: "Revista", hints: ["Leer", "Papel", "Páginas"] },
        { civ: "Zapato", imp: "Zapatilla", hints: ["Pie", "Calzado", "Andar"] },
        { civ: "Guante", imp: "Manopla", hints: ["Mano", "Frío", "Invierno"] },
        { civ: "Cama", imp: "Sofá", hints: ["Dormir", "Descanso", "Mueble"] },
        { civ: "Champú", imp: "Gel", hints: ["Ducha", "Jabón", "Baño"] },
        { civ: "Peine", imp: "Cepillo", hints: ["Pelo", "Peinar", "Cabeza"] },
        { civ: "Gafas", imp: "Lentillas", hints: ["Vista", "Ojos", "Ver"] },
        { civ: "Teclado", imp: "Ratón", hints: ["Ordenador", "Escribir", "Click"] },
        { civ: "Móvil", imp: "Tablet", hints: ["Pantalla", "Dispositivo", "Llamar"] },
        { civ: "Ventana", imp: "Puerta", hints: ["Abrir", "Casa", "Cristal"] },
        { civ: "Cortina", imp: "Persiana", hints: ["Ventana", "Luz", "Tapar"] },
        { civ: "Sábana", imp: "Manta", hints: ["Cama", "Dormir", "Tapar"] },
        { civ: "Cuaderno", imp: "Agenda", hints: ["Escribir", "Papel", "Notas"] },
        { civ: "Lápiz", imp: "Portaminas", hints: ["Grafito", "Escribir", "Borrar"] },
        { civ: "Goma", imp: "Sacapuntas", hints: ["Estuche", "Lápiz", "Escuela"] },
        { civ: "Carpeta", imp: "Archivador", hints: ["Papeles", "Guardar", "Orden"] },
        { civ: "Taza", imp: "Tazón", hints: ["Desayuno", "Asa", "Café"] },
        { civ: "Plato", imp: "Cuenco", hints: ["Comida", "Mesa", "Vajilla"] },
        { civ: "Sartén", imp: "Olla", hints: ["Cocina", "Fuego", "Cocinar"] },
        { civ: "Cuchillo", imp: "Navaja", hints: ["Cortar", "Filo", "Metal"] },
        { civ: "Tijeras", imp: "Cúter", hints: ["Cortar", "Papel", "Manualidad"] },
        { civ: "Ciso", imp: "Baldosa", hints: ["Suelo", "Pisada", "Casa"] },
        { civ: "Techo", imp: "Tejado", hints: ["Arriba", "Casa", "Cubrir"] },
        { civ: "Pared", imp: "Muro", hints: ["Separar", "Ladrillo", "Vertical"] },
        { civ: "Llave", imp: "Tarjeta", hints: ["Abrir", "Puerta", "Acceso"] },
        { civ: "Candado", imp: "Cerradura", hints: ["Seguridad", "Cerrar", "Llave"] },
        { civ: "Moneda", imp: "Billete", hints: ["Dinero", "Pagar", "Cartera"] },
        { civ: "Cartera", imp: "Monedero", hints: ["Dinero", "Bolsillo", "Guardar"] },
        { civ: "Bolso", imp: "Riñonera", hints: ["Llevar", "Guardar", "Accesorio"] },
        { civ: "Abrigo", imp: "Chaqueta", hints: ["Frío", "Ropa", "Invierno"] },
        { civ: "Camisa", imp: "Camiseta", hints: ["Ropa", "Torso", "Vestir"] },
        { civ: "Pantalón", imp: "Bermuda", hints: ["Piernas", "Ropa", "Vestir"] },
        { civ: "Calcetín", imp: "Media", hints: ["Pie", "Ropa", "Tejido"] },
        { civ: "Corbata", imp: "Pajarita", hints: ["Cuello", "Traje", "Elegante"] },
        { civ: "Sombrero", imp: "Gorra", hints: ["Cabeza", "Sol", "Accesorio"] },
        { civ: "Paraguas", imp: "Chubasquero", hints: ["Lluvia", "Agua", "Mojarse"] },
        { civ: "Espejo", imp: "Cristal", hints: ["Reflejo", "Mirar", "Imagen"] },
        { civ: "Toalla", imp: "Albornoz", hints: ["Secar", "Baño", "Agua"] },
        { civ: "Jabón", imp: "Desinfectante", hints: ["Lavar", "Manos", "Limpio"] },
        { civ: "Colonia", imp: "Perfume", hints: ["Olor", "Aroma", "Cuello"] },
        { civ: "Maquillaje", imp: "Pintura", hints: ["Cara", "Color", "Estética"] },
        { civ: "Anillo", imp: "Alianza", hints: ["Dedo", "Joya", "Redondo"] },
        { civ: "Collar", imp: "Gargantilla", hints: ["Cuello", "Joya", "Colgar"] },
        { civ: "Pendiente", imp: "Piercing", hints: ["Oreja", "Joya", "Agujero"] },
        { civ: "Botella", imp: "Jarra", hints: ["Líquido", "Recipiente", "Beber"] },
        { civ: "Lata", imp: "Brik", hints: ["Envase", "Bebida", "Metal/Cartón"] },
        { civ: "Tapón", imp: "Chapa", hints: ["Cerrar", "Botella", "Abrir"] },
        { civ: "Servilleta", imp: "Mantel", hints: ["Limpiar", "Mesa", "Comer"] },
        { civ: "Escoba", imp: "Fregona", hints: ["Suelo", "Limpiar", "Palo"] },
        { civ: "Cubo", imp: "Barreño", hints: ["Agua", "Plástico", "Recipiente"] },
        { civ: "Plancha", imp: "Vaporeta", hints: ["Ropa", "Calor", "Alisar"] },
        { civ: "Lavadora", imp: "Secadora", hints: ["Ropa", "Limpiar", "Electrodoméstico"] },
        { civ: "Horno", imp: "Microondas", hints: ["Calentar", "Cocina", "Comida"] },
        { civ: "Nevera", imp: "Congelador", hints: ["Frío", "Conservar", "Alimentos"] },
        { civ: "Batidora", imp: "Licuadora", hints: ["Triturar", "Cocina", "Mezclar"] },
        { civ: "Tostadora", imp: "Sandwichera", hints: ["Pan", "Caliente", "Desayuno"] },
        { civ: "Cafetera", imp: "Tetera", hints: ["Bebida", "Caliente", "Desayuno"] },
        { civ: "Radio", imp: "Altavoz", hints: ["Sonido", "Escuchar", "Música"] },
        { civ: "Mando", imp: "Joystick", hints: ["Control", "Botones", "Mano"] },
        { civ: "Pila", imp: "Batería", hints: ["Energía", "Electricidad", "Carga"] },
        { civ: "Cable", imp: "Cuerda", hints: ["Largo", "Conectar/Atar", "Fino"] },
        { civ: "Enchufe", imp: "Interruptor", hints: ["Pared", "Electricidad", "Luz"] },
        { civ: "Martillo", imp: "Maza", hints: ["Golpear", "Clavo", "Herramienta"] },
        { civ: "Destornillador", imp: "Taladro", hints: ["Girar", "Tornillo", "Bricolaje"] },
        { civ: "Sierra", imp: "Serrucho", hints: ["Cortar", "Madera", "Dientes"] },
        { civ: "Escalera", imp: "Taburete", hints: ["Subir", "Alto", "Peldaños"] },
        { civ: "Grifo", imp: "Manguera", hints: ["Agua", "Abrir", "Jardín/Baño"] },
        { civ: "Maceta", imp: "Jarrón", hints: ["Planta", "Flores", "Tierra"] },
        { civ: "Cuadro", imp: "Póster", hints: ["Pared", "Arte", "Decoración"] },
        { civ: "Estatua", imp: "Figura", hints: ["Escultura", "Arte", "Forma"] },
        { civ: "Alfombra", imp: "Felpudo", hints: ["Suelo", "Tejido", "Pisada"] },
        { civ: "Cojín", imp: "Almohada", hints: ["Blando", "Sofá/Cama", "Apoyar"] },
        { civ: "Vela", imp: "Incienso", hints: ["Fuego", "Olor", "Cera"] },
        { civ: "Mechero", imp: "Cerilla", hints: ["Fuego", "Encender", "Llama"] },
        { civ: "Cenicero", imp: "Papelera", hints: ["Basura", "Depositar", "Residuos"] },
        { civ: "Bolsa", imp: "Saco", hints: ["Guardar", "Transportar", "Plástico/Tela"] },
        { civ: "Caja", imp: "Estuche", hints: ["Guardar", "Cartón", "Cerrar"] },
        { civ: "Sobre", imp: "Paquete", hints: ["Carta", "Correo", "Enviar"] },
        { civ: "Sello", imp: "Pegatina", hints: ["Pegar", "Papel", "Imagen"] },
        { civ: "Mapa", imp: "Plano", hints: ["Lugar", "Papel", "Guiarse"] },
        { civ: "Brújula", imp: "GPS", hints: ["Norte", "Orientación", "Dirección"] },
        { civ: "Prismáticos", imp: "Telescopio", hints: ["Ver", "Lejos", "Lentes"] },
        { civ: "Cámara", imp: "Móvil", hints: ["Foto", "Imagen", "Capturar"] },
        { civ: "Trípode", imp: "Soporte", hints: ["Sujetar", "Cámara", "Estable"] },
        { civ: "Guitarra", imp: "Ukelele", hints: ["Cuerdas", "Música", "Instrumento"] },
        { civ: "Piano", imp: "Teclado", hints: ["Teclas", "Música", "Tocar"] },
        { civ: "Violín", imp: "Viola", hints: ["Arco", "Cuerdas", "Música"] },
        { civ: "Tambor", imp: "Batería", hints: ["Golpear", "Ritmo", "Percusión"] },
        { civ: "Flauta", imp: "Clarinete", hints: ["Viento", "Soplar", "Música"] },
        { civ: "Micrófono", imp: "Megáfono", hints: ["Voz", "Sonido", "Hablar"] },
        { civ: "Auriculares", imp: "Cascos", hints: ["Oído", "Escuchar", "Música"] },
    ],
    "Personas famosas": [
        { civ: "Picasso", imp: "Dalí", hints: ["Pintor", "España", "Arte"] },
        { civ: "Messi", imp: "Cristiano", hints: ["Fútbol", "Balón", "Gol"] },
        { civ: "Nadal", imp: "Federer", hints: ["Tenis", "Raqueta", "Deporte"] },
        { civ: "Shakira", imp: "Rosalía", hints: ["Cantante", "Música", "Baile"] },
        { civ: "Cervantes", imp: "Shakespeare", hints: ["Escritor", "Libros", "Clásico"] },
        { civ: "Batman", imp: "Superman", hints: ["Héroe", "Cómic", "Capa"] },
        { civ: "Mario", imp: "Luigi", hints: ["Juego", "Nintendo", "Fontanero"] },
        { civ: "Jobs", imp: "Gates", hints: ["Tecnología", "Informática", "Millonario"] },
        { civ: "Einstein", imp: "Newton", hints: ["Ciencia", "Física", "Genio"] },
        { civ: "Colón", imp: "Magallanes", hints: ["Barco", "Viaje", "Descubridor"] },
        { civ: "Cleopatra", imp: "Nefertiti", hints: ["Egipto", "Reina", "Historia"] },
        { civ: "Brad Pitt", imp: "DiCaprio", hints: ["Actor", "Hollywood", "Cine"] },
        { civ: "Penélope", imp: "Salma", hints: ["Actriz", "Cine", "Morena"] },
        { civ: "Alonso", imp: "Sainz", hints: ["Coches", "Piloto", "España"] },
        { civ: "Gasol", imp: "Jordan", hints: ["Baloncesto", "Altura", "Canasta"] },
        { civ: "Mozart", imp: "Beethoven", hints: ["Música", "Piano", "Clásico"] },
        { civ: "Velázquez", imp: "Goya", hints: ["Pintor", "Museo", "Cuadros"] },
        { civ: "Lorca", imp: "Machado", hints: ["Poeta", "Versos", "España"] },
        { civ: "Gandalf", imp: "Dumbledore", hints: ["Mago", "Barba", "Película"] },
        { civ: "Frodo", imp: "Harry Potter", hints: ["Protagonista", "Saga", "Aventura"] },
        { civ: "Beyoncé", imp: "Rihanna", hints: ["Diva", "Pop", "Cantante"] },
        { civ: "Eminem", imp: "Snoop Dogg", hints: ["Rap", "Música", "EEUU"] },
        { civ: "Trump", imp: "Biden", hints: ["Presidente", "Política", "USA"] },
        { civ: "Sánchez", imp: "Feijóo", hints: ["Política", "España", "Gobierno"] },
        { civ: "Ibaye", imp: "Rubius", hints: ["Streamer", "Internet", "Youtube"] },
        { civ: "Zuckerberg", imp: "Musk", hints: ["Redes", "Tech", "Dueño"] },
        { civ: "Mickey", imp: "Donald", hints: ["Disney", "Dibujos", "Animal"] },
        { civ: "Simpson", imp: "Griffin", hints: ["Familia", "Animación", "Padre"] },
        { civ: "Goku", imp: "Naruto", hints: ["Anime", "Lucha", "Poderes"] },
        { civ: "Pikachu", imp: "Charmander", hints: ["Pokémon", "Bicho", "Evolución"] },
        { civ: "Spiderman", imp: "Ironman", hints: ["Marvel", "Vengador", "Película"] },
        { civ: "Joker", imp: "Thanos", hints: ["Villano", "Malo", "Enemigo"] },
        { civ: "Sherlock", imp: "Poirot", hints: ["Detective", "Investigar", "Crimen"] },
        { civ: "Drácula", imp: "Frankenstein", hints: ["Monstruo", "Miedo", "Terror"] },
        { civ: "Tarzán", imp: "Mowgli", hints: ["Selva", "Niño", "Animales"] },
        { civ: "Barbie", imp: "Nancy", hints: ["Muñeca", "Juguete", "Rubia"] },
        { civ: "Bond", imp: "Bourne", hints: ["Espía", "Acción", "Agente"] },
        { civ: "Rocky", imp: "Rambo", hints: ["Stallone", "Lucha", "Película"] },
        { civ: "Terminator", imp: "Robocop", hints: ["Robot", "Futuro", "Disparos"] },
        { civ: "Yoda", imp: "Vader", hints: ["StarWars", "Fuerza", "Espacio"] },
        { civ: "Jesús", imp: "Buda", hints: ["Religión", "Dios", "Creencia"] },
        { civ: "Papa", imp: "Rey", hints: ["Líder", "Corona/Mitra", "Poder"] },
        { civ: "Letizia", imp: "Sofía", hints: ["Reina", "España", "Monarquía"] },
        { civ: "Diana", imp: "Kate", hints: ["Princesa", "Inglaterra", "Royal"] },
        { civ: "Marilyn", imp: "Audrey", hints: ["Icono", "Cine", "Antiguo"] },
        { civ: "Elvis", imp: "Jackson", hints: ["Rey", "Música", "Baile"] },
        { civ: "Beatles", imp: "Stones", hints: ["Banda", "Rock", "Ingleses"] },
        { civ: "Queen", imp: "ABBA", hints: ["Grupo", "Canciones", "Famosos"] },
        { civ: "Almodóvar", imp: "Amenábar", hints: ["Director", "Cine", "Español"] },
        { civ: "Spielberg", imp: "Tarantino", hints: ["Director", "Películas", "Cine"] },
        { civ: "Banderas", imp: "Bardem", hints: ["Actor", "Español", "Internacional"] },
        { civ: "Casillas", imp: "Ramos", hints: ["Fútbol", "Madrid", "Selección"] },
        { civ: "Iniesta", imp: "Xavi", hints: ["Fútbol", "Barça", "Campo"] },
        { civ: "Maradona", imp: "Pelé", hints: ["Leyenda", "Fútbol", "10"] },
        { civ: "Bolt", imp: "Phelps", hints: ["Olimpiadas", "Récord", "Medalla"] },
        { civ: "Armstrong", imp: "Aldrin", hints: ["Luna", "Espacio", "Astronauta"] },
        { civ: "Curie", imp: "Darwin", hints: ["Ciencia", "Descubrimiento", "Estudio"] },
        { civ: "Da Vinci", imp: "Miguel Ángel", hints: ["Renacimiento", "Artista", "Italia"] },
        { civ: "Van Gogh", imp: "Monet", hints: ["Pintura", "Colores", "Arte"] },
        { civ: "Frida", imp: "Chavela", hints: ["México", "Arte", "Mujer"] },
        { civ: "Garfield", imp: "Snoopy", hints: ["Perro/Gato", "Cómic", "Dibujo"] },
        { civ: "Tom", imp: "Jerry", hints: ["Persecución", "Animales", "Dibujos"] },
        { civ: "Pedro", imp: "Pablo", hints: ["Picapiedra", "Nombres", "Amigos"] },
        { civ: "Astérix", imp: "Obélix", hints: ["Galo", "Cómic", "Roma"] },
        { civ: "Tintín", imp: "Milú", hints: ["Cómic", "Investigar", "Perro"] },
        { civ: "Mafalda", imp: "Susanita", hints: ["Niña", "Cómic", "Argentina"] },
        { civ: "Doraemon", imp: "Nobita", hints: ["Gato", "Japón", "Bolsillo"] },
        { civ: "Heidi", imp: "Marco", hints: ["Dibujos", "Antiguo", "Niños"] },
        { civ: "Zelda", imp: "Link", hints: ["Videojuego", "Princesa", "Espada"] },
        { civ: "Sonic", imp: "Tails", hints: ["Erizo", "Rápido", "Sega"] },
        { civ: "Pacman", imp: "Fantasma", hints: ["Comer", "Juego", "Laberinto"] },
        { civ: "Ryu", imp: "Ken", hints: ["Lucha", "StreetFighter", "Karate"] },
        { civ: "Kratos", imp: "Dante", hints: ["Acción", "Juego", "Matar"] },
        { civ: "Lara Croft", imp: "Nathan Drake", hints: ["Tesoros", "Aventura", "Juego"] },
        { civ: "Siri", imp: "Alexa", hints: ["Voz", "Asistente", "Robot"] },
        { civ: "Google", imp: "Yahoo", hints: ["Buscar", "Internet", "Web"] },
        { civ: "Amazon", imp: "AliExpress", hints: ["Comprar", "Online", "Paquete"] },
        { civ: "Netflix", imp: "HBO", hints: ["Series", "Streaming", "Ver"] },
        { civ: "Spotify", imp: "Youtube", hints: ["Música", "Escuchar", "App"] },
        { civ: "Instagram", imp: "TikTok", hints: ["Fotos/Vídeo", "Móvil", "Social"] },
        { civ: "Whatsapp", imp: "Telegram", hints: ["Chat", "Mensajes", "Móvil"] },
        { civ: "Windows", imp: "Mac", hints: ["Sistema", "Ordenador", "OS"] },
        { civ: "Android", imp: "iOS", hints: ["Móvil", "Sistema", "Teléfono"] },
        { civ: "PlayStation", imp: "Xbox", hints: ["Consola", "Mando", "Jugar"] },
        { civ: "Ferrari", imp: "Lamborghini", hints: ["Coche", "Lujo", "Rápido"] },
        { civ: "Mercedes", imp: "BMW", hints: ["Coche", "Alemán", "Marca"] },
        { civ: "Nike", imp: "Adidas", hints: ["Deporte", "Ropa", "Marca"] },
        { civ: "CocaCola", imp: "Pepsi", hints: ["Refresco", "Bebida", "Gas"] },
        { civ: "McDonalds", imp: "Burger King", hints: ["Hamburguesa", "Rápida", "Comida"] },
        { civ: "Visa", imp: "Mastercard", hints: ["Tarjeta", "Pagar", "Banco"] },
        { civ: "Ikea", imp: "Leroy Merlin", hints: ["Muebles", "Tienda", "Casa"] },
        { civ: "Zara", imp: "H&M", hints: ["Ropa", "Tienda", "Moda"] },
        { civ: "Mercadona", imp: "Carrefour", hints: ["Supermercado", "Compra", "Comida"] },
        { civ: "Telecinco", imp: "Antena 3", hints: ["Tele", "Canal", "España"] },
        { civ: "El País", imp: "El Mundo", hints: ["Periódico", "Noticias", "Papel"] },
        { civ: "Cervantes", imp: "Quevedo", hints: ["Siglo Oro", "Escritor", "España"] },
        { civ: "Velázquez", imp: "El Greco", hints: ["Pintor", "Antiguo", "Arte"] },
        { civ: "Rosalía", imp: "C.Tangana", hints: ["Música", "Moderno", "España"] },
        { civ: "Bizarrap", imp: "Quevedo", hints: ["Productor", "Música", "Éxito"] },
        { civ: "Aitana", imp: "Lola Índigo", hints: ["Pop", "Triunfo", "Cantante"] },
    ]
};
