import { CategoryData } from './customCategoriesPart1';

export const CUSTOM_CATEGORIES_PART_5: Record<string, CategoryData[]> = {
    "Películas y series": [
        { civ: "Star Wars", imp: "Star Trek", hints: ["Espacio", "Saga", "Futuro"] },
        { civ: "Harry Potter", imp: "El Señor de los Anillos", hints: ["Magia", "Fantasía", "Saga"] },
        { civ: "Marvel", imp: "DC", hints: ["Superhéroes", "Cómics", "Películas"] },
        { civ: "Batman", imp: "Superman", hints: ["Héroe", "Capa", "Cómic"] },
        { civ: "Friends", imp: "Cómo conocí a vuestra madre", hints: ["Grupo", "Amigos", "Bar/Café"] },
        { civ: "Juego de Tronos", imp: "El Señor de los Anillos", hints: ["Espadas", "Reinos", "Fantasía"] },
        { civ: "Breaking Bad", imp: "Narcos", hints: ["Droga", "Dinero", "Crimen"] },
        { civ: "Los Simpson", imp: "Padre de Familia", hints: ["Animación", "Familia", "Humor"] },
        { civ: "Futurama", imp: "Rick y Morty", hints: ["Ciencia", "Futuro", "Animación"] },
        { civ: "Disney", imp: "Pixar", hints: ["Animación", "Niños", "Películas"] },
        { civ: "El Rey León", imp: "Bambi", hints: ["Animales", "Disney", "Triste"] },
        { civ: "Titanic", imp: "Avatar", hints: ["Cameron", "Taquilla", "Historia"] },
        { civ: "Jurassic Park", imp: "King Kong", hints: ["Monstruo", "Isla", "Grande"] },
        { civ: "Tiburón", imp: "Piranha", hints: ["Miedo", "Agua", "Dientes"] },
        { civ: "Alien", imp: "Predator", hints: ["Espacio/Selva", "Monstruo", "Matar"] },
        { civ: "Matrix", imp: "Terminator", hints: ["Máquinas", "Futuro", "Acción"] },
        { civ: "Rocky", imp: "Rambo", hints: ["Stallone", "Lucha", "Película"] },
        { civ: "James Bond", imp: "Misión Imposible", hints: ["Espía", "Acción", "Agente"] },
        { civ: "Indiana Jones", imp: "Tomb Raider", hints: ["Aventura", "Tesoros", "Ruinas"] },
        { civ: "Cazafantasmas", imp: "Gremlins", hints: ["80s", "Bichos", "Humor"] },
        { civ: "Regreso al Futuro", imp: "Doctor Who", hints: ["Tiempo", "Viajar", "Ciencia"] },
        { civ: "Stranger Things", imp: "Dark", hints: ["Misterio", "Niños/Tiempo", "Netflix"] },
        { civ: "La Casa de Papel", imp: "Vis a Vis", hints: ["Atraco/Cárcel", "España", "Mono"] },
        { civ: "Élite", imp: "Física o Química", hints: ["Instituto", "Jóvenes", "España"] },
        { civ: "Aquí no hay quien viva", imp: "La que se avecina", hints: ["Vecinos", "Comunidad", "Risa"] },
        { civ: "Cuéntame", imp: "Los Serrano", hints: ["Familia", "España", "Serie"] },
        { civ: "El Juego del Calamar", imp: "Black Mirror", hints: ["Distopía", "Muerte", "Crítica"] },
        { civ: "The Walking Dead", imp: "The Last of Us", hints: ["Zombies", "Mundo", "Supervivencia"] },
        { civ: "Vengadores", imp: "Liga Justicia", hints: ["Grupo", "Héroes", "Salvar"] },
        { civ: "Spiderman", imp: "Ironman", hints: ["Marvel", "Héroe", "Traje"] },
        { civ: "Capitán América", imp: "Thor", hints: ["Vengador", "Fuerte", "Arma"] },
        { civ: "Joker", imp: "Harley Quinn", hints: ["Locura", "Villano", "Maquillaje"] },
        { civ: "Toy Story", imp: "Shrek", hints: ["Animación", "Saga", "Risa"] },
        { civ: "Frozen", imp: "Vaiana", hints: ["Princesa", "Canción", "Disney"] },
        { civ: "Mulan", imp: "Pocahontas", hints: ["Guerrera", "Disney", "Historia"] },
        { civ: "La Sirenita", imp: "Nemo", hints: ["Mar", "Disney/Pixar", "Pez"] },
        { civ: "Minions", imp: "Pitufos", hints: ["Pequeños", "Azul/Amarillo", "Muchos"] },
        { civ: "Cenicienta", imp: "Blancanieves", hints: ["Princesa", "Cuento", "Madrastra"] },
        { civ: "Drácula", imp: "Frankenstein", hints: ["Terror", "Monstruo", "Clásico"] },
        { civ: "Exorcista", imp: "Poltergeist", hints: ["Miedo", "Niña", "Casa"] },
        { civ: "Saw", imp: "Scream", hints: ["Sangre", "Miedo", "Asesino"] },
        { civ: "Psicosis", imp: "El Resplandor", hints: ["Locura", "Cuchillo/Hacha", "Hotel"] },
        { civ: "Grease", imp: "Dirty Dancing", hints: ["Baile", "Música", "Amor"] },
        { civ: "La La Land", imp: "Mamma Mia", hints: ["Musical", "Cantar", "Película"] },
        { civ: "Bohemian Rhapsody", imp: "Rocketman", hints: ["Biografía", "Cantante", "Música"] },
        { civ: "Gladiator", imp: "Troya", hints: ["Roma/Grecia", "Guerra", "Espada"] },
        { civ: "Braveheart", imp: "300", hints: ["Guerra", "Libertad", "Batalla"] },
        { civ: "Salvar al Soldado Ryan", imp: "Dunkerque", hints: ["Guerra", "Mundial", "Soldados"] },
        { civ: "El Padrino", imp: "Scarface", hints: ["Mafia", "Crimen", "Familia"] },
        { civ: "Pulp Fiction", imp: "Kill Bill", hints: ["Tarantino", "Sangre", "Violencia"] },
        { civ: "Forrest Gump", imp: "La Vida es Bella", hints: ["Historia", "Emoción", "Vida"] },
        { civ: "Cadena Perpetua", imp: "Milla Verde", hints: ["Cárcel", "Drama", "Stephen King"] },
        { civ: "Origen", imp: "Interstellar", hints: ["Nolan", "Mente/Espacio", "Complejo"] },
        { civ: "Sexto Sentido", imp: "Los Otros", hints: ["Muertos", "Final", "Misterio"] },
        { civ: "Cazavampiros", imp: "Crepúsculo", hints: ["Vampiros", "Matar/Amar", "Adolescente"] },
        { civ: "Los Juegos del Hambre", imp: "Divergente", hints: ["Futuro", "Jóvenes", "Lucha"] },
        { civ: "Torrente", imp: "Ocho Apellidos", hints: ["España", "Risa", "Éxito"] },
        { civ: "Almodóvar", imp: "Amenábar", hints: ["Director", "España", "Cine"] },
        { civ: "Oscar", imp: "Goya", hints: ["Premio", "Cine", "Estatua"] },
        { civ: "Comedia", imp: "Drama", hints: ["Género", "Risa/Lloro", "Cine"] },
        { civ: "Terror", imp: "Suspense", hints: ["Miedo", "Tensión", "Género"] },
        { civ: "Ciencia Ficción", imp: "Fantasía", hints: ["Imaginación", "Futuro/Magia", "Género"] },
        { civ: "Documental", imp: "Noticia", hints: ["Realidad", "Cámara", "Informar"] },
        { civ: "Cortometraje", imp: "Largometraje", hints: ["Duración", "Cine", "Película"] },
        { civ: "Actor", imp: "Extra", hints: ["Película", "Salir", "Papel"] },
        { civ: "Director", imp: "Productor", hints: ["Jefe", "Mandar", "Película"] },
        { civ: "Guion", imp: "Libro", hints: ["Texto", "Historia", "Escribir"] },
        { civ: "Cámara", imp: "Foco", hints: ["Rodaje", "Imagen", "Luz"] },
        { civ: "Pantalla", imp: "Proyector", hints: ["Cine", "Imagen", "Ver"] },
        { civ: "Butaca", imp: "Sofá", hints: ["Asiento", "Cine/Casa", "Ver"] },
        { civ: "Palomitas", imp: "Nachos", hints: ["Cine", "Comer", "Snack"] },
        { civ: "Entrada", imp: "Taquilla", hints: ["Pagar", "Ticket", "Cine"] },
        { civ: "Estreno", imp: "Preestreno", hints: ["Primera", "Vez", "Película"] },
        { civ: "Tráiler", imp: "Teaser", hints: ["Anuncio", "Vídeo", "Adelanto"] },
        { civ: "Spoiler", imp: "Final", hints: ["Contar", "Destripe", "Película"] },
        { civ: "Cameo", imp: "Protagonista", hints: ["Aparecer", "Actor", "Breve"] },
        { civ: "Doblaje", imp: "Subtítulo", hints: ["Idioma", "Voz/Texto", "Traducir"] },
        { civ: "Versión Original", imp: "Doblada", hints: ["Idioma", "Voz", "Cine"] },
        { civ: "3D", imp: "IMAX", hints: ["Gafas", "Pantalla", "Realidad"] },
        { civ: "Streaming", imp: "Blu-ray", hints: ["Ver", "Casa", "Formato"] },
        { civ: "Netflix", imp: "Prime", hints: ["Plataforma", "Pagar", "Series"] },
        { civ: "Serie", imp: "Miniserie", hints: ["Capítulos", "Historia", "TV"] },
        { civ: "Temporada", imp: "Episodio", hints: ["Parte", "Serie", "Tiempo"] },
        { civ: "Maratón", imp: "Binge-watching", hints: ["Ver", "Mucho", "Seguido"] },
        { civ: "Telenovela", imp: "Reality", hints: ["TV", "Drama", "Gente"] },
        { civ: "Concurso", imp: "Telediario", hints: ["Programa", "TV", "Plató"] },
        { civ: "Mudo", imp: "Sonoro", hints: ["Cine", "Hablar", "Historia"] },
        { civ: "Blanco y Negro", imp: "Color", hints: ["Imagen", "Antiguo", "Cine"] },
        { civ: "Western", imp: "Vaqueros", hints: ["Oeste", "Pistolas", "Caballos"] },
        { civ: "Musical", imp: "Teatro", hints: ["Canciones", "Escenario", "Baile"] },
        { civ: "Créditos", imp: "Intro", hints: ["Nombres", "Final/Principio", "Letras"] },
        { civ: "Banda Sonora", imp: "Efectos", hints: ["Música", "Sonido", "Audio"] },
        { civ: "Rodaje", imp: "Ensayo", hints: ["Grabar", "Preparar", "Cámara"] },
        { civ: "Corte", imp: "Acción", hints: ["Director", "Grito", "Rodar"] },
        { civ: "Plató", imp: "Exterior", hints: ["Rodaje", "Lugar", "Decorado"] },
        { civ: "Decorado", imp: "Croma", hints: ["Fondo", "Falso", "Escenario"] },
        { civ: "Especialista", imp: "Doble", hints: ["Riesgo", "Actor", "Sustituir"] },
        { civ: "Claqueta", imp: "Megáfono", hints: ["Sonido", "Acción", "Rodaje"] },
        { civ: "Alfombra Roja", imp: "Photocall", hints: ["Famosos", "Fotos", "Gala"] },
        { civ: "Gala", imp: "Festival", hints: ["Premios", "Cine", "Evento"] }
    ],
    "Música y bandas": [
        { civ: "Pop", imp: "Rock", hints: ["Música", "Estilo", "Guitarra"] },
        { civ: "Jazz", imp: "Blues", hints: ["Trompeta/Guitarra", "EEUU", "Triste"] },
        { civ: "Rap", imp: "Trap", hints: ["Rima", "Calle", "Ritmo"] },
        { civ: "Reggaeton", imp: "Salsa", hints: ["Baile", "Latino", "Ritmo"] },
        { civ: "Clásica", imp: "Ópera", hints: ["Antigua", "Orquesta", "Voz"] },
        { civ: "Heavy Metal", imp: "Punk", hints: ["Duro", "Gritos", "Guitarra"] },
        { civ: "Indie", imp: "Alternativo", hints: ["Independiente", "Festival", "Grupo"] },
        { civ: "Techno", imp: "House", hints: ["Electrónica", "Fiesta", "DJ"] },
        { civ: "Flamenco", imp: "Copla", hints: ["España", "Guitarra", "Cante"] },
        { civ: "Sevillanas", imp: "Rumba", hints: ["Feria", "Baile", "Flamenco"] },
        { civ: "K-Pop", imp: "J-Pop", hints: ["Asia", "Grupos", "Baile"] },
        { civ: "Country", imp: "Folk", hints: ["Guitarra", "Campo", "EEUU"] },
        { civ: "Disco", imp: "Funk", hints: ["70s", "Baile", "Bola"] },
        { civ: "Soul", imp: "Gospel", hints: ["Voz", "Negra", "Sentimiento"] },
        { civ: "Reggae", imp: "Ska", hints: ["Jamaica", "Ritmo", "Relax"] },
        { civ: "Cantante", imp: "Músico", hints: ["Artista", "Escenario", "Voz"] },
        { civ: "Guitarrista", imp: "Bajista", hints: ["Cuerdas", "Grupo", "Instrumento"] },
        { civ: "Batería", imp: "Percusionista", hints: ["Ritmo", "Golpes", "Baquetas"] },
        { civ: "Pianista", imp: "Teclista", hints: ["Teclas", "Dedos", "Instrumento"] },
        { civ: "DJ", imp: "Productor", hints: ["Mezclar", "Música", "Mesa"] },
        { civ: "Solista", imp: "Banda", hints: ["Uno", "Grupo", "Escenario"] },
        { civ: "Coro", imp: "Orquesta", hints: ["Muchos", "Música", "Conjunto"] },
        { civ: "Director", imp: "Compositor", hints: ["Batuta/Escribir", "Música", "Jefe"] },
        { civ: "Tenor", imp: "Soprano", hints: ["Voz", "Ópera", "Cantar"] },
        { civ: "Fan", imp: "Groupie", hints: ["Seguidor", "Concierto", "Idolo"] },
        { civ: "Concierto", imp: "Festival", hints: ["Directo", "Música", "Gente"] },
        { civ: "Gira", imp: "Tour", hints: ["Viaje", "Conciertos", "Mundo"] },
        { civ: "Escenario", imp: "Backstage", hints: ["Lugar", "Artistas", "Público"] },
        { civ: "Micrófono", imp: "Altavoz", hints: ["Sonido", "Voz", "Amplificar"] },
        { civ: "Auriculares", imp: "Cascos", hints: ["Oído", "Escuchar", "Música"] },
        { civ: "Vinilo", imp: "CD", hints: ["Disco", "Formato", "Música"] },
        { civ: "Cassette", imp: "MP3", hints: ["Cinta", "Antiguo/Digital", "Música"] },
        { civ: "Spotify", imp: "Radio", hints: ["Escuchar", "Música", "Plataforma"] },
        { civ: "Videoclip", imp: "Directo", hints: ["Vídeo", "Canción", "Ver"] },
        { civ: "Single", imp: "Álbum", hints: ["Uno", "Disco", "Canciones"] },
        { civ: "Hit", imp: "Éxito", hints: ["Famoso", "Radio", "Top"] },
        { civ: "Versión", imp: "Cover", hints: ["Copia", "Canción", "Otro"] },
        { civ: "Remix", imp: "Original", hints: ["Mezcla", "Cambio", "Canción"] },
        { civ: "Playback", imp: "Directo", hints: ["Falso", "Voz", "Actuación"] },
        { civ: "Autotune", imp: "Voz", hints: ["Efecto", "Robot", "Corregir"] },
        { civ: "Grammy", imp: "Disco Oro", hints: ["Premio", "Música", "Ventas"] },
        { civ: "Eurovisión", imp: "OT", hints: ["Concurso", "TV", "Cantar"] },
        { civ: "Pentagrama", imp: "Partitura", hints: ["Líneas", "Notas", "Papel"] },
        { civ: "Nota", imp: "Acorde", hints: ["Sonido", "Música", "Símbolo"] },
        { civ: "Ritmo", imp: "Melodía", hints: ["Tiempo", "Sonido", "Música"] },
        { civ: "Estribillo", imp: "Estrofa", hints: ["Repetir", "Canción", "Parte"] },
        { civ: "Letra", imp: "Instrumental", hints: ["Palabras", "Cantar", "Texto"] },
        { civ: "Beatles", imp: "Stones", hints: ["Banda", "Ingleses", "60s"] },
        { civ: "Oasis", imp: "Blur", hints: ["Britpop", "Hermanos", "Rivalidad"] },
        { civ: "Nirvana", imp: "Pearl Jam", hints: ["Grunge", "90s", "Rock"] },
        { civ: "Metallica", imp: "Iron Maiden", hints: ["Metal", "Duro", "Pelo"] },
        { civ: "Queen", imp: "Pink Floyd", hints: ["Leyenda", "Rock", "Freddie"] },
        { civ: "AC/DC", imp: "Guns N' Roses", hints: ["Rock", "Guitarra", "Clásico"] },
        { civ: "Mecano", imp: "Hombres G", hints: ["España", "80s", "Pop"] },
        { civ: "Estopa", imp: "Melendi", hints: ["Rumba", "España", "Dúo/Solo"] },
        { civ: "Rosalía", imp: "C.Tangana", hints: ["Moderno", "España", "Éxito"] },
        { civ: "Shakira", imp: "JLo", hints: ["Latina", "Baile", "Pop"] },
        { civ: "Madonna", imp: "Lady Gaga", hints: ["Reina", "Pop", "Rubia"] },
        { civ: "Britney", imp: "Christina", hints: ["Pop", "2000s", "Princesa"] },
        { civ: "Justin", imp: "Harry Styles", hints: ["Chico", "Pop", "Famoso"] },
        { civ: "Beyoncé", imp: "Rihanna", hints: ["Diva", "Voz", "Pop"] },
        { civ: "Eminem", imp: "50 Cent", hints: ["Rap", "Blanco/Negro", "USA"] },
        { civ: "Bad Bunny", imp: "Anuel", hints: ["Trap", "Latino", "Puerto Rico"] },
        { civ: "Bizarrap", imp: "Quevedo", hints: ["Sesión", "Productor", "Argentina"] },
        { civ: "Violín", imp: "Viola", hints: ["Cuerda", "Arco", "Clásica"] },
        { civ: "Chelo", imp: "Contrabajo", hints: ["Grande", "Cuerda", "Suelo"] },
        { civ: "Guitarra", imp: "Ukelele", hints: ["Cuerdas", "Tocar", "Madera"] },
        { civ: "Flauta", imp: "Clarinete", hints: ["Viento", "Soplar", "Tubo"] },
        { civ: "Trompeta", imp: "Trombón", hints: ["Metal", "Viento", "Dorado"] },
        { civ: "Saxofón", imp: "Trompeta", hints: ["Jazz", "Viento", "Curvo"] },
        { civ: "Batería", imp: "Cajón", hints: ["Percusión", "Golpear", "Ritmo"] },
        { civ: "Piano", imp: "Órgano", hints: ["Teclas", "Iglesia", "Grande"] },
        { civ: "Arpa", imp: "Lira", hints: ["Cuerdas", "Ángel", "Dedos"] },
        { civ: "Maracas", imp: "Pandereta", hints: ["Agitar", "Mano", "Ritmo"] },
        { civ: "Xilófono", imp: "Metalófono", hints: ["Golpear", "Placas", "Niños"] },
        { civ: "Gaita", imp: "Acordeón", hints: ["Aire", "Fuelle", "Galicia"] },
        { civ: "Púa", imp: "Baqueta", hints: ["Tocar", "Objeto", "Mano"] },
        { civ: "Afinador", imp: "Metrónomo", hints: ["Ajustar", "Ritmo", "Aparato"] },
        { civ: "Amplificador", imp: "Pedal", hints: ["Sonido", "Guitarra", "Electricidad"] },
        { civ: "Cable", imp: "Inalámbrico", hints: ["Conexión", "Micro", "Suelo"] },
        { civ: "Salsa", imp: "Bachata", hints: ["Baile", "Caribe", "Pareja"] },
        { civ: "Tango", imp: "Vals", hints: ["Baile", "Salón", "Pareja"] },
        { civ: "Pasodoble", imp: "Jota", hints: ["España", "Baile", "Fiesta"] },
        { civ: "Himno", imp: "Canción", hints: ["País", "Soelmne", "Fútbol"] },
        { civ: "Villancico", imp: "Nana", hints: ["Navidad/Dormir", "Cantar", "Niños"] },
        { civ: "Silbar", imp: "Tararear", hints: ["Boca", "Melodía", "SinLetra"] },
        { civ: "Aplauso", imp: "Abucheo", hints: ["Público", "Final", "Manos"] },
        { civ: "Bis", imp: "Fin", hints: ["Otra", "Final", "Concierto"] }
    ],
    "Profesiones": [
        { civ: "Médico", imp: "Enfermero", hints: ["Hospital", "Salud", "Bata"] },
        { civ: "Cirujano", imp: "Dentista", hints: ["Operar", "Boca", "Medicina"] },
        { civ: "Veterinario", imp: "Zoólogo", hints: ["Animales", "Curar", "Salud"] },
        { civ: "Psicólogo", imp: "Psiquiatra", hints: ["Mente", "Hablar", "Diván"] },
        { civ: "Farmacéutico", imp: "Químico", hints: ["Medicinas", "Laboratorio", "Tienda"] },
        { civ: "Profesor", imp: "Maestro", hints: ["Enseñar", "Escuela", "Alumnos"] },
        { civ: "Director", imp: "Jefe", hints: ["Mandar", "Escuela/Oficina", "Líder"] },
        { civ: "Entrenador", imp: "Árbitro", hints: ["Deporte", "Equipo", "Silbato"] },
        { civ: "Policía", imp: "Guardia Civil", hints: ["Ley", "Uniforme", "Seguridad"] },
        { civ: "Bombero", imp: "Militar", hints: ["Fuego/Guerra", "Uniforme", "Riesgo"] },
        { civ: "Detective", imp: "Espía", hints: ["Investigar", "Secreto", "Lupa"] },
        { civ: "Abogado", imp: "Juez", hints: ["Ley", "Juicio", "Tribunal"] },
        { civ: "Fiscal", imp: "Notario", hints: ["Ley", "Acusar/Firmar", "Papeles"] },
        { civ: "Político", imp: "Alcalde", hints: ["Votos", "Mandar", "Público"] },
        { civ: "Rey", imp: "Presidente", hints: ["Mandar", "País", "Corona"] },
        { civ: "Periodista", imp: "Presentador", hints: ["Noticias", "TV/Papel", "Informar"] },
        { civ: "Fotógrafo", imp: "Cámara", hints: ["Imagen", "Foto/Vídeo", "Objetivo"] },
        { civ: "Escritor", imp: "Guionista", hints: ["Libros", "Historias", "Escribir"] },
        { civ: "Pintor", imp: "Escultor", hints: ["Arte", "Cuadro", "Artista"] },
        { civ: "Músico", imp: "Cantante", hints: ["Arte", "Sonido", "Escenario"] },
        { civ: "Actor", imp: "Modelo", hints: ["Fama", "Cámara", "Papel"] },
        { civ: "Arquitecto", imp: "Ingeniero", hints: ["Planos", "Edificios", "Diseñar"] },
        { civ: "Albañil", imp: "Obrero", hints: ["Construcción", "Ladrillo", "Obra"] },
        { civ: "Fontanero", imp: "Electricista", hints: ["Agua/Luz", "Reparar", "Casa"] },
        { civ: "Carpintero", imp: "Ebanista", hints: ["Madera", "Muebles", "Sierra"] },
        { civ: "Pintor", imp: "Decorador", hints: ["Pared", "Brocha", "Casa"] },
        { civ: "Jardinero", imp: "Agricultor", hints: ["Plantas", "Campo", "Tierra"] },
        { civ: "Ganadero", imp: "Pastor", hints: ["Animales", "Granja", "Campo"] },
        { civ: "Pescador", imp: "Marinero", hints: ["Mar", "Barco", "Peces"] },
        { civ: "Cocinero", imp: "Camarero", hints: ["Restaurante", "Comida", "Servir"] },
        { civ: "Panadero", imp: "Pastelero", hints: ["Harina", "Horno", "Dulce/Salado"] },
        { civ: "Carnicero", imp: "Pescadero", hints: ["Vender", "Mercado", "Comida"] },
        { civ: "Frutero", imp: "Tendero", hints: ["Vender", "Tienda", "Comida"] },
        { civ: "Cajero", imp: "Dependiente", hints: ["Cobrar", "Tienda", "Dinero"] },
        { civ: "Repartidor", imp: "Cartero", hints: ["Paquete", "Moto", "Entrega"] },
        { civ: "Taxista", imp: "Chófer", hints: ["Coche", "Conducir", "Pasajero"] },
        { civ: "Camionero", imp: "Conductor", hints: ["Carretera", "Grande", "Transporte"] },
        { civ: "Piloto", imp: "Azafata", hints: ["Avión", "Volar", "Viaje"] },
        { civ: "Mecánico", imp: "Técnico", hints: ["Taller", "Reparar", "Coche"] },
        { civ: "Informático", imp: "Programador", hints: ["Ordenador", "Código", "Oficina"] },
        { civ: "Científico", imp: "Investigador", hints: ["Laboratorio", "Bata", "Ciencia"] },
        { civ: "Astronauta", imp: "Astrónomo", hints: ["Espacio", "Cohete", "Estrellas"] },
        { civ: "Arqueólogo", imp: "Historiador", hints: ["Pasado", "Excavar", "Huesos"] },
        { civ: "Bibliotecario", imp: "Librero", hints: ["Libros", "Silencio", "Leer"] },
        { civ: "Sacerdote", imp: "Monja", hints: ["Iglesia", "Dios", "Misa"] },
        { civ: "Militar", imp: "Soldado", hints: ["Ejército", "Arma", "Defensa"] },
        { civ: "Vigilante", imp: "Portero", hints: ["Seguridad", "Puerta", "Edificio"] },
        { civ: "Limpiador", imp: "Basurero", hints: ["Suciedad", "Limpiar", "Calle"] },
        { civ: "Peluquero", imp: "Barbero", hints: ["Pelo", "Tijeras", "Cortar"] },
        { civ: "Maquillador", imp: "Esteticista", hints: ["Cara", "Belleza", "Pintar"] },
        { civ: "Sastre", imp: "Modista", hints: ["Ropa", "Coser", "Aguja"] },
        { civ: "Zapatero", imp: "Relojero", hints: ["Arreglar", "Zapatos/Reloj", "Taller"] },
        { civ: "Joyero", imp: "Cerrajero", hints: ["Oro/Llaves", "Metal", "Tienda"] },
        { civ: "Banquero", imp: "Contable", hints: ["Dinero", "Números", "Banco"] },
        { civ: "Empresario", imp: "Autónomo", hints: ["Negocio", "Dinero", "Jefe"] },
        { civ: "Secretario", imp: "Administrativo", hints: ["Oficina", "Papeles", "Teléfono"] },
        { civ: "Recepcionista", imp: "Telefonista", hints: ["Entrada", "Llamadas", "Atender"] },
        { civ: "Traductor", imp: "Intérprete", hints: ["Idiomas", "Hablar", "Texto"] },
        { civ: "Guía", imp: "Monitor", hints: ["Turismo", "Grupo", "Explicar"] },
        { civ: "Deportista", imp: "Atleta", hints: ["Ejercicio", "Competición", "Físico"] },
        { civ: "Youtuber", imp: "Influencer", hints: ["Internet", "Vídeo", "Fama"] },
        { civ: "Hacker", imp: "Gamer", hints: ["Ordenador", "Juego/Código", "Pantalla"] },
        { civ: "Payaso", imp: "Mago", hints: ["Circo", "Risa", "Niños"] },
        { civ: "Torero", imp: "Bailaor", hints: ["Plaza/Tablao", "Arte", "Traje"] },
        { civ: "Minero", imp: "Espeleólogo", hints: ["Cueva", "Tierra", "Oscuro"] },
        { civ: "Buzo", imp: "Socorrista", hints: ["Agua", "Mar", "Playa"] },
        { civ: "Ladrón", imp: "Atracador", hints: ["Robar", "Delito", "Policía"] },
        { civ: "Mendigo", imp: "Vagabundo", hints: ["Calle", "Pobre", "Dinero"] },
        { civ: "Jubilado", imp: "Parado", hints: ["NoTrabaja", "Mayor", "Tiempo"] },
        { civ: "Estudiante", imp: "Becario", hints: ["Aprender", "Joven", "Libros"] },
        { civ: "Ama de Casa", imp: "Criada", hints: ["Hogar", "Limpiar", "Familia"] },
        { civ: "Niñera", imp: "Cuidador", hints: ["Niños", "Vigilar", "Casa"] },
        { civ: "Mayordomo", imp: "Chófer", hints: ["Servicio", "Rico", "Casa/Coche"] },
        { civ: "Vendedor", imp: "Comercial", hints: ["Vender", "Producto", "Hablar"] },
        { civ: "Consultor", imp: "Asesor", hints: ["Ayuda", "Empresa", "Experto"] },
        { civ: "Diseñador", imp: "Publicista", hints: ["Crear", "Imagen", "Vender"] },
        { civ: "Editor", imp: "Corrector", hints: ["Texto", "Libro", "Revisar"] },
        { civ: "Agente", imp: "Representante", hints: ["Famoso", "Negocio", "Contrato"] },
        { civ: "Árbitro", imp: "Juez", hints: ["Decidir", "Normas", "Deporte/Ley"] },
        { civ: "Coach", imp: "Psicólogo", hints: ["Ayuda", "Mente", "Meta"] },
        { civ: "Cura", imp: "Obispo", hints: ["Iglesia", "Misa", "Religión"] },
        { civ: "Monje", imp: "Ermitaño", hints: ["Rezar", "Solo", "Aislado"] },
        { civ: "Misionero", imp: "Voluntario", hints: ["Ayuda", "Viaje", "Gente"] },
        { civ: "Filósofo", imp: "Pensador", hints: ["Mente", "Ideas", "Saber"] },
        { civ: "Poeta", imp: "Novelista", hints: ["Escribir", "Versos", "Libro"] },
        { civ: "Crítico", imp: "Experto", hints: ["Opinar", "Valorar", "Saber"] },
        { civ: "Inventur", imp: "Científico", hints: ["Crear", "Nuevo", "Idea"] },
        { civ: "Explorador", imp: "Aventurero", hints: ["Viaje", "Descubrir", "Mundo"] },
        { civ: "Pirata", imp: "Corsario", hints: ["Barco", "Robar", "Parche"] },
        { civ: "Vikingo", imp: "Espartano", hints: ["Guerrero", "Antiguo", "Lucha"] },
        { civ: "Gladiador", imp: "Luchador", hints: ["Arena", "Roma", "Pelea"] },
        { civ: "Samurái", imp: "Ninja", hints: ["Japón", "Espada", "Honor"] },
        { civ: "Rey", imp: "Emperador", hints: ["Corona", "Mandar", "Reino"] },
        { civ: "Faraón", imp: "Momia", hints: ["Egipto", "Mandar", "Pirámide"] },
        { civ: "Dictador", imp: "Tirano", hints: ["Mandar", "Malo", "Poder"] },
        { civ: "Espía", imp: "Agente Secreto", hints: ["Misión", "Incógnito", "Información"] },
        { civ: "Sicario", imp: "Asesino", hints: ["Matar", "Dinero", "Crimen"] },
        { civ: "Mafioso", imp: "Gánster", hints: ["Crimen", "Familia", "Ilegal"] },
        { civ: "Contrabandista", imp: "Traficante", hints: ["Ilegal", "Pasar", "Frontera"] }
    ]
};
